### ISSUE TITLE
Confused how to run server tests in watch mode

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode#102]
I've tried `gulp server-test` and `gulp test-watch-all` but I can't for the life of me figure out how to setup auto-running server-side tests.

I can run tests manually with `gulp test-dev`, but the other two just start up a file browser at `localhost:3001`. 

How do I do this?

**Comment by jchip** [comment]
`test-watch` is suppose to do this.  It's very possible that is broken at the moment since it's not part of the CI verification.  Thanks for reporting this.

**Comment by DavidOrchard** [comment]
test-watch should be fixed in next release.

**Comment by sergesemashko** [comment]
I have the latest app from electrode generator and it gives me `Chrome 60.0.3112 (Mac OS X 10.11.4): Executed 0 of 0 ERROR (0.041 secs / 0 secs)` in `test-watch`, however `clap check` works fine.  
Any ideas how to solve that?

**Comment by sergesemashko** [comment]
It turned out that karma launched browser cannot get webpack builld due to CORS issue. Following code in my custom webpack dev config fixed the issue: 
```js
////archetype/config/webpack/webpack.config.hot.js

module.exports = function( composer, options, compose ) {
  // Now that the composer has been updated, compose the final config
  const config = compose();
  config.devServer.disableHostCheck = true;
  config.devServer.headers = {
    "Access-Control-Allow-Origin": "*"
  };
  return config;
};

```
