### ISSUE TITLE
Will there be support for ES7+ in the future?

### ISSUE THREAD

**Issue by mmmikeal** [electrode-io/electrode#1026]
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```

**Comment by jchip** [comment]
that depends on whatever the version of babel we are using supports. :)
