### ISSUE TITLE
Custom .eslintrc should allow all valid .eslintrc file extensions

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode#104]
See https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app/arch-gulpfile.js#L61

Right now, only allows:

- `.eslintrc`
- `.eslintrc.json`
- `.eslintrc.yml`

Should support:

- above and
- `.eslintrc.yaml`
- `.eslintrc.js`

Perhaps also `package.json` (see http://eslint.org/docs/user-guide/configuring#configuration-file-formats)

**Comment by cross311** [comment]
Was just looking at this code, so I figured I would just open a pull for it.

**Comment by ShotaMegre** [comment]
I can't figure out if the component has a feature to extend the existing eslint rules coming from WallMart.
Is there a way to do that?
I want to change some errors to warnings and fix the indent for Switch/case.
