### ISSUE TITLE
How to control SSR CSS classname and a flicker problem.

### ISSUE THREAD

**Issue by LeeFrancis** [electrode-io/electrode#105]
Running the following 
```
gulp build
gulp server-prod
```
results in my SSR content having classnames like "filter-menu__menuHeader___1sOcW"
But when the bundled js execs it replaces that with hashed classnames that match the bundled CSS, eg r8t_xEkXa-m0lW__s2ZE- _2dLkwB0yvSEcAXl8as6gOn.
The result is that I see an unstyled page until the js evaluates and corrects the classnames. (a substantial flicker).
I know you can control the names with localIdentName in CSS modules but I cant see where to set that.
Any help is much appreciated.

**Comment by jmcriffey** [comment]
@LeeFrancis What version of `electrode-archetype-react-app` are you using? This was a bug that should have been addressed. What does your `server/index.js` file look like?

Here is an example that works for me with the correct class names both client and server side: 
https://github.com/electrode-samples/electrode-pwa-examples/blob/master/examples/product/server/index.js#L54

**Comment by LeeFrancis** [comment]
Thank you.. I am slowly getting a better understanding of the supporting Archetype projects and how to access different config values.
I had 
```
supports.cssModuleHook({
    generateScopedName: "[name]__[local]___[hash:base64:5]"
});
```
Which was forcing my delivered markup to be different to my compiled assets.
I changed to make an empty call to cssModuleHook and it works perfectly.
