### ISSUE TITLE
dll-util version verification does not resolve modules correctly

### ISSUE THREAD

**Issue by Anujan** [electrode-io/electrode#1076]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `MacOS 10.13.6`
* *Node version:* `8.11.1` (run `node --version` in your terminal)
* *npm version:* `5.6.0` (run `npm --version` in your terminal)

## Expected behavior

The electrode DLL plugin should be doing the version verification by recursively checking the parent folders for a "node_modules" folder.

## Current behavior

The Electrode DLL plugin throws error messages when packages aren't in your node_modules folder. We use a monorepo setup and have node_modules in our root of the repo. The [dll-util](https://github.com/electrode-io/electrode/blob/da860b72b97d406c4795e8821daedec5ba60df3d/packages/electrode-archetype-react-app-dev/config/webpack/util/dll-util.js#L75) file expects it to be in the node_modules of the package. This is different from NodeJS' module resolution. 

Note: The DLL plugin still does the bundling correctly -- it's only version verification that is broken.

## Steps to reproduce the behavior

Move your node_modules folder back by one folder, then run the app with the dll plugin setup.

## Command line output

```
```info: Electrode DLL modules to be loaded @walmartca/ui-vendor-dlls
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module babel-runtime installed at node_modules/babel-runtime. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module core-js installed at node_modules/core-js. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module history installed at node_modules/history. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module hoist-non-react-statics installed at node_modules/hoist-non-react-statics. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module invariant installed at node_modules/invariant. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module isarray installed at node_modules/isarray. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module lodash-es installed at node_modules/lodash-es. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module object-assign installed at node_modules/object-assign. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module path-to-regexp installed at node_modules/path-to-regexp. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module process installed at node_modules/process. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module prop-types installed at node_modules/prop-types. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module react-dom installed at node_modules/react-dom. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module react-redux installed at node_modules/react-redux. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module react-router installed at node_modules/react-router. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module warning installed at node_modules/react-router/node_modules/warning. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module react installed at node_modules/react. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module redux installed at node_modules/redux. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module resolve-pathname installed at node_modules/resolve-pathname. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module scheduler installed at node_modules/scheduler. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module symbol-observable installed at node_modules/symbol-observable. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module value-equal installed at node_modules/value-equal. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module warning installed at node_modules/warning. Skipping it.
info: Electrode DLL module @walmartca/ui-vendor-dlls - You don't have module webpack installed at node_modules/webpack. Skipping it.```
```

**Comment by jchip** [comment]
The issue is actually not that simple.

- When Electrode create a npm DLL module for you, the paths to each source is fixed at the time the DLL got compiled.
- Therefore, if your app doesn't have the same module at the same location as the DLL, webpack will not be able to connect your code to use the files from within the DLL.
- So what the DLL version check util is doing is just taking the paths that're stored in the DLL's manifest and ensure you have them at the same location, and warn you.

Also, a side note: you are getting so many warnings is because you are using yarn and its workspace feature.

Some ideas I have that may help with the webpack DLL paths is to try to match them up according to app's node_modules locations and update the DLL manifest file.

**Comment by Anujan** [comment]
Can we use `require.resolve` to get the module path instead?

**Comment by jchip** [comment]
dll-util doesn't resolve, it just validates and inform you.

- DLLs were built and published with paths from its node_modules
- hopefully your app install modules in the DLL under the same paths in node_modules, and dll-util validates it for you
