### ISSUE TITLE
electrode-archetype-react-app: webpack build fails in development 

### ISSUE THREAD

**Issue by Anujan** [electrode-io/electrode#1079]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `MacOS`
* *Node version:* `8.11.1` (run `node --version` in your terminal)
* *npm version:* `5.6.0` (run `npm --version` in your terminal)

## Expected behavior

Webpack builds successfully

## Current behavior

Webpack fails due to configuration option that shouldn't exist. I was able to fix this by removing the `optimizations` from [here](https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js#L40) but I'm not sure if it's the correct change.

## Steps to reproduce the behavior

run `clap dev`

## Command line output

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'optimization'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           optimization: ...
         }
       })
     ]
```

**Comment by Anujan** [comment]
Note that this is using electrode-archetype-react-app version 6.0.6

**Comment by didi0613** [comment]
Hi Anujan, @Anujan 

Thanks for reporting this issue!

Few things wants to explain here:

- The `uglify.js` is for `UglifyJsPlugin` which is included under production mode. When you run `clap dev`, it will use the `dev` config for development mode.

- From the webpack v4 documentation mentioned [here](https://webpack.js.org/configuration/optimization/), the `optimization` field should be a property at the root level of the webpack config:

```
module.exports = {
  //...
  optimization: {
    minimize: false
  }
};
```

And the final configuration should look similar to:
```
{
  "cache": true,
  "context": "/Users/s0d00px/Electrode/test-app/src/client",
  "entry": "./app.jsx",
  "output": {...},
  "resolve": {
    "alias": {},
    "symlinks": true,
    "plugins": [...],
    "modules":  [...],
    "extensions": [...],
  },
  "resolveLoader": {
    "symlinks": true,
    "modules": [...],
    "plugins": [...]
  },
  "module": {
    "rules": [...]
  },
  "plugins": [...],
  "mode": "development",
  "devServer": {...},
  "optimization": {
    "noEmitOnErrors": true
  }
}
```

To resolve your issue, please check few things for me:
- With `electrode-archetype-react-app` v6, it will only support webpack v4, can you please help to verify that your app does not install any previous version of webpack?
- If you installed webpack 4 only, can you please print out the final configurations and compared with the one above?

**Comment by Anujan** [comment]
@didi0613  Thanks. Clearing my lockfile seems to have fixed this.
