### ISSUE TITLE
Add directions for running start scripts

### ISSUE THREAD

**Issue by jlim81** [electrode-io/electrode#108]
This is related to this issue - https://github.com/electrode-io/electrode/issues/88
The documentation is not clear on how to build production bundles locally. The users in this issue is report that it is broken, but it works for @animesh10. It might actually be working, but we don't know the steps for building, etc. Either way, it should it documented somewhere for clarification.

**Comment by vimcat** [comment]
I just now tried to deploy to heroku a fresh electrode install. Here are the errors I got:

remote:        Running heroku-postbuild
remote:
remote:        > electrode-sample@0.0.1 heroku-postbuild /tmp/build_b26328502c90214e955ec17a9d95851e
remote:        > gulp build
remote:
remote: sh: 1: gulp: not found
remote:
remote: npm ERR! Linux 3.13.0-105-generic
remote: npm ERR! argv "/tmp/build_b26328502c90214e955ec17a9d95851e/.heroku/node/bin/node" "/tmp/build_b26328502c90214e955ec17a9d95851e/.heroku/node/bin/npm" "run" "heroku-postbuild" "--if-present"
remote: npm ERR! node v6.9.1
remote: npm ERR! npm  v4.1.1
remote: npm ERR! file sh
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno ENOENT
remote: npm ERR! syscall spawn
remote: npm ERR! electrode-sample@0.0.1 heroku-postbuild: `gulp build`
remote: npm ERR! spawn ENOENT
remote: npm ERR!
remote: npm ERR! Failed at the electrode-sample@0.0.1 heroku-postbuild script 'gulp build'.
