### ISSUE TITLE
prodBundleBase prefix doesn't apply to images

### ISSUE THREAD

**Issue by kartik-jethani** [electrode-io/electrode#1086]
Hi,

My electrode app corresponds to a prodBundleBase prefix "/myapp/js/".
My js and CSS bundles get served properly but images in do not have a prefix applied.
My expected image path is "/myapp/js/img01.png" whereas the actual path doesn't pick the prefix and comes like "/js/img01.png" and doesn't load as it's not there in that directory.

Any image path that I give from within css files comes prefixed with "/myapp/js/img02.png". I guess this is because it picks relative path from CSS files which do have the prefix applied.

Can someone please help?

**Comment by jchip** [comment]
do you have a sample that we can try to repro the issue? thanks.
