### ISSUE TITLE
Dynamic pageTitle in electrode-react-webapp?

### ISSUE THREAD

**Issue by daviddyess** [electrode-io/electrode#110]
Is there a way to make the page title dynamic? Preferably the rendered title tag, not just the document title in the browser. If someone can lead me in the right direction, I'd be happy to submit a pull request for the boilerplate.

**Comment by ananavati** [comment]
@daviddyess 

webapp currently supports a config option to customize the content inside `pageTitle: string`

example usage: https://github.com/electrode-io/electrode/blob/271673d50f45329e988647739516a616b6b641b3/samples/universal-material-ui/config/default.json#L15

options being read here in webapp: https://github.com/electrode-io/electrode/blob/3d8dde5c74e5e4ab84e142acb1e8249e585d14aa/packages/electrode-react-webapp/lib/react-webapp.js#L235

this is where pageTitle gets injected into the html template:
https://github.com/electrode-io/electrode/blob/3d8dde5c74e5e4ab84e142acb1e8249e585d14aa/packages/electrode-react-webapp/lib/index.html#L7

**Comment by daviddyess** [comment]
@ananavanti Thank you for the response, loving the work you guys are doing. I had drilled down to those, but I'm not seeing how I can manipulate the pageTitle from outside of the config file. 

What I'm wanting to do is have a base title and then prepend a route specific title to it, fairly standard. I'm using a data API that would specify the route page title as its content driven. Is this beyond the scope of webapp or is there a place in its workflow I can inject the page title from outside of webapp?

**Comment by citelao** [comment]
@daviddyess it is currently impossible as far as I know, at least with the current system

**Comment by daviddyess** [comment]
Right, too much plumbing. The order of operations isn't built for it. What I'm doing is retooling the webapp plugin to pass the route to an optional module to fetch head data (because meta data and such would be useful as well). I haven't had time to finish it, but that seems like the best approach to me and doesn't involve too many changes elsewhere (plus it's optional). I'll do a pull request once I'm finished with it.

**Comment by citelao** [comment]
NFL's [react-helmet](https://github.com/nfl/react-helmet) might really help with this :D

**Comment by karlhorky** [comment]
@daviddyess could you post your current state of this as a git repo or something? Just trying to do something similar and it would be great to collaborate on this PR.

**Comment by karlhorky** [comment]
At @kununu have a working version of `react-helmet` integrated with Electrode (credit to @dennisat @kaytcat @FreaKzero).

@dennisat will open a pull request to Electrode soon for this!

**Comment by dennisat** [comment]
With [this PR](https://github.com/electrode-io/electrode/pull/299) using `react-helmet` you can set the `<title>` (and some other tags).

**Comment by karlhorky** [comment]
🎉 PR is open! electrode-io/electrode#299

**Comment by ishwinder** [comment]
Doesn't seem to render the title server side. This happens with helmet.rewind which seems kind of bit limiting in the current flow of electrode-webapp. Any thoughts ?

**Comment by karanmartian** [comment]
Hey guys so the latest release of electrode-webapp doesnt have any Helmet server side rendering. It was removed back in August I believe. How are we supposed to do server side dynamic title with latest electrode-webapp? This is important for me and many I believe because it affects Search Engine Optimization in a big way.

**Comment by ishwinder** [comment]
You have to define your own token handler and render out the helmet content that you want to do ..

Check this commit .. https://github.com/electrode-io/electrode/commit/4c5a4a75c96ce31ce49eb0c0d05e2945c9184f39

Towards the end, there is a spec on how to use helmet in the handler .. The file is packages/electrode-react-webapp/test/fixtures/react-helmet-handler.js

HTH.

**Comment by karanmartian** [comment]
Hi HTH,
Thats a great pointer and I understand the code but I dont get the whole test / spec thing. Is there a more plug and play file that i can in include in my source code? I would really be very thankful for that.

Best,
Karan

**Comment by karanmartian** [comment]
Ok could you just let me know where exactly do I have to register this custom handler? there is little documentation on this. I read the design.md file too.

**Comment by karanmartian** [comment]
@ishwinder could you let me know where exactly do I have to register this custom handler? there is little documentation on this. I read the design.md file too.

**Comment by ishwinder** [comment]
Token handler is registered with electrode-react-webapp .. In your electrode config, find the key: "webapp" and register your customer handler like this ..

```
"webapp": {
      "module": "electrode-react-webapp/lib/express",
      "options": {
        "pageTitle": "Default Page Title",
        "paths": {
          "*": {
            "content": {
              "module": "./{{env.APP_SRC_DIR}}/server/views/index-view"
            }
          }
        },
        "tokenHandler": "./{{env.APP_SRC_DIR}}/server/token-handler"
      }
    }
```

**Comment by karanmartian** [comment]
Thanks so much @ishwinder ! Works like magic! Here's the token handler i used exactly like in the commit. Just wanted to make sure that its ok.

`"use strict";`

`import Helmet from "react-helmet";`

`const emptyTitleRegex = /<title[^>]*><\/title>/;`

`module.exports = options => {
  const routeOptions = options.routeOptions;
  const iconStats = options.routeData.iconStats;`

 `return {
    INITIALIZE: context => {
      context.$.user.helmet = Helmet.renderStatic();
    },`

    PAGE_TITLE: context => {
      const helmet = context.$.user.helmet;
      const helmetTitleScript = helmet.title.toString();
      const helmetTitleEmpty = helmetTitleScript.match(emptyTitleRegex);

      return helmetTitleEmpty ? `<title>${routeOptions.pageTitle}</title>` : helmetTitleScript;
    },

    WEBAPP_HEADER_BUNDLES: (context, next) => {
      context.handleResult(
        "WEBAPP_HEADER_BUNDLES",
        context.tokenHandler.WEBAPP_HEADER_BUNDLES(context), // eslint-disable-line
        () => {
          const scriptsFromHelmet = ["link", "style", "script", "noscript"]
            .map(tagName => context.$.user.helmet[tagName].toString())
            .join("");
          context.output.add(`<!--scripts from helmet-->${scriptsFromHelmet}`);
          next();
        }
      );
    },

    META_TAGS: context => {
      return context.$.user.helmet.meta.toString() + iconStats;
    }
  `};`
`};`

**Comment by ishwinder** [comment]
Glad that it helped.

Default handler is good to go with the default index-view. Ofcourse, You can always add custom index-view adding custom tokens and handling them here (Like schema ld/json etc since you talked about search engine).

**Comment by karanmartian** [comment]
@ishwinder yea so the other thing that is still kind of a conundrum to me is lets say there is data from the Db that loads after an ajax call once the javascript is loaded. I want to incorporate that data as part of the title of the page (e.g. Username - Page Title). Is that in any way possible to do at server side rendering? So that search engines like google can wait for the whole page to load and then extract page meta data, title etc.

**Comment by ishwinder** [comment]
Check this sample out .. https://github.com/electrode-io/electrode/tree/master/samples/universal-react-node

This fetches data from the database so that the search engine sees the data. Basically, you fetch the data while the server is loading and then do rendering client side.

**Comment by karanmartian** [comment]
@ishwinder Is this the same boilerplate that gets generated when you type the command ignite generate-app as per the electrode.io documentation? i am currently using that. Do you think the boilerplate you mentioned is much better?

**Comment by ishwinder** [comment]
I am not sure about the boilerplate with ignite .. I just saw the sample and it works like a charm.

**Comment by karanmartian** [comment]
Hi @ishwinder is there any example of fetching data from db that search engine sees in the below boilerplate that you mentioned? I looked into the code but couldnt find a particular example for doing this.
———————
Check this sample out .. https://github.com/electrode-io/electrode/tree/master/samples/universal-react-node

This fetches data from the database so that the search engine sees the data. Basically, you fetch the data from server on first load and then do rendering client side.

**Comment by ishwinder** [comment]
Its quite a late reply and you would have figured this out by now .. Just in case, Check this file on how to initialise a store server side .. When the store is initliliazed the React component will be rendered as per the values in the store.

https://github.com/electrode-io/electrode/blob/master/samples/universal-react-node/src/server/views/index-view.jsx

**Comment by karanmartian** [comment]
Thats great and no I hadn’t actually figured it out:) So thats where you would write a quick db query to pull your required info you want the search engine to see for that page(route) if i am understanding this. But wont it only work on a full refresh of the page? I dont know how search engines crawl exactly but once they do an initial page load and then traverse the connected pages of the site the store is not going to be reinitialized everytime or do they traverse by doing a full refresh of the page every time they want to crawl a particular page(route)?

**Comment by ishwinder** [comment]
True, you will fetch the data required at that place .. Traditional bots will treat the react router link with a page refresh. Google/Bing etc are advanced search engines, they can execute the js as well as refresh the page. Make sure that both the versions are similar.

**Comment by himanshualturaab** [comment]
> Hey guys so the latest release of electrode-webapp doesnt have any Helmet server side rendering. It was removed back in August I believe. How are we supposed to do server side dynamic title with latest electrode-webapp? This is important for me and many I believe because it affects Search Engine Optimization in a big way.



you can implement it by gatsby which is client side rendering ( prerendering )
