### ISSUE TITLE
"@babel/runtime" should be a dependency of `electrode-archetype-react-app`

### ISSUE THREAD

**Issue by romanlv** [electrode-io/electrode#1107]
## Type of issue
bug

## My environment

"electrode-archetype-react-app": "6.1.0" 
"electrode-archetype-react-app-dev": "6.1.0"

## Expected behavior

`yarn install --production` to install all dependencies needed to run the app

## Current behavior
Currently `@babel/runtime` is a dependency of `electrode-archetype-react-app-dev` only

When app is prepared for prod deployment `yarn install -production` removes dev dependencies, which includes `@babel/runtime`

When `electrode-archetype-react-app-dev` is listed as prod dependency, then electrode tres to write to log file, which is undesirable in our prod env

## Steps to reproduce the behavior

- create electrode app, 
- make sure that `electrode-archetype-react-app-dev` is in dev dependencies
- `yarn install --production`
- `yarn build && yarn prod`

**Comment by jchip** [comment]
we actually didn't run into this issue because we are using electrode-redux-router-engine which pulls in react-redux that pulls `@babel/runtime`.  are you not using electrode-redux-router-engine?  anyways, fix PR opened.  thanks for the report.

**Comment by romanlv** [comment]
`"electrode-redux-router-engine": "2.1.8",` is listed in prod dependencies, but it didn't work, for now i had to add `@babel/runtime` as a direct dependency, maybe it's `yarn` messing it up...?
