### ISSUE TITLE
cssModulesSupport

### ISSUE THREAD

**Issue by thiagoneves** [electrode-io/electrode#1116]
How can i disable toe cssModuleSupport?

Thanks

**Comment by brandonburkett** [comment]
I believe set `process.env.CSS_MODULE_SUPPORT = true;` in xlcap.js should do it.

**Comment by jchip** [comment]
the env, or you can completely disable it and not even pull in the dependencies:

https://github.com/electrode-io/electrode/tree/master/packages/electrode-archetype-opt-css-module#electrode-archetype-option-css-module
