### ISSUE TITLE
init attribute example needed

### ISSUE THREAD

**Issue by chetank628** [electrode-io/electrode#1117]
!!need a help
can anyone help me about init attribute for redux router engine the example provided in the documentation is just a skeleton 
```
export default function reduxInit(options) {
  const name = options.route.name;
  // if you didn't specify a name for the route, then you have to provide
  // some default name for your route's reducer and redux state data.
  return {
    reducer: {
      [name]: (state, action) => {
        // reducer code
      }
    },
    initialState: {
      [name]: {
        // initial redux state data
      }
    }
  };
}
```
can anyone give me any working example or explain how to use this how can we load the initial state with api call how can i use redux thunk in it if possible, what is the use of reducer here how is action dispatched from here  a working example would be  great

**Comment by 1846689910** [comment]
Hi @chetank628,
The application as generated by Electrode has demos for using the `init` routes.  A copy of the app has been added to [samples/hapi-app]

[samples/hapi-app/src/client/routes.jsx] is an example using `init` in routes. As for this example,

```
    ... ...
    init: "./init-top",
    ... ...
```

the `./init-top` will reference to [samples/hapi-app/src/server/routes/init-top.jsx], which imported `reducers` and defined `initialState`

At the client entry point [samples/hapi-app/src/client/app.jsx], [samples/hapi-app/src/client/routes.jsx] was imported and a root component App was created by

```js
    const App = () => renderRoutes(routes);
```

the redux store was created with `window.__PRELOADED_STATE__` referenced to `initialState` mentioned above

```js
    const store = configureStore(window.__PRELOADED_STATE__);
```

and then the method `start` was called for

```js
ReactDOM.hydrate(
    <Provider store={store}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </Provider>,
    jsContent
  )
```

All the react components will use `reducers` defined in [samples/hapi-app/src/client/reducers/index.jsx] and `actions` defined in [samples/hapi-app/src/client/actions/index.jsx]

[samples/hapi-app]: https://github.com/electrode-io/electrode/tree/master/samples/hapi-app
[samples/hapi-app/src/client/routes.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/routes.jsx
[samples/hapi-app/src/server/routes/init-top.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/server/routes/init-top.jsx
[samples/hapi-app/src/client/app.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/app.jsx
[samples/hapi-app/src/client/routes.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/routes.jsx
[samples/hapi-app/src/client/reducers/index.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/reducers/index.jsx
[samples/hapi-app/src/client/actions/index.jsx]: https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/actions/index.jsx

**Comment by chetank628** [comment]
> Hi @chetank628,
> The application as generated by Electrode has demos for using the `init` routes. A copy of the app has been added to [samples/hapi-app](https://github.com/electrode-io/electrode/tree/master/samples/hapi-app)
> 
> [samples/hapi-app/src/client/routes.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/routes.jsx) is an example using `init` in routes. As for this example,
> 
> ```
>     ... ...
>     init: "./init-top",
>     ... ...
> ```
> the `./init-top` will reference to [samples/hapi-app/src/server/routes/init-top.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/server/routes/init-top.jsx), which imported `reducers` and defined `initialState`
> 
> At the client entry point [samples/hapi-app/src/client/app.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/app.jsx), [samples/hapi-app/src/client/routes.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/routes.jsx) was imported and a root component App was created by
> 
> ```js
>     const App = () => renderRoutes(routes);
> ```
> 
> the redux store was created with `window.__PRELOADED_STATE__` referenced to `initialState` mentioned above
> 
> ```js
>     const store = configureStore(window.__PRELOADED_STATE__);
> ```
> 
> and then the method `start` was called for
> 
> ```js
> ReactDOM.hydrate(
>     <Provider store={store}>
>       <BrowserRouter>
>         <App />
>       </BrowserRouter>
>     </Provider>,
>     jsContent
>   )
> ```
> 
> All the react components will use `reducers` defined in [samples/hapi-app/src/client/reducers/index.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/reducers/index.jsx) and `actions` defined in [samples/hapi-app/src/client/actions/index.jsx](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/actions/index.jsx)
Awesome it was so much helpful thanks just few doubts means so what i  get that it is fed with an reducer and initial state can i have async conent in initialState any e.g. so if i am having a reducer with thunk middelware which do some async call so what state will be picked up while ssr rendering how can i make the ssr wait for completion of async request any exmaple would be great help
