### ISSUE TITLE
Production node . error missing isomorphic-loader

### ISSUE THREAD

**Issue by vimcat** [electrode-io/electrode#112]
Hi all,

I'm trying get the production server started on Azure. When I run `node .` it gives me an error that it can't find isomorphic-loader -- I checked in the installed node_modules on the server and sure enough, it's not there but it does exist locally. Is this supposed to be loaded on production?

**Comment by jchip** [comment]
did you do `npm install --production` only?

**Comment by vimcat** [comment]
I did not the NODE_ENV variable was set to production

**Comment by vimcat** [comment]
Looking through the documentation, Azure's default *does* run npm install --production. So, it's an Azure issue, not necessarily an issue with electrode.
