### ISSUE TITLE
code splitting / lazy loading support

### ISSUE THREAD

**Issue by chetank628** [electrode-io/electrode#1139]
I have gone through the issue there was one pr for code-splitting long back which was reverted back have anybody managed to get work code-splitting after that with this because without code-splitting building  a large scale enterprise application is  a pain for the user experience, if Walmart uses this in production then how you manage code splitting

**Comment by Anujan** [comment]
We use `React.lazy` with dynamic imports to do code splitting. The following babel plugins need to be added
```
    "@babel/plugin-syntax-dynamic-import",
    "dynamic-import-webpack",
```

**Comment by chetank628** [comment]
> We use `React.lazy` with dynamic imports to do code splitting. The following babel plugins need to be added
> 
> ```
>     "@babel/plugin-syntax-dynamic-import",
>     "dynamic-import-webpack",
> ```
I have already tried that but ssr is not working ,only client side loading happens that too when hmr picksup, can you give me any working code snippet that would be helpful

**Comment by 1846689910** [comment]
Hi @chetank628 , https://reactjs.org/docs/code-splitting.html#reactlazy
react `lazy` and `Suspense` is not yet available for server-side rendering. Please use `@loadable/component`.
by installing
```bash
fyn a @babel/plugin-syntax-dynamic-import @loadable/component react-notify-toast
```
add plugin to your `src/client/.babelrc.js`:
```js
module.exports = {
  extends: "electrode-archetype-react-app-dev/config/babel/babelrc-client.js",
  plugins: [
    "@babel/plugin-syntax-dynamic-import"
  ]
};
```
Then you can use `@loadable/component` to do dynamic import. Please refer [this](https://github.com/electrode-io/electrode/blob/master/samples/hapi-app/src/client/components/demo-dynamic-import.jsx) as an example

**Comment by brandonburkett** [comment]
@1846689910 Thanks for the example, very helpful.  Does it support SSR?  Loading is working create for me on CSR, but I always see my fallback SSR.

**Comment by brandonburkett** [comment]
@1846689910 Thank you! This was very helpful. Does loadable work with SSR with electrode?  When I run the demo via ignite, SSR shows `<strong>Dynamic Imported Component is loading ...</strong>`.  It is working great for me on CSR.

Thanks!

**Comment by 1846689910** [comment]
Hi @brandonburkett Thank you. It is actually working now in only CSR, since only client-side changed. I will look into it

**Comment by Bryze** [comment]
@1846689910 hi, it seems the loadable feature has been shipped in [https://github.com/electrode-io/electrode/pull/1240/files](url)

But there seems to be no documentation available regarding the usage. 

Would want to give this feature a try!
