### ISSUE TITLE
Is there a HMR mode / live-reload for the component archetype?

### ISSUE THREAD

**Issue by bradbarrow** [electrode-io/electrode#115]
I am trying to create my first component using the `yo electrode-component` generator.

I can run `gulp demo` and then visit `localhost:4000` to see it. 

The generator says "with... live-reload" - but I can't seem to get any live reload behaviour.

Making a change in `src/components/MyComponent.jsx` for example, causes no refresh in the browser. A manual refresh shows the change.

Furthermore, reading the archetype gulpfile there's a couple of relevant looking tasks that are undocumented including `gulp hot`

I gave that a go and it appears to spin up a webpack dev server but since the `demo.hot.js` webpack config enters at the `demo/demo.jsx` file...nothing is actually `ReactDOM.render`'d as it is in the dev config (where we include `demo-server/app.js`

So my questions are:

- Is hot reloading supposed to be available? If so...is it broken? If not... can it be documented?
- Is `gulp demo` supposed to have live reloading? If so, any idea why mine doesn't work?

**Comment by darkbls** [comment]
Do try and run `gulp hot`, it should refresh the page, and restart the server.

Regarding HMR, it is being discussed here as well:
https://github.com/electrode-io/electrode/issues/37

**Comment by bradbarrow** [comment]
@darkbls I have tried it, and it doesn't work as expected.

> *Note:* I am referring to the `electrode-archetype-react-component` repo

*Behaviour when running `gulp hot`

It doesn't seem to start the application itself, the page on `localhost:4000` is blank. The console shows that HMR is connected and the webpack dev server itself responds. 

From what I can tell, the issue is in the `webpack.config.demo.hot.js` file. The entry is changed to point to `demo/demo.jsx` meaning that the bundle that is delivered over HMR doesn't actually contain the code that calls `ReactDOM.render`

Therefore, the page stays blank.

https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-component/config/webpack/webpack.config.demo.hot.js#L21

**Comment by animesh10** [comment]
@bradbarrow : when the generator says `live-reload` we mean editing the actual code on the console displayed at `localhost:4000` when `gulp demo` is run.

`gulp hot` task is available since it is inherited from the archetype. 

<img width="1162" alt="screen shot 2017-01-25 at 4 09 45 pm" src="https://cloud.githubusercontent.com/assets/5844098/22315046/4260936c-e319-11e6-9e44-8d28902b48cf.png">
In the above screenshot, I am editing the component code in the browser to view the results below the console.
Hope that helps.

**Comment by jchip** [comment]
the latest generator now creates a demo-app for the components.  it uses the actual app archetype.  so features like hmr is now possible when developing components.
