### ISSUE TITLE
.spec files in server are getting added to production build

### ISSUE THREAD

**Issue by ajbowler** [electrode-io/electrode#1151]
## Type of issue
Bug

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
Windows 10 64-bit
* *Node version:* `x.x.x` (run `node --version` in your terminal)
8.11.4
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
5.6.0
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)
2.0.5

## Expected behavior

Running `clap build` doesn't add spec files to `lib/`

## Current behavior

Running `clap build` adds .spec files under `src/server` to `lib/`

## Steps to reproduce the behavior
Write some unit tests (we're using Jest) in `src/server` then run `clap build`.

For reference, here's our `archetype/config/index.js`:

```
module.exports = {
  options: {
    karma: false,
    sass: true
  },
  jest: {
    collectCoverage: true,
    modulePathIgnorePatterns: ["<rootDir>/lib"],
    testURL: "http://localhost/",
    setupTestFrameworkScriptFile: "<rootDir>/node_modules/jest-enzyme/lib/index.js",
    setupFiles: ["<rootDir>/src/setup-tests.js"],
    moduleNameMapper: {
      "\\.(css|sass|scss)$": "identity-obj-proxy"
    },
    snapshotSerializers: ["enzyme-to-json/serializer"],
    testPathIgnorePatterns: ["<rootDir>/archetype/", "/node_modules/"]
  },
  webpack: {
    cssModuleSupport: true
  }
};
```

**Comment by ajbowler** [comment]
https://github.com/electrode-io/electrode/pull/997 appears to be related, we're excluding test files detected in `client/` but we're not doing the same for `server`.

**Comment by 1846689910** [comment]
Hi @ajbowler , Thank you for posting. The issue has been fixed with https://github.com/electrode-io/electrode/pull/1192.
