### ISSUE TITLE
Where should i place my api call?

### ISSUE THREAD

**Issue by thiagoneves** [electrode-io/electrode#1154]
Hey guys,

Where should i place my API calls in a SSR project using Electrode.io? 

Thanks!

**Comment by 1846689910** [comment]
Hi @thiagoneves ,

if you generate a app using `Hapi` server, you need to register a plugin.

you can create `src/server/plugins/my-api.js`:

```js
const plugin = {
  pkg: {
    name: "MyApi"
  },
  register: server =>
    server.route([
      {
        method: "GET",
        path: "/my-api1",
        handler: (request, h) => h.response("this is my-api1").code(200)
      },
      {
        method: "GET",
        path: "/my-api2",
        handler: (request, h) => h.response("this is my-api2").code(200)
      }
    ])
};
module.exports = plugin;
```

Then, in `config/default.js`, add the above plugin to the plugins array in `module.exports = {..., plugins:[...], ...}`:

```js
module.exports = {
  // ...
  "server/plugins/my-api": {
    module: "./{{env.APP_SRC_DIR}}/server/plugins/my-api"
  }
  // ...
};
```
Then you could start the app with `clap dev` and visit your api at http://localhost:3000/my-api1

As for `Express` app, it will be much easier to manipulate `src/server/views/index-view.jsx`, use `async` function and add a `req.path` check:

```js
module.exports = async req => {
  if (!routesEngine) {
    routesEngine = new ReduxRouterEngine({ routes });
  }
  if (req.path === "/my-api1") {
    const { res } = req;
    res.set("Content-Type", "application/json");
    return JSON.stringify({ foo: 123, bar: 2 });
  }
  return routesEngine.render(req);
};
```
