### ISSUE TITLE
Enable Dynamic caching in electrode?

### ISSUE THREAD

**Issue by Bryze** [electrode-io/electrode#1155]
I have a page which has a full dynamic view. The problem is whenever I do, cache:url-of-my-website,
it only shows me the static versions of the website for example header and footer.

Any idea how to enable them so that I can have the dynamic data included in the cached version of the website as well?

**Comment by jchip** [comment]
This doesn't sound like something that's in Electrode.  What is caching your pages?

**Comment by Bryze** [comment]
@jchip To give you more insight - 
When I view the page source after the page fully loads with all the api calls and data, I am only able to view the content that is static for example, the hyper links, headings, footer links etc.

I have created a custom token handler which checks the context object and populates the custom tokens present in the index.html. So, whenever, I console.log(context.user.content), only the data that is static such as hyperlinks, headings, footer links are logged.

I guess this is the problem but I am not able to wrap my head around as to why electrode doesn't recognise the content being rendered dynamically.

Token-Handler.js file
```import Helmet from 'react-helmet';

const emptyTitleRegex = /<title[^>]*><\/title>/;

module.exports = function setup(options) {
  // console.log({ options });
  return {
    INITIALIZE: context => {
      context.user.helmet = Helmet.renderStatic();
    },
    PAGE_TITLE: context => {
      const helmet = context.user.helmet;
      const helmetTitleScript = helmet.title.toString();
      const helmetTitleEmpty = helmetTitleScript.match(emptyTitleRegex);

      return helmetTitleEmpty ? `<title>${options.routeOptions.pageTitle}</title>` : helmetTitleScript;
    },
    REACT_HELMET_SCRIPTS: context => {
      const scriptsFromHelmet = ["link", "style", "script", "noscript"]
        .map(tagName => context.user.helmet[tagName].toString())
        .join("");
      return `<!--scripts from helmet-->${scriptsFromHelmet}`;
    },
    META_TAGS: context => {
      console.log(context,'123') //this is where I am checking
      return context.user.helmet.meta.toString();
    }
  };
};
```

default.js file

```module.exports = {
  port: portFromEnv() || "3000",
  webapp: {
    module: "electrode-react-webapp/lib/express",
    options: {
      prodBundleBase: '/buy-used-car/js/',
      insertTokenIds: false,
      htmlFile: "./{{env.APP_SRC_DIR}}/client/index.html",
      paths: {
        "*": {
          content: {
            module: "./{{env.APP_SRC_DIR}}/server/views/index-view"
          },
        }
      },
      serverSideRendering: true,
      tokenHandler: "./{{env.APP_SRC_DIR}}/server/token-handler"
    }
  }
};
```

To answer your question - 
I'm checking my cache on `cache:https://urlofmnywebsite.com` which returns only the static content.

Does this clear out things? @jchip

**Comment by Bryze** [comment]
@jchip Two more questions - 
Does the token-handler.js file if specified, extend the original token-handler file or replace it?
Also, does electrode outputs dynamically rendered data (.i.e. views rendered after receiving data from the API) in the page source?

**Comment by Bryze** [comment]
Apparently, it wasn't an issue of caching
