### ISSUE TITLE
How to add .LESS support?

### ISSUE THREAD

**Issue by EternallLight** [electrode-io/electrode#1170]
Hello,

I would like to use [Ant Design](https://ant.design/docs/react/introduce) components within an Electrode app. Ant Design uses Less, and in order to change default colors, I'm going to need to be able to compile .less files with my own Less variables.

I added less-loader and less to my project's dependencies and created <path-to-project>/archetype/config/webpack/webpack.config.dev.js and <path-to-project>/archetype/config/webpack/webpack.config.js files that export the following:

```
const config = {
  module: {
    rules: [{
      test: /\.less$/,
      use: [{
        loader: 'less-loader', // compiles Less to CSS
        options: {
          modifyVars: {
            'primary-color': '#1DA57A',
            'link-color': '#1DA57A',
            'border-radius-base': '2px',
          },
          javascriptEnabled: true,
        },
      }]
    }]
  }
};

module.exports = config;
```

This gets included in the final config, but in the final webpack config dump in archtype-debug.log I can see the following:

```
{
        "test": {},
        "use": [
          {
            "loader": "less-loader",
            "options": {
              "modifyVars": {
                "primary-color": "#1DA57A",
                "link-color": "#1DA57A",
                "border-radius-base": "2px"
              },
              "javascriptEnabled": true
            }
          }
        ]
      }
```

When I run `clap dev`, I see in the browser the following error:

```
ERROR in /<path-to-project>node_modules/antd/dist/antd.less 1:9
Module parse failed: Unexpected token (1:9)
You may need an appropriate loader to handle this file type.`
<contents of the .less file>
```

Unfortunately, I could not find a way to solve this, so I had to create this issue. What should I correct to be able to import and compile .less files? Could this be done or is less totally unsupported?

Thanks,
Andrey.

**Comment by 1846689910** [comment]
Hi @EternallLight ,
you could try to modify your `archetype/config/webpack/webpack.config.dev.js` and `archetype/config/webpack/webpack.config.js` as 
```js
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const { BABEL_ENV, NODE_ENV } = process.env;
const isProduction = (BABEL_ENV || NODE_ENV) === "production";
const Path = require("path");
const config = {
  module: {
    rules: [
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            {
              loader: "css-loader",
              options: {
                context: Path.resolve("src"),
                modules: true,
                localIdentName: `${isProduction ? "" : "[name]__[local]___"}[hash:base64:5]`
              }
            },
            {
              loader: "less-loader",
              options: {
                modifyVars: {
                  "primary-color": "#1DA57A",
                  "link-color": "#1DA57A",
                  "border-radius-base": "2px"
                },
                javascriptEnabled: true
              }
            }
          ],
          publicPath: ""
        })
      }
    ]
  }
};
module.exports = config;
```
and modify your `src/client/.babelrc.js` 
```js
const { BABEL_ENV, NODE_ENV } = process.env;
const isProduction = (BABEL_ENV || NODE_ENV) === "production";
module.exports = {
  extends: "electrode-archetype-react-app-dev/config/babel/babelrc-client.js",
  plugins: [
    [
      "babel-plugin-react-css-modules",
      {
        context: "./src",
        generateScopedName: `${isProduction ? "" : "[name]__[local]___"}[hash:base64:5]`,
        filetypes: {
          ".less": {
            syntax: "postcss-less"
          }
        }
      }
    ]
  ]
};
```

**Comment by 1846689910** [comment]
Hi @EternallLight ,
LESS support have been made via https://github.com/electrode-io/electrode/pull/1181
Please use the latest electrode-io, and set environment variable `CSS_MODULE_SUPPORT = true`, you could do this is `xclap.js`. Then you could import `*.less` file in your component

**Comment by EternallLight** [comment]
Hi @1846689910,

I will try the suggested options and let you know if it worked. Thank you for your help!

**Comment by EternallLight** [comment]
@1846689910, could you please push these changes to npm? I don't know how to update electrode-archetype-react-app-dev specifically with the "mono-repo" structure.

**Comment by 1846689910** [comment]
Hi @EternallLight ,
The changes have been published. could you please update your dependency with
```bash
fyn a electrode-archetype-react-app-dev@latest electrode-archetype-react-app@latest
```
Then, create `archetype/config/index.js`:
```js
module.exports = {
  webpack: {
    cssModuleSupport: true
  }
};
```
Then you are good to put `*.less` in `src/client/styles` and import to your component

**Comment by EternallLight** [comment]
@1846689910,
