### ISSUE TITLE
Electrode SSR doesn't re-render

### ISSUE THREAD

**Issue by crup** [electrode-io/electrode#1177]
I started using electrode but was faced with a fundamental problem. 
What I did? 
Generated an app - `ignite generate-app`. 

I call an API then I set the `loaded` state to true and as expected I get `<div>Loaded</div>`. What I observed was the same behaviour wasn't replicated in the page source .i.e. the page source still displayed the initial state that is `<div>Not Loaded</div>`.

```js
class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loaded: false
    }
  }

  componentDidMount() {
    fetch('https://some-api-call').then(resp => {
      return resp.json();
    }).then((result) => {
      const { data } = result;
      this.setState({
        loaded: true
      })
    })
  }

  render() {
    return (
      <div styleName={"custom.container"}>
        { 
          this.state.loaded ? <div>Loaded</div> : <div>No Loaded</div>
        }
      </div>
    );
  }
}
```

Below is the page source

```html
<!-- INITIALIZE -->
<!-- $~INITIALIZE~$ -->
<!DOCTYPE html>

<html lang="en">

<head><!-- HEAD_INITIALIZE removed due to its handler set to null -->
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- META_TAGS -->
<!-- $~META_TAGS~$ -->
<!-- PAGE_TITLE -->
<title>test-elec</title><!-- $~PAGE_TITLE~$ -->
<!-- CRITICAL_CSS -->
<!-- $~CRITICAL_CSS~$ -->
<!-- WEBAPP_HEADER_BUNDLES -->
<link rel="stylesheet" href="http://127.0.0.1:3000/js/main.style.css" /><!-- $~WEBAPP_HEADER_BUNDLES~$ -->
<!-- WEBAPP_DLL_BUNDLES -->
<!-- $~WEBAPP_DLL_BUNDLES~$ -->
</head><!-- HEAD_CLOSED removed due to its handler set to null -->
<body>
  <div class="js-content"><!-- SSR_CONTENT -->
<div><div class="custom__container___1G9dc"><div>Not Loaded</div></div></div><!-- $~SSR_CONTENT~$ -->
</div><!-- AFTER_SSR_CONTENT removed due to its handler set to null -->
<!-- PREFETCH_BUNDLES -->
<script>window.__PRELOADED_STATE__ = {"checkBox":{"checked":false},"number":{"value":999},"username":{"value":""},"textarea":{"value":""},"selectedOption":{"value":"0-13"}};</script><!-- $~PREFETCH_BUNDLES~$ -->
<!-- WEBAPP_BODY_BUNDLES -->
<script src="http://127.0.0.1:3000/js/main.bundle.dev.js"></script><!-- $~WEBAPP_BODY_BUNDLES~$ -->
<script>
    if (window.webappStart) webappStart();
  </script>
  <noscript>
    <h4>JavaScript is Disabled</h4>
    <p>Sorry, this webpage requires JavaScript to function correctly.</p>
    <p>Please enable JavaScript in your browser and reload the page.</p>
  </noscript>
</body><!-- BODY_CLOSED removed due to its handler set to null -->
</html><!-- HTML_CLOSED removed due to its handler set to null -->
```

Is there any workaround to get the re-rendered dom in page source?

**Comment by 1846689910** [comment]
Hi @crup ,
this is not how React render and ssr works. React is using virtual dom to render all your components within a statically designated element. all your state changes and component operation and corresponding response is all handled by react component life cycle and its render method. your page source is not changing when your app state changes. 
The source code you are seeing is from SSR, which will send plain initial HTML to user while other resources are still in fetch. This is for improving the user performance.
When you modify components within `src/client/` and revisit the page, you can see the plain page was changed

**Comment by crup** [comment]
@1846689910 Can you check my repo https://github.com/crup/electrode-ssr.git

I've created a file `src/server/routes/home.jsx`, which I configured with `init` parameter in routes configuration and I had to export a function there from which electrode expects a promise with some state in resolve. 

I can also change component later, see an action dispatched in setTimeout after the component is loaded. 

With that integration, I am able to set my content as initial state for components. 

Now I need to confirm, if I am going in the right direction, as I noticed it's fairly slower than the componentDidMount based implementations. 

Maybe I need to enable ssr caching for better performance.

**Comment by 1846689910** [comment]
Hi @crup ,

The electrode app use redux to manage state, so stateless component should be passed in `connect` function. 

If you wants to do some initialization before the app starts, you could use `async/await` in `server/routes`.
For example, you wants to initialize the whole app and `Home` component.

in `src\client\routes.jsx`:
```js
const routes = [
  {
    path: "/",
    component: withRouter(Root),
    init: "./init-top",
    routes: [
      {
        path: "/",
        exact: true,
        component: Home,
        init: "./init-home"
      },
      {
        path: "/demo1",
        exact: true,
        component: Demo1
      },
      {
        path: "/demo2",
        exact: true,
        component: Demo2
      }
    ]
  }
];

export { routes };
```

**Note:**

+ the `init` property refer to a node module that will do init for this component, the default path if you use `.` as beginning of the path will be `src/server/routes`, so if all your init functions are in `src/server/routes`, the path should be `./init-X`


Then, in `src/server/routes/init-top.jsx`, you could have some async calls to fetch resources then set the initialState:
```js
import reducer from "../../client/reducers";
const initNumber = async () => {
  const value = await new Promise(resolve => setTimeout(() => resolve(123), 2000));
  return { value };
};
export default async function initTop() {
  return {
    reducer,
    initialState: {
      checkBox: { checked: false },
      number: await initNumber(),
      username: { value: "" },
      textarea: { value: "" },
      selectedOption: { value: "0-13" }
    }
  };
}
```
and it is the same with `src\server\routes\init-home.jsx`
```js
import reducer from "../../client/reducers";
const initUsername = async () => {
  const value = await new Promise(resolve => setTimeout(() => resolve("alex"), 2000));
  return { value };
};
export default async () => ({
  reducer,
  initialState: {
    username: await initUsername()
  }
});
```

The above is for initialize the app or component. If you load the component and do state change in component life cycle method, the initial html template will not change. It is slower than the `componentDidMount` is because it needs to initialize the state and ensure the data is ready then render. It depends how you want your app initialized. I would recommended to put simple init data in `initialState` and fetch resources in component

**Comment by crup** [comment]
@1846689910 Thank you so much for confirming this. It took me a while to dig into the samples directory and find these examples.
