### ISSUE TITLE
"What's Inside" documentation incorrect

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode#118]
The [What's Inside page of the Electrode documentation](http://www.electrode.io/docs/whats_inside.html) incorrectly describes the old plugin layout (`plugins/webapp/*`) which does not exist anymore.

Perhaps note instead that the base HTML file is in [`electrode-react-webapp/lib/index.html`](
https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/index.html) and that it can be overrode using the `htmlFile` option in the `electrode-react-webapp` config.

**Comment by jakeki** [comment]
There are also similar issues in Intermediate parts all over , see for example [([http://www.electrode.io/docs/build_server_plugin.html))]

`server
    ├── index.js
    ├── plugins
    │   ├── friends
    │   │   └── index.js
    │   └── webapp
    │       ├── index.html
    │       └── index.js
    └── views
        └── index-view.jsx`

**Comment by donsalari** [comment]
https://github.com/electrode-io/electrode-io.github.io/pull/385
