### ISSUE TITLE
Include a <noscript> in `index.htm` for graceful fail

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode#119]
If a user has JS disabled, they should see an error message—not a blank screen.

**Comment by animesh10** [comment]
Closing since PR is merged.

**Comment by citelao** [comment]
I'm not sure this should be closed so quickly; since we have server-side rendering, a fully isomorphic webapp will only be less nice, rather than non-functional as the `<noscript>` in the pull request implies.

This might be something that users override by using their own template; maybe we can document that better?
