### ISSUE TITLE
clap dev fails with the error Cannot find the module xclap at CWD

### ISSUE THREAD

**Issue by arunabhdas** [electrode-io/electrode#1235]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `Mac OS Mojave 10.14.3`
* *Node version:* `8.9.1` (run `node --version` in your terminal)
* *npm version:* `6.9.0` (run `npm --version` in your terminal)
* *Version of yo :* `2.0.6` (run `yo --version` in your terminal)

## Current behavior

Running 

$ clap dev

fails with the error 
```
Cannot find the module xclap at CWD 
Please install it with 'npm install xclap'
```

## Steps to reproduce the behavior
Perform the following steps 

$ ignite 
Select option 2
[2] ♡ Generate an Electrode application
Select myapp as the name of the app
$ cd myapp
$ clap dev

## Command line output

```
Cannot find the module xclap at CWD 
Please install it with 'npm install xclap'
```

**Comment by jchip** [comment]
you need to run `npm install` after `cd myapp`
