### ISSUE TITLE
Electrode keeps requesting sw.js

### ISSUE THREAD

**Issue by Bryze** [electrode-io/electrode#1250]
Been noticing this behavior for some time now,

Whenever the app executes, electrode keeps requesting `sw.js` in the background even when pwa isn't enabled, due to which sometimes unhandled exceptions in our application creep up.

The part which seems similar that each error trace has the same start,
 `at process._tickCallback (internal/process/next_tick.js:68:7)` 
and in the end, the requesting resource is for example `path-to-the-page/sw.js`

Any specific reason behind this behavior?

**Comment by jchip** [comment]
Electrode app only enables `sw.js` if it was generated with PWA enabled.

However, once the browser loaded a site that's PWA enabled, it will remember it, and always request for the `sw.js` from then on.

To unregister `sw.js` for a site, open `dev tools` => `Application` => `Service Workers (left side menu)` => `Service workers from other domains`, find the domain, and click on `Unregister`.

**Comment by Bryze** [comment]
So, in principle, if once we have enabled pwa while generating the basic boilerplate. There is no going back to unregister thw sw.js programmatically?

**Comment by jchip** [comment]
You should be able to unregister with https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister
