### ISSUE TITLE
MiniCssExtractPlugin css/sass image prefix bug

### ISSUE THREAD

**Issue by brandonburkett** [electrode-io/electrode#1255]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `macOS 10.14.4`
* *Node version:* `12.3.1` 
* *npm version:* `6.9.0`

## Expected behavior
Images included via css and sass previously worked with ExtractTextPlugin, but with the switch to MiniCssExtractPlugin, the seem to be prefixed incorrectly and missing `/js/`

## Current behavior
CSS / SASS image includes to be prefixed by`/js/`

## Steps to reproduce the behavior
* spin up electrode app via ignite
* add the following to custom.css with a test image
```
.test {
  background-image: url("./test.jpg");
  background-color: #cccccc;
}
```

* add the folowing to home.jsx `<div styleName={"custom.container custom.test"}>`
* get a 500 error for image
** actual (broken): http://127.0.0.1:2992/fd2b67abf0e177d206a4e6f45a5b8eca.jpg
** what it should be (works): http://127.0.0.1:2992/js/fd2b67abf0e177d206a4e6f45a5b8eca.jpg

**Comment by 1846689910** [comment]
Thanks for posting issue, this was resolved by https://github.com/electrode-io/electrode/pull/1261

**Comment by brandonburkett** [comment]
No prob at all, `MiniCssExtractPlugin` supports hot reloading now!  Would love it was added, then I could drop my custom extract styles config.  EX:

```
if (archetype.options.sass) {
    rules.push({
      _name: `extract${cssModuleSupport ? '-css' : ''}-scss`,
      test: /\.(scss|sass)$/,

      /* CUSTOM - live reload on dev */
      use: [
        {
          loader: MiniCssExtractPlugin.loader, options: {
            publicPath: '/js/',
            // only enable hot in development
            hmr: process.env.NODE_ENV === 'development',
            // if hmr does not work, this is a forceful method.
            reloadAll: true,
          },
        },
        ...(cssModuleSupport
          ? [cssModuleQuery, postcssQuery, sassQuery]
          : [cssQuery, postcssQuery, sassQuery]),
      ],
    });
  }
```
