### ISSUE TITLE
Ignite generate-app freezing

### ISSUE THREAD

**Issue by MichaelBrazeau** [electrode-io/electrode#1286]
## Type of issue
ignite generate-app failing to generate an app, freezes when on prompt: "? GitHub username or organization".

## My environment

MacOs mojave: 10.14.5
* *Node version:* `10.16.0` (run `node --version` in your terminal)
* *npm version:* `6.9.0` (run `npm --version` in your terminal)
* *Version of yo :* `2.0.6` (run `yo --version` in your terminal)

**Comment by 1846689910** [comment]
Could you please reinstall the `electrode-ignite` and try the `ignite` command again
