### ISSUE TITLE
When I created the electrode app, clap dev, and then changed the home. JSX code, there was no hot update, the error was reported.

### ISSUE THREAD

**Issue by fengqinxingtao** [electrode-io/electrode#1292]
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output
ignite generate-app
 clap dev
 changed some code
ctrl + s
```
Paste your error output over here
```
[wds] webpack bundle is now INVALID
[wds] webpack bundle is now VALID
error: uncaughtException: no such file or directory
{ date: 'Thu Jul 04 2019 13:24:22 GMT+0800 (GMT+08:00)',
  process:
   { pid: 15896,
     uid: null,
     gid: null,
     cwd: 'D:\\web\\serverSideRender\\lucky-cat',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v11.13.0',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\dev-server.js' ],
     memoryUsage:
      { rss: 211234816,
        heapTotal: 172335104,
        heapUsed: 133883504,
        external: 3541514 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 14974 },
  trace:
   [ { column: 10,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\memory-fs\\lib\\MemoryFileSystem.js',
       function: 'MemoryFileSystem.readFileSync',
       line: 114,
       method: 'readFileSync',
       native: false },
     { column: 35,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js',
       function: 'transferMemFsFiles',
       line: 199,
       method: null,
       native: false },
     { column: 27,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js',
       function: 'waitIsoLock',
       line: 274,
       method: null,
       native: false },
     { column: 16,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js',
       function: 'waitIsoLock',
       line: 181,
       method: null,
       native: false },
     { column: 9,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js',
       function: 'defaultReporter',
       line: 274,
       method: null,
       native: false },
     { column: 44,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js',
       function: 'Object.webpackDevOptions.reporter',
       line: 145,
       method: 'reporter',
       native: false },
     { column: 23,
       file:
        'D:\\web\\serverSideRender\\lucky-cat\\node_modules\\webpack-dev-middleware\\lib\\context.js',
       function: 'process.nextTick',
       line: 42,
       method: 'nextTick',
       native: false },
     { column: 9,
       file: 'internal/process/task_queues.js',
       function: 'processTicksAndRejections',
       line: 79,
       method: null,
       native: false } ],
  stack:
   [ 'Error: no such file or directory',
     '    at MemoryFileSystem.readFileSync (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\memory-fs\\lib\\MemoryFileSystem.js:114:10)',
     '    at transferMemFsFiles (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js:199:35)',
     '    at waitIsoLock (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js:274:27)',
     '    at waitIsoLock (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js:181:16)',
     '    at defaultReporter (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js:274:9)',
     '    at Object.webpackDevOptions.reporter (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\electrode-archetype-react-app-dev\\lib\\dev-admin\\middleware.js:145:44)',
     '    at process.nextTick (D:\\web\\serverSideRender\\lucky-cat\\node_modules\\webpack-dev-middleware\\lib\\context.js:42:23)',
     '    at processTicksAndRejections (internal/process/task_queues.js:79:9)' ] }

**Comment by 1846689910** [comment]
What is the version of your `electrode-archetype-react-app-dev`. It seems you are not using the archetype v6

**Comment by fengqinxingtao** [comment]
> 你的版本是`electrode-archetype-react-app-dev`什么？

"devDependencies": {
    "@loadable/babel-plugin": "^5.10.0",
    "@loadable/webpack-plugin": "^5.7.1",
    "electrode-archetype-react-app-dev": "^6.0.0"
  }

I am starting a new project based on the documentation of the electrode official website.

**Comment by 1846689910** [comment]
cannot reproduce the error. the HMR is enabled by default, no need to save changes.

**Comment by fengqinxingtao** [comment]
> cannot reproduce the error. the HMR is enabled by default, no need to save changes.


It’s ok to try again today. but...
Can you give me an example of using "redux-thunk"? How to perform server-side asynchronous data initialization? I want to use ‘redux-thunk, thank you
