### ISSUE TITLE
[HMR] css are not updated in hot mode

### ISSUE THREAD

**Issue by orlandodemauro** [electrode-io/electrode#135]
related to #125

**Comment by orlandodemauro** [comment]
@jchip working on this issue I found a bug in he ```css-modules-require-hook``` set up.

basically even if we set a custom ``generateScopedName``` in the server it will never work, the classes are displayed as

```
_1cnXHAlzCtH79wfQ7FYQFz
```
instead of 
```
header__container_Z56Gh
```

I fixed it locally and I need to understand how to move my changes into the elecrode-generator before do a PR. Do you think I should open a different issue?

**Comment by orlandodemauro** [comment]
@jchip here an example on how to fix the issue with the css-modules-require-hook 

https://github.com/orlandodemauro/electrode/tree/fix_css_modules_require_hook

I used this https://github.com/css-modules/css-modules-require-hook/tree/master/demo ad base to understand how to fix it in electrode.

I hope this can help

**Comment by jmcriffey** [comment]
@orlandodemauro https://github.com/electrode-samples/electrode-pwa-examples/blob/master/examples/product/server/index.js#L54 Show an example of using the cssModuleHook in `electrode-archetype-react-app/supports`. That hook basically sets the root for css module generator on the server the same as the client. That should fix the issue.

**Comment by orlandodemauro** [comment]
@jmcriffey please see my comment here https://github.com/electrode-io/electrode/pull/136#issuecomment-276616448
