### ISSUE TITLE
Plan for version 7 release

### ISSUE THREAD

**Issue by jchip** [electrode-io/electrode#1354]
# Plan for a major bump version 7 release:

## Breaking Changes

- Optional add-ons
  - All optionals default to off
  - App must add each to its `devDependencies` to enable
  - [TBD] rename all add-on packages with a npm scope ~under `@xopt` like `@xopt/karma`~, instead of `electrode-archetype-opt-karma`
  - [x] scope option 2: `@xarc/opt-karma`

- Available optional add-ons:

```
electrode-archetype-opt-critical-css
electrode-archetype-opt-eslint
electrode-archetype-opt-flow
electrode-archetype-opt-inferno
electrode-archetype-opt-jest
electrode-archetype-opt-karma
electrode-archetype-opt-less
electrode-archetype-opt-mocha
electrode-archetype-opt-phantomjs
electrode-archetype-opt-postcss
electrode-archetype-opt-pwa
electrode-archetype-opt-react
electrode-archetype-opt-sass
electrode-archetype-opt-sinon
electrode-archetype-opt-stylus
electrode-archetype-opt-typescript
```

- [x] remove `cssModuleStylusSupport` flag from extract-style.js (https://github.com/electrode-io/electrode/pull/1423)
- [x] remove `webpack-dev-server` and use internal dev server only: `WEBPACK_DEV_MIDDLEWARE=true` (https://github.com/electrode-io/electrode/pull/1431)
- [x] Enable development reverse proxy by default, set `PORT=3000` and `APP_SERVER_PORT=3100` (https://github.com/electrode-io/electrode/pull/1431)
- [x] remove `electrode-bundle-analyzer` and associated tasks (https://github.com/electrode-io/electrode/pull/1420)
- [x] remove `electrode-webpack-reporter` (https://github.com/electrode-io/electrode/pull/1425)
- [x] remove `nodemon` and associated tasks (https://github.com/electrode-io/electrode/pull/1424)
- [x] move enzyme dependencies into the opt archetype that uses it (karma) (https://github.com/electrode-io/electrode/pull/1415)
- [x] move chai dependencies into the opt archetype that uses it (mocha or karma?) (https://github.com/electrode-io/electrode/pull/1414)
- [x] move `react-test-renderer` into an opt archetype if applicable (https://github.com/electrode-io/electrode/pull/1417)
- [x] remove `prop-types` dep (why is it in archetype dep) (https://github.com/electrode-io/electrode/pull/1418)
- [x] move react-intl into optional archetype (https://github.com/electrode-io/electrode/pull/1419)
- [x] remove OPTIMIZE_STATS and associated tasks (https://github.com/electrode-io/electrode/pull/1421)
- [x] Implementation of [contenthash] in webpack to improve browser caching (Change webpack [hash] to [contenthash]) (https://github.com/electrode-io/electrode/pull/1373)
- [x] drop legacy app dir structure support, App mode should always be `src/lib` now and APP_SRC_DIR should be set to `src` if WEBPACK_DEV is "true" else set it to `lib` (https://github.com/electrode-io/electrode/pull/1436)
- [x] drop optimizeModulesForProduction: React hasn't need this for a while now (https://github.com/electrode-io/electrode/pull/1416)
- [x] drop support for React version < 16 (https://github.com/electrode-io/electrode/pull/1426)

**Comment by datvong-wm** [comment]
i thought some default to on?

**Comment by jchip** [comment]
> i thought some default to on?
with this new approach we can't anymore.  we depend on the app adding each one to its `devDependencies` to pull in the optional.  we need to update our generator to add some for the app generated.

**Comment by divyakarippath** [comment]
- Change webpack [hash] to [contenthash]
