### ISSUE TITLE
clap-cli : I don't think that means what you think it means

### ISSUE THREAD

**Issue by caseman72** [electrode-io/electrode#1412]
URLs:
https://github.com/electrode-io/electrode/blob/master/samples/universal-material-ui/README.md
https://github.com/electrode-io/electrode/blob/master/samples/react-jest-app/README.md

Screenshot:
![image](https://user-images.githubusercontent.com/898808/67247455-470cf480-f416-11e9-9053-99b40c6f3403.png)

Expected:
https://github.com/electrode-io/xclap/blob/master/package.json

```
npm install -g xclap
```

Actual:
https://github.com/nickwanninger/clap-cli

```
clap dev
dev
```

**Comment by jchip** [comment]
thanks.  typo. should be xclap-cli
