### ISSUE TITLE
Csrf "INVALID_JWT"

### ISSUE THREAD

**Issue by Eric013** [electrode-io/electrode#143]
Hello,

I try electrode crsf with crsf.jsx component in demo or todo-app sample, but i have same issue response 400: "INVALID_JWT" on post request:

Example request post on todo-app:
Request URL:http://localhost:3000/updateStorage
Request Method:POST
Status Code:400 Bad Request
Remote Address:127.0.1.1:3000

**Response header:**
```
HTTP/1.1 400 Bad Request
vary: origin
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: WWW-Authenticate,Server-Authorization
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 64
Date: Thu, 02 Feb 2017 07:39:51 GMT
Connection: keep-alive
```
**Request header**
```
POST /updateStorage HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 82
Pragma: no-cache
Cache-Control: no-cache
accept: application/json
Origin: http://localhost:3000
x-csrf-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaGVhZGVyIiwidXVpZCI6IjZlZGY0NDJkLTU0OTktNGM2OC04MjhjLWY5Y2E0YjBhNzVjMCIsImlhdCI6MTQ4NjAyMTE5MSwiZXhwIjoxNDg2MDIxMjUxfQ.t9Yty5-j9WLFZMjYGf_NlpknyNZqmlu1q3Jw3mUbCTM
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
content-type: application/json
Referer: http://localhost:3000/todo-app
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,fr;q=0.6,fr-FR;q=0.4,ru;q=0.2
```
**Request payload**
`{"visibilityFilter":"SHOW_ALL","todos":[{"id":0,"text":"test","completed":false}]}`

An idea?

**Comment by jchip** [comment]
that's because the change in electrode-csrf-jwt to turn off Secure flag for the csrf token cookie was not published.  It's published as v1.2.1 and this should work now.
