### ISSUE TITLE
How to handle sensitive (POST) requests isomorphically

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode#144]
I wonder if anyone has any input on this. For now, I've had to sacrifice full isomorphism since I couldn't come up with a good solution.

**Problem**

I have a `<Route>` for `/login` that handles `POST` (and initial `GET`) requests. I want to be able to submit to that route a username and password and receive my session cookie/token. This is easy enough to do purely server-side or client-side, but I want to be able to handle it isomorphically/universally.

React Router can be modified to store POST data in some sort of `state` ([react-router-form](https://github.com/insin/react-router-form) does this), but only when such a request is sent client side. When rendered on server, React Router cannot access POST data (as far as I know).

**A bad solution**

A very simple solution (that worked) involved storing POST data in a Redux store, priming the store properly on the server-side (using `createReduxStore` in `index-view.js`) and modifying react-router-form to do the same. However, that unacceptably puts sensitive information in the DOM in plaintext. 

Does anyone have any thoughts?

**Comment by citelao** [comment]
Overriding `renderToString` in the config for ReduxRouterEngine in `index-view.js` might be promising; we can inject state from `req.body` into `renderProps.location.state`

**Comment by jchip** [comment]
generally, the approach to authentication is handled before routes.  You have middleware (express) or Hapi's auth lifecycle event, that validates authentication.  It redirects to a login page if auth fails, or allow the request to go through.  I personally would not take the approach you have in regards to authentication and security.

**Comment by citelao** [comment]
I think that is smart, but how would that handle react-router client-side routing? The middleware would not be called.

**Comment by animesh10** [comment]
There are auth plugins that are fairly simple, for example: https://github.com/hapijs/hapi-auth-basic
You will not need to install a second app, unless you want to completely isolate all the authentication logic. Here is hapi's official example: https://hapijs.com/tutorials/auth

**Comment by citelao** [comment]
The problem with those plugins is that, while they *will* work server-side, they will not work with react router. For example, if there is a `<Link>` to `/securepage` on a page I can access without authentication, a user could browse to the page *client-side* and bypass authentication. Hapi auth would work if the user clicked a normal link—that would hit the server—but not if react router stepped in to do client-side navigation.

**Comment by jchip** [comment]
any kind of auth or security validation must only occur server side.  anything that happen on the client side is not secured.  you should avoid any kind of validation or authentication in your routes directly.  protect your secure routes with passport on express or Hapi's auth lifecycle on server side.

**Comment by citelao** [comment]
This suggests to me that any service with both public- and private-facing services would need two apps, or at least two production JS bundles.

Is there an easy way to do this?

**Comment by jchip** [comment]
I don't think so.  Our apps with logins and secured routes work just fine.  You should re-evaluate your setup and consider some changes to how you handle secure routes.

**Comment by citelao** [comment]
@jchip I think we're going in circles at this point; I believe I've given a concrete example of where server-side validation wouldn't work. How would I mitigate it?

**Comment by jchip** [comment]
yup, basically I am explaining how I think security should be done and what you are trying to do is not viable.  

> server-side validation wouldn't work

That's the only way.

**Comment by jchip** [comment]
A typical app with secured routes:

`Browser` `-- Default Route -->`  `Auth middleware/plugin (auth cookie valid?)`

**A** `-- Yes -->` `forward to redux default route` `-->` `retrieve authed user's secured data` `-->` `SSR default page with user's secured data` `-->` `HTML back to browser` `-->` `Client side bootstrap React with initial Redux store containing user's secured data (or retrieve from secured enpoints with AJAX)`

**B** `-- No -->` `Redirect to Login Page` `(back to browser)` `-- POST to Login endpoint with username/password --> ` `Auth middleware/plugin (username/password verified?) to A or B again`
