### ISSUE TITLE
🐞 try/catches swallow application errors during build

### ISSUE THREAD

**Issue by jshado1** [electrode-io/electrode#145]
There are a bunch of `try` `catch` blocks around `require()`s in the Electrode source that cause application errors to fail silently, hiding the invaluable errors that the underlying build-tools throw. These should be replaced with fs checks.

**Comment by jchip** [comment]
all of them are for checking optional files.  Using fs checks would have the same behavior.  Is there a specific scenario you can offer?  But thanks for raising the issue, we do need to improve logging to let user know what the build is doing with regards to this.

**Comment by jshado1** [comment]
An fs would not have the same behaviour:
```js
if (fs.fileExists(optionalFile)) {
  require(optionalFile); // optionalFile contains code that throws an error --> error thrown and execution stops as expected
} else someLogger.debug(`${optionalFile} not found`);
```
Vs
```js
try {
  require(optionalFile);
} catch (err) {}
```
Error is swallowed.
Vs
```js
try {
  require(optionalFile);
} catch (err) {
  someLogger.debug(err); // error is not swallowed, but exection does not stop
}
```

The code that includes optional webpack.config files uses a try/catch, which swallows errors thrown in them. That was a fun waste of an afternoon tracking down.

Now I have a React module that Electrode reports can't be found; yet strangely when I log `process.cwd()` and take the outputted path of the supposedly non-existant file, it does in fact exist: `cat "$1$2"`. So I suspect the module is actually throwing an error that Electrode is swallowing with another try/catch and instead reports Module Not Found.

**Comment by jshado1** [comment]
Safeguarding against an application error crashing the server is desirable for prod, but not in dev. In dev, I expect it to explode.

**Comment by jchip** [comment]
ah, yeah, thanks for pointing that out.
