### ISSUE TITLE
Cannot run gulp dev - error in running task 'dev' and 'server-dev'

### ISSUE THREAD

**Issue by chengsieuly** [electrode-io/electrode#146]
I followed the steps laid out in: [http://www.electrode.io/docs/get_started.html](http://www.electrode.io/docs/get_started.html), but when I reach the last step trying to run the developement server, I get the following error below:

<img width="1279" alt="error" src="https://cloud.githubusercontent.com/assets/10070358/22614681/698d0baa-ea3a-11e6-9de3-20948aa1f857.png">

- Windows 10
- node 7.3.0
- npm 3.10.10
- yo 1.8.5

I can't seem to figure it out. Please help.

**Comment by jchip** [comment]
😋  yeah, your home directory being named with your name and spaces really don't mix well with command line arguments passing.  Any space is treated as argument separators so it's making `nodemon` very confused.

**Comment by jchip** [comment]
try moving your dev to somewhere like `C:\electrode`.
