### ISSUE TITLE
Enable webpack-hot-middleware https

### ISSUE THREAD

**Issue by caoanhhao** [electrode-io/electrode#1481]
## Type of issue
Bug

----
## Environment
WEBPACK_DEV_HOST = 'example.com'
WEBPACK_DEV_HTTPS = true
Hapi server

## Expected behavior
webpack-hot-middleware connect through https

## Current behavior
webpack-hot-middleware connect through http

## Steps to reproduce the behavior
set environment variable
WEBPACK_DEV_HOST = 'example.com'
WEBPACK_DEV_HTTPS = true
run project with "clap dev"

## Command line output
Blocked loading mixed active content “http://example.com:2992/__webpack_hmr”

## Cause
electrode-archetype-react-app-dev/lib/dev-admin/middleware.js line 88
"Path" default is hard code.

electrode-archetype-react-app-dev/lib/dev-admin/dev-hapi17.js line 19
paramter have only "baseUrl" and have not custom option

**Comment by jchip** [comment]
local HTTPS takes a few things before it would work.

Electrode uses a HTTPS proxy for local dev now.

We haven't consolidate the docs yet, but to get local HTTPS to work, you have to create your own self signed certs and key, put the files as:

 `config/dev-proxy.crt` and `config/dev-proxy.key`

I have some docs here on creating your own self sign https://github.com/jchip/mitm-proxy#create-ssl-certs

Then run this dev command:

`PORT=443 HOST=<host-name.for-your-cert> clap dev`

and now you can see your local dev app at `https://host-name.for-your-cert`

**Comment by caoanhhao** [comment]
@jchip thank you very much.
