### ISSUE TITLE
Move samples into https://github.com/electrode-samples

### ISSUE THREAD

**Issue by thejones** [electrode-io/electrode#153]
Are there any objections to moving the samples into https://github.com/electrode-samples? I think it would be easier if everything was in the same place. Currently, 3 samples are in the main electrode repo and then there are more in the other repo. From an outsiders perspective, I would like to have a single repo for the Electrode Boilerplate. 

I really like using this and appreciate all of your hard work. 

Thanks!

**Comment by jchip** [comment]
the samples are there for running tests and CI/CD.
