### ISSUE TITLE
dev archetype bundles @types/mocha, making jest compatibility challenging 

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1533]
## Type of issue

bug

## My environment

n/a

## Expected behavior

@types/mocha to be an optional dependency, with known semver compat ranges. in this fashion, when i install @types/jest, i will not get global type collisions

## Current behavior

```
$ npm ls @types/mocha
store-services-rise-registry@0.0.1 /Users/c0d01a5/src/rise
└─┬ electrode-archetype-react-app-dev@6.5.17
  └─┬ electrode-archetype-opt-mocha@1.0.4
    └── @types/mocha@5.2.7
```

## Steps to reproduce the behavior

install archetype 6.x

## Command line output

n/a

**Comment by jcaowml** [comment]
Does a workaround like this work?
https://stackoverflow.com/questions/56181799/how-to-use-mocha-and-jest-with-typescript-without-conflicts

**Comment by cdaringe** [comment]
we could augment, but (opinion) i think that comes w/ other side-effects, such as making mocha symbols appear valid even though in fact they _are not valid_, despite suppressing the compiler error.  ultimately we don't want mocha symbols in our compile chain.  i have a successful workaround ATM by just puring the mocha types, but it violates BKMs by `rm -rf`'ing into node_modules postinstall 😬

**Comment by jchip** [comment]
if you are using jest I assume you don't need mocha.  You can turn it off, in version 6:

`archetype/config/index.js`:

```
module.exports = {
  options: {
    mocha: false
  }
};
```

and remove any `electrode-archetype-opt-mocha` from your `package.json`

**Comment by cdaringe** [comment]
Thanks for the input and ideation, however the proposed solution will not be successful. It does not work because the existence of the file inside of node_modules includes it in the compile phase by default. Consequently turning it off in a configuration file does not have impact to the typescript compiler.  Further, I cannot remove it from my package.json because it's a child dependency of the archetype. Thus, I still think the correct solution is to make it a peer dependency, and bump this package's version

**Comment by jchip** [comment]
turning off will remove it from node_modules

**Comment by cdaringe** [comment]
Thx @jchip !  Interesting.  Ok--ill give it a shot!
