### ISSUE TITLE
electrode development workflow frequently leaves zombie processes behind

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1552]
## Type of issue

bug

## My environment

os: mac, many versions
node/npm: many versions

## Expected behavior

no zombie processes

## Current behavior

- electrode processes crash periodically, or are exited manually, then
- electrode leaves PIDs running for the internal proxy, wds, or application server

## Steps to reproduce the behavior

- use electrode in dev mode
- actively develop code that causes processes to crash (non-deterministic)
- re-run electrode, observe `EADDRINUSE`

## Command line output

example:

```
[proxy] {"level":50,"time":1583866298115,"pid":43308,"hostname":"m-c02x6042jgh7","name":"redbird","code":"EADDRINUSE","errno":-48,"syscall":"listen","address":"::","port":3000,"msg":"Server Error","stack":"Error: listen EADDRINUSE: address already in use :::3000
```

**Comment by jchip** [comment]
These two released PRs should've fix the zombies
https://github.com/electrode-io/electrode/pull/1531
https://github.com/electrode-io/electrode/pull/1542

Do you still see them?  Do you have a specific steps to repo?

**Comment by cdaringe** [comment]
@jchip, it happens pretty regularly in our repo ATM.   All it takes is starting and editing.  Generally a TS compiler error from Babel triggers it somewhat reliably.  We can get a DM going and I can hook you up
