### ISSUE TITLE
electrode webpack instance not sending updated code to browser on change

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1554]
## Type of issue

bug :bug: 

## My environment

OS version/details: osx, mojave
Node version: 12
npm version: 6
Version of yo : n/a

## Expected behavior

- updated code to be sent to browser

## Current behavior

- old/cached code sent to browser

## Steps to reproduce the behavior

- clone `<internal-repository>`
- `npm start`
- slap some `debugger` statements in various files
- observer the webpack dev server exec its change detection
- reload the page, observe, after some changes, that fresh code is not shipped to the client. one must stop the processes & reload electrode to see code changes in browser

## Command line output

`npx clap dev` ... output is not n/a.

**Comment by jchip** [comment]
There was an issue with hash added to the bundles in dev mode so every compile it changes.  fixed.
