### ISSUE TITLE
electrode development process exits periodically while editing files

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1555]
## Type of issue

🐛 bug

## My environment

OS version/details: osx, mojave
Node version: 12
npm version: 6
Version of yo : n/a

## Expected behavior

- error messages streamed to logs--not process crashes--when editing files

## Current behavior

- process crashes, leaves zombie behind on port `3000`, exits back to calling shell process

## Steps to reproduce the behavior

- clone `<internal-project>`
- `npx clap dev`
- edit files! quickly?
- observe process crash.  observe zombie PID

suffers additional symptom discussed in #1552 

## Command line output

```
 Execution Failed - Errors: 
 1  cmd "node "/Users/c0d01a5/src/storks/node_modules/@xarc/app-dev/lib/dev-admin"  --exec "/Users/c0d01a5/src/storks/node_modules/@xarc/app/support/babel-run" --ext js,jsx,json,yaml,log,ts,tsx --watch config src/server -- src/server" exit code null
    at ChildProcess.<anonymous> (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:477:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by jchip** [comment]
could you please submit internal ticket with more info on this?

**Comment by jchip** [comment]
we fixed a number of issues that may be related during beta.  I would like to test it on latest if you have the internal-project.

**Comment by cdaringe** [comment]
Repro is tricky on this one too, otherwise I would have liked to send a branch. I think my version is probably too far behind now to be viable. Perhaps if you guys have tried replicating and it's not happening, we can just close it
