### ISSUE TITLE
tasks: support wds only mode

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1560]
## Type of issue

feature 💡 

## My environment

n/a

## Expected behavior

- run wds only from std clap task set

## Current behavior

- no clap task runs _just_ the wds. we do support only the app server, why not also expose the wds as an independent task

**Comment by jchip** [comment]
The dev-admin server runs the app server/wds/proxy and sets up IPC between them through node.js `process.send`.  Without these setup, the WDS is not very useful.  What's the intended use for this?

**Comment by cdaringe** [comment]
i didn't leave sufficient breadcrumbs here. we wanted this for a solid reason, but clearly i did a poor job recording it. will re-open if it returns to mind
