### ISSUE TITLE
dev-admin: pressing K does not kill my application server

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1563]
## Type of issue

bug :bug:

## My environment

n/a

## Expected behavior

pressing `K` to kill my application server

## Current behavior

no-op

## Steps to reproduce the behavior

see sibling, recent tickets for setup.

- enter debug mode in app server
- press `D` again, receive message "Start your app server already in progress - press K to kill it."
- press `K`, observe nothing occur
- press `Q`, observe processes never come down

**Comment by jchip** [comment]
this was an issue that's found in an earlier version and it's fixed.

**Comment by cdaringe** [comment]
it's still active in archetype v7. is that formally unsupported by this point, are should it be patched as well?

**Comment by jchip** [comment]
hmm... we've been doing all the work in `@xarc/app` (ver8, and renamed).

I'd like help you update to `@xarc/app@8` if that's an option, rather than having to spend our limited resource to backport the fix to v7.

**Comment by cdaringe** [comment]
I'll defer to you then on whether to keep open or close!
