### ISSUE TITLE
electrode-redux-router-engine: rfc for improved ux

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1566]
## Type of issue

feature

## My environment

n/a

## Expected behavior

- more debug logging from electrode-redux-router-engine (output path, matches for path, component trees to render, etc)
- removal of `init-top` convention, promotion of `createStore` api.  these are largely redundant provisions. createReduxStore is more robust, inspectable, clear intentioned, and not stringly typed to an non-relative/non-absolute filepath
- or, minimally, improved error handling when initTop does not return a store.  atm, electrode trusts user input that all went well, even when a store is not returned

## Current behavior

- accepts bad user input from init-top, crashes later downstream in processing

**Comment by jchip** [comment]
Yes, if we want to continue support the redux router engine workflow we should improve its APIs.

We are focusing most of our effort on the subapp architecture and hope to slowly deprecate the redux router engine stuff and only support it in old apps.
