### ISSUE TITLE
Error in console following a default installation procedure of latest electrode

### ISSUE THREAD

**Issue by LuckStock** [electrode-io/electrode#1570]
* *OS version/details*: `Windows 10 x64`
* *Node version:* `12.16.1`
* *npm version:* `6.13.4`
* *Version of yo :* `3.1.1`

## Expected behavior

Following standard installation procedure, it shouldn't throw errors in the browser console after running with `clap dev`.

## Current behavior

Produces error in the developer's console and the environment is not smoothly functional.
There are two types of errors produces depending on whether I choose HapiJS, ExpressJS or KoaJS during the initialization of the electrode app.

## Steps to reproduce the behavior
`ignite` the app using all default settings, select HapiJS, ExpressJS or KoaJS to see the different errors and run `clap dev`. Go to http://localhost:3000 and check the developer's console.

## Command line output

Error number #1 generated by using ExpressJS and KoaJS during initialization of the app:
```
react-dom.development.js:88 Warning: Did not expect server HTML to contain the text node "
" in <div>.
    in div (created by Root)
    in Root (created by Context.Consumer)
    in withRouter(Root) (created by Context.Consumer)
    in Route
    in Switch
    in Unknown
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
```

Error number #2 generated by using HapiJS during initialization of the app:
```
react-dom.development.js:88 Warning: Text content did not match. Server: "Test cookie value: From_SSR_1584713894424" Client: "Test cookie value: "
    in p (created by DemoCookies)
    in div (created by DemoCookies)
    in DemoCookies (created by Home)
    in div (created by Home)
    in div (created by Home)
    in Home (created by Connect(Home))
    in Connect(Home) (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in div (created by Root)
    in Root (created by Context.Consumer)
    in withRouter(Root) (created by Context.Consumer)
    in Route
    in Switch
    in Unknown
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider```

**Comment by jchip** [comment]
this is the difference between server side rendered and client side rendered content.  some was intended in the sample.
