### ISSUE TITLE
How to override CSSSplitPlugin in archetype/config/webpack/webpack.config.js

### ISSUE THREAD

**Issue by crup** [electrode-io/electrode#1571]
## My environment

* *OS version/details*: `MacOS Mojave (10.14.6)`
* *Node version:* `v12.12.0`
* *npm version:* `6.13.0`

How can I override CSSSplitPlugin's configuration in my custom webpack configuration `archetype/config/webpack/webpack.config.js`?

I tried overriding it in webpack.config.js but no luck. 

With its default config I am getting `@import("localhost:3000/undefined")` in my prod css. 
```
new CSSSplitPlugin({
        size: 4000,
        imports: true,
        preserve: true,
        defer: true
      })
```

**Comment by crup** [comment]
It's looks like a bug in `css-split-webpack-plugin`. I tried debugging `node_modules/css-split-webpack-plugin/dist/index.js` and found out the issue in line 206.

```
var content = entry.chunks.map(function (file) {
      return `@import "${publicPath}/${file._name}";`;
}).join('\n');
```
It expects a `_name` property in name `file` but it gets `name` instead. Changing it to `return `@import "${publicPath}/${file._name}";`;` fixed the undefined path in split chunk file.

**Comment by jchip** [comment]
thanks for the report and info on the fix.  Would this be something css-split-web-plugin can fix?

**Comment by crup** [comment]
@jchip Changing `_name` to `name` in css-split-web-plugin fixed this issue but I am not sure if this breaks something else.

https://github.com/metalabdesign/css-split-webpack-plugin/blob/master/src/index.js
```
entry.chunks.forEach((file) => {
            assets[file.name] = file;
            // It uses file.name here
            chunk.files.push(file.name);
          });
          const content = entry.chunks.map((file) => {
            // But file._name here. 
            return `@import "${publicPath}/${file._name}";`;
          }).join('\n');
```
