### ISSUE TITLE
dev-panel renders incorrect text in TUI output

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1608]
# Type of issue

bug

## My environment

node 10, npm 6

## Expected behavior

un-mutated log stream

## Current behavior

overwritten/mutated log stream

## Steps to reproduce the behavior

- install electrode-x per getting started guide
- `npx clap dev`
- observe `error: | ...`, which then reads into part of a virtual banner, not an error message

## Command line output

![image](https://user-images.githubusercontent.com/1003261/79786376-358ba300-82fa-11ea-94d9-68283e7472dc.png)

**Comment by jchip** [comment]
Yup, noticed the same thing.  We have to figure out what to do about this.
