### ISSUE TITLE
dev-panel does not respect extended log mode and flickers

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1609]
## Type of issue

bug

## My environment

node 10, npm 6

## Expected behavior

- stdio to stream increased log-level on log-level keypress

## Current behavior

- dev-panel flickers

## Steps to reproduce the behavior

- install electrode-x as covered in getting-started guide
- `npx clap dev`
- press `6`
- observe

## Command line output

(tapping the `6` key every couple of seconds)

![dev-panel-flicker mov](https://user-images.githubusercontent.com/1003261/79786922-01fd4880-82fb-11ea-8758-45901ab9f096.gif)

**Comment by jchip** [comment]
it'd be nice to get a nice rendering terminal admin.  It's a lot of work though.
