### ISSUE TITLE
electrode swallowing error messaging, versus presenting it to the user

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1610]
## Type of issue

bug

## My environment

n/a

## Expected behavior

surface error messaging

## Current behavior

swallows error messaging

## Steps to reproduce the behavior

- setup electrode-x app, misconfigure uiFilter JSONPath
- execute in debug mode
- listen for all exception

## Command line output

observe error:

![image](https://user-images.githubusercontent.com/1003261/79789606-56a2c280-82ff-11ea-86ba-5ccb4ce0420f.png)

but electrode yields:

```
Error: http://localhost:3100/electrode/services/ccm/refresh returned status 500
    at server.inject.then.res (/Users/c0d01a5/src/smarties/node_modules/@walmart/electrode-wml-server/lib/service-refreshers.js:44:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

this isn't the end of the world--the 500 is somewhat communicative, but the refresh route perhaps ought present more graceful messaging. additionally, we ought validate server configuration

**Comment by jchip** [comment]
could you submit this as an internal ticket please?
