### ISSUE TITLE
electrode-ui-config pulls config object which is not written by default by electrode-x to the window

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1611]
## Type of issue

bug

## My environment

n/a

## Expected behavior

crash on missing configuration, **or**, improved resiliency on writing expected config onto browser window 

## Current behavior

in electrode-x, using the defacto install process, `window._config` is not written: https://github.com/electrode-io/electrode/blob/fbdf021d883f85dbb94dc1dcdf14d3aafc92b0cf/packages/electrode-ui-config/src/csindex.js#L5

## Steps to reproduce the behavior

- create new electrode-x app
- install electrode-ui-config
- attempt to use electrode-ui-config
- observe no classic-o electrode-ui-config, browser-side

**Comment by jchip** [comment]
we need to add the ui-config support code to `subapp-server`.
