### ISSUE TITLE
add more comprehensive debug logs for problem diagnosis

### ISSUE THREAD

**Issue by jchip** [electrode-io/electrode#164]
Add a better logger so user can enable debug logs to output to a file for problem diagnosis.

  - contain all configs
  - paths use
  - features/options enabled/disabled

/cc @jshado1 
/ref https://github.com/electrode-io/electrode/pull/148#issuecomment-277474874

**Comment by jshado1** [comment]
Sweet! Need anything from me?

**Comment by jchip** [comment]
probing for preference of logger.  I am inclined toward https://github.com/trentm/node-bunyan since we use that internally also.

**Comment by citelao** [comment]
I'm a fan of [Winston](https://github.com/winstonjs/winston), but I think either option works well.

**Comment by didi0613** [comment]
@jshado1 @citelao @jchip 
I've created a PR using `bunyan` for adding more comprehensive debug logs for problem diagnosis:
https://github.com/electrode-io/electrode/pull/218/files

Currently it is specifically for error message in add-dll-references.js and all the errors will output to file `buyan-logs-json`

Here is the sample error logs:
Intentionally commented out line:
https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/webpack/add-dll-references.js#L12

And output content:
![screen shot 2017-02-28 at 5 30 47 pm](https://cloud.githubusercontent.com/assets/10135897/23442155/b2e9509c-fddb-11e6-8c43-df8451d689d6.png)

Please let me know if i need to make any changes or needs to adding more info in the log.
Thanks.

**Comment by jshado1** [comment]
I vote for Winston because it has integration with loads of logging services.

**Comment by didi0613** [comment]
@jshado1 @jchip  Here is another PR for winston: https://github.com/electrode-io/electrode/pull/220/files
Demo:
![add-winston](https://cloud.githubusercontent.com/assets/10135897/23532810/6a15dfec-ff62-11e6-97fb-c31245e10276.gif)

Partial sample error log:
![screen shot 2017-03-02 at 4 07 36 pm](https://cloud.githubusercontent.com/assets/10135897/23532818/7677e816-ff62-11e6-9bc4-c26b3e7dca2b.png)

Please take a look and let me know if i need any updates.

**Comment by didi0613** [comment]
From my point of view:
*Winston*: large community support with various logging modules
*Bunyan*: easy out of box to parse logs, works well when logging complex context and objects but leaves consumption up the user.

It comes down to preference and how easy it to integrate with our whole app.

**Comment by didi0613** [comment]
@jshado1 @jchip @citelao updates:
I've added a wrapper to initialize & utilize winston inside, put all the configurations there.
please take a look at the updated pr: https://github.com/electrode-io/electrode/pull/220 and let me know if you guys still needs anything.

Sample winston.log:
`
{
"configurations": [ ... ],
"path":"/Users/s0d00px/Documents/electrode-io/samples/universal-react-node/src/client/dll.config.js",
"features":{  
   "devHostname":"localhost",
   "devPort":2992,
   "testPort":3001,
   "modulesDirectories":[ ... ],
   "enableBabelPolyfill":true
   },
"level":"error",
"message":"add-dll-references failed: exists is not defined",
"timestamp":"2017-03-06T20:20:19.682Z"
}
`

**Comment by citelao** [comment]
@jchip You mentioned in #220 the ability to choose between Winston and Bunyan; why not roll forward with that? A wrapper function would be fairly simple to write, and it could be server/client compatible (fallback to console.log or silence on client) if so desired.
