### ISSUE TITLE
Electrode 

### ISSUE THREAD

**Issue by wwaldbu** [electrode-io/electrode#166]
Currently, when I try to build a new project using hapi as my server, the generator puts in an express server and a koa server and not a hapi server implementation. Any suggestions on how to resolve this? Here is a what my scaffold looks like:

<img width="196" alt="screen shot 2017-02-13 at 10 47 46 am" src="https://cloud.githubusercontent.com/assets/16925112/22890286/e7635312-f1d9-11e6-8bd6-3baaed765d1f.png">

**Comment by animesh10** [comment]
The index.js should be using the correct electrode-server module. The koa file is an extra, this is a known issue which we will be fixing.

**Comment by wwaldbu** [comment]
But there isn't a happy-server file for me to start with? I only have express and koa.

**Comment by animesh10** [comment]
In your server/index.js, when using Hapi, you will see a reference to electrode-server, which is a node module and should be present in your node_modules after you do npm install.

**Comment by wwaldbu** [comment]
So where is my hapi server code then? For example, I have both of these files for express and koa but no file for hapi to edit:

<img width="791" alt="screen shot 2017-02-13 at 11 48 26 am" src="https://cloud.githubusercontent.com/assets/16925112/22893025/849f3e86-f1e2-11e6-8993-cdb9dc8649f3.png">
<img width="792" alt="screen shot 2017-02-13 at 11 48 44 am" src="https://cloud.githubusercontent.com/assets/16925112/22893029/86faa5a8-f1e2-11e6-8a32-18597588dce7.png">

**Comment by animesh10** [comment]
If you follow my last comment, you will be able to see a `electrode-server` in your `node_modules`. Within that you will be able to see `lib/electrode-server.js`. Here is the git link for that module : https://github.com/electrode-io/electrode-server/blob/master/lib/electrode-server.js
