### ISSUE TITLE
SplitChunksPlugin is not working

### ISSUE THREAD

**Issue by crup** [electrode-io/electrode#1667]
App doesn't work when I try to use `SplitChunksPlugin` in custom Webpack configuration. Only main bundle is included in html file.

Sample repo: https://github.com/crup/electrode-split-chunk

**To Reproduce**

1. Create `archetype/config/webpack/webpack.config.js`
2. Add following configuration:
```js
module.exports = {
    optimization: {
        splitChunks: {
          cacheGroups: {
            vendor: {
              test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
              name: "vendor",
              chunks: "all"
            }
          }
        }
    }
  };

```
3. `npm run prod-start`

**Expected behavior**
`react/react-dom`'s vendor chunk(`dist/js/2d2802a38e87d2c51a3a.vendor.js`) should have been loaded/included in html.

**Desktop (please complete the following information):**
## System:
 - OS: macOS 10.15.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 104.23 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.12.0 - /usr/local/bin/node
 - Yarn: 1.19.1 - /usr/local/bin/yarn
 - npm: 6.13.0 - /usr/local/bin/npm
## Browsers:
 - Chrome: 83.0.4103.97
 - Firefox: 76.0.1
 - Safari: 13.1

**Electrode Version**
```
├── electrode-archetype-react-app@7.0.0-beta7.0
└── electrode-redux-router-engine@3.0.0
```

**Framework Version**
```
├─┬ electrode-archetype-react-app@7.0.0-beta7.0
│ └─┬ electrode-archetype-opt-react@2.0.5
│   ├── react@16.13.1
│   └── react-dom@16.13.1
├─┬ electrode-archetype-react-app-dev@7.0.0-beta7.0
│ └─┬ electrode-archetype-opt-preact@1.0.1
│   └── preact@10.4.4
├─┬ electrode-redux-router-engine@3.0.0
│ ├── react-router@5.2.0
│ └── redux@4.0.5
└─┬ react-router-dom@5.2.0
  └── react-router@5.2.0
```

**Comment by jchip** [comment]
I don't know if we ever support this, but latest has built-in code splitting.

```
npm init @xarc/app@beta
```
