### ISSUE TITLE
Problems with ignite generate-component

### ISSUE THREAD

**Issue by Renji3** [electrode-io/electrode#1680]
**Describe the bug**
Error when using ignite to create a component

When I run `ignite generate-component` and use all the default parameter to create the component, The script runs but eventually stops at 
```
conflict archetype/config/index.js
```
asking me if i want to overrite it. Either choosing yes or no doesn't make a difference since it in both cases end up in another error later on: 

```
[15:52:26] ------Execute electrode/build-lib:copy-flow as function
Error catched: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wysiwyg-component@0.0.1 prepublish: `clap prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wysiwyg-component@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-06-23T13_52_27_009Z-debug.log

Your new Electrode component is ready!
Your component is in wysiwyg-component/packages and your demo app is wysiwyg-component/demo-app

Type 'cd wysiwyg-component/demo-app' then 'clap dev' to run the development build for the demo app.
```

The build doesn't break directly and it states that the "Component is ready".
When running clap dev in demo-app however it doesn't recognize jsx and seet the 
<div> as a syntax error.

**Desktop (please complete the following information):**
## System:
 - OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
 - Memory: 137.21 MB / 7.56 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 12.16.3 - /usr/local/bin/node
 - Yarn: 1.22.4 - ~/.npm-global/bin/yarn
 - npm: 6.14.4 - /usr/local/bin/npm
## Browsers:
 - Chrome: 83.0.4103.116
 - Firefox: 77.0.1

**Electrode Version**
I am using Ignite version `3.0.17`

**Comment by jchip** [comment]
not supported anymore
