### ISSUE TITLE
Look at your Doc web site page... result is not what you want it to be.

### ISSUE THREAD

**Issue by jerome-diver** [electrode-io/electrode#1720]
**Describe the bug**
Render the doc page of your web site is very strange and unreadable

**To Reproduce**
open Firefox browser and go to see... (i'm under archlinux, but i think there is nothing in relation with the os there)
[look your doc mage there... something is going wrong right ?](https://www.electrode.io/docs/what_is_electrode.html)

**Expected behavior**
Read the doc, have a navbar, etc...

**Comment by taocode** [comment]
## 404 Errors
I'm also seeing 404 error pages for most all documentation links, often from many places other places on the internet. It seems like the old URLs to documentation have changed but no redirect or forwarding address has been offered. Further findings:

## Where
* docs.electrode.io -> All 404 all the time, nothing useful
* www.electrode.io/docs -> 404 errors without usable links, all links on these error pages tend to produce another error page (demo by clicking jerome-diver's link).
* www.electrode.io/electrode/ -> Footer "Docs" "Community" and "More" are headings without any links.

## Makes Learning Very Difficult
I am interested in learning Electrode but all these bad links have made this difficult. Kirill Konshin summarizes [Electrode documentation as  *nightmare*](https://medium.com/disdj/solutions-for-react-app-development-f9fcaeba504#3578) in 2017, now I'd suggest they're *impossible*.

## Where's the docs?
Where can anybody go for documentation on Electrode today? Can you maybe make a useful error page for the above and/or include the links that seem to be missing?

**Comment by jchip** [comment]
yes, docs has been non-existent or maintained since 2017, no one to work on them, and gitbook broke.
latest doc is in docusaurus but nothing in there. https://www.electrode.io/electrode/
