### ISSUE TITLE
Css module not working with typescript

### ISSUE THREAD

**Issue by tpriyesh** [electrode-io/electrode#1724]
I have created electrode project, I am trying to use css module in my tsx file. In my folder I have demo.tsx file along that I also have styles.css file. I am using css module. When I am trying to import css in my demo.tsx file, it is breaking not working

I am using it like:

```
import * as React from "react";
import styles from "./styles.css";

export const Demo = () => {
    return <div styleName="styles.login">My login page</div>;
};
```

Also I want to use style like style.login in object literal way strongly typed way. I have tried several ways like putting style loader in archetype config project structure but it was not getting into affect. Also typescript was giving error styles.css could not be found. I solved it by putting style.d.ts file. But style loader is not working when running the app.

**Comment by jchip** [comment]
don't know why it doesn't work, but just verified in latest and it works.

```
npm init @xarc/app my-app
```

Add some info to demo's README on enabling CSS module https://github.com/electrode-io/electrode/blob/8d617439d238ac81bf9aea835b14026add85b21a/packages/xarc-create-app/template/README.md#styling-support
