### ISSUE TITLE
New release, or how can we dev. against HEAD?

### ISSUE THREAD

**Issue by ograycode** [electrode-io/electrode#174]
There's been several improvements over the past week or so I would like to take advantage of. However, with each package being in this repo, but separate in npm, it's unclear to me how I would change to develop against HEAD until a new version is cut.

**Comment by jchip** [comment]
I update my package.json to point to the packages in HEAD with local file paths.

**Comment by ograycode** [comment]
@jchip do you mind expanding on that? From what I understand you had this repo in a different local folder and the just pointed the the package.json entry to the local folder?
