### ISSUE TITLE
Yarn error

### ISSUE THREAD

**Issue by franciscocpg** [electrode-io/electrode#175]
I'm trying to use `yarn` on a electrode project and getting this error
```
error electrode-archetype-react-app@1.9.1: The engine "node" is incompatible with this module. Expected version "^4.4.6 || ^6.2.1".
error Found incompatible module
```
I get no error when running with `yarn --ignore-engines` flag.
Does anyone knows the reason?

**Comment by jchip** [comment]
yarn doesn't understand `"^4.4.6 || ^6.2.1"`?
