### ISSUE TITLE
Initial install doesn't validate with TypeScript

### ISSUE THREAD

**Issue by TimMensch** [electrode-io/electrode#1806]
**Describe the bug**
I used `npx @xarc/create-app xarc` to create a new `/xarc` project to try out Electrode. After running it I ran `tsc` and it showed up with several errors.

**To Reproduce**

1. `npx @xarc/create-app xarc`
2. `cd xarc`
3. `yarn`
4. `yarn dev`
5. Hit Q to quit the server.
6. `npx tsc`

Observe errors.

**Expected behavior**
I expect the initial install to have types (and package dependencies) configured such that `tsc` shows no errors.

**Desktop:**

```
## System:
 - OS: Windows 10 10.0.19041
 - CPU: (16) x64 AMD Ryzen 7 3800XT 8-Core Processor
 - Memory: 15.16 GB / 31.95 GB
## Binaries:
 - Node: 12.20.1 - C:\Devel\nodejs\node.EXE
 - Yarn: 1.22.10 - C:\Devel\nodejs\yarn.CMD
 - npm: 6.14.10 - C:\Devel\nodejs\npm.CMD
## Browsers:
 - Edge: Spartan (44.19041.423.0), Chromium (88.0.705.56)
 - Internet Explorer: 11.0.19041.1
```

Note: Problem still happens on Node 14.15.4; I re-ran the above sequence with the same result.

**Electrode Version**
Please run `npm ls subapp-react subapp-pbundle electrode-archetype-react-app @xarc/app electrode-redux-router-engine` and paste the output:

```
$ npm ls subapp-react subapp-pbundle electrode-archetype-react-app @xarc/app electrode-redux-router-engine
my-x-app@0.0.1 D:\projects\xarc
`-- @xarc/app@8.2.4
```

**Framework Version**

- Which of the following are you using? Please provide versions:
  - React
  - Preact
  - Redux
  - Redux-router

Please run `npm ls react react-dom redux react-router preact` and paste the output:

```
$ npm ls react react-dom redux react-router preact
my-x-app@0.0.1 D:\projects\xarc
+-- @xarc/react@0.1.4
| +-- react@17.0.1
| `-- react-dom@17.0.1
`-- @xarc/react-redux@0.1.3
  `-- redux@4.0.5
```

**Comment by jchip** [comment]
this is fixed in `@xarc/create-app@5`, but it's published with `beta` tag for now.  

`npm init @xarc/app@5 xarc` should do it.

**Comment by TimMensch** [comment]
Thanks for letting me know!
