### ISSUE TITLE
Which branch is used for Deploy?

### ISSUE THREAD

**Issue by woochanleee** [electrode-io/electrode#1831]
# Problem

As you can see, https://github.com/electrode-io/electrode/pull/1830

I'd like to contribute some wrong link from https://www.electrode.io/electrode/

But actually, as shown below image, Some MarkDown file doesn't exist on `master` branch. 
![image](https://user-images.githubusercontent.com/48552260/108804484-b8e3e800-75e0-11eb-907f-cdd6295bf0ef.png)

However, another branch has all MarkDown files on `next`, `v8.x.x` `etc.`. Like:
![image](https://user-images.githubusercontent.com/48552260/108804603-137d4400-75e1-11eb-94a7-29a587210063.png)

# Question

So, I'm very confused this situation. Can you tell me which branch is used for deploy?

**Comment by jchip** [comment]
the default master branch.  docs source is `/docusaurus`, and published as to `/docs` that github picks up and made available as website.

**Comment by jchip** [comment]
https://github.com/electrode-io/electrode/blob/master/CONTRIBUTING.md#updating-docs
