### ISSUE TITLE
Removing node.js 

### ISSUE THREAD

**Issue by shirishsahay** [electrode-io/electrode#1845]
I am creating a project using electrode in which I don't require the use of node.js because we are already using Java Springboot as backend. Following are my concerns:
- How should I remove node.js from electrode framework?
- How to use/integrate client-side routing using react-router-dom?

**Comment by jchip** [comment]
node.js is mainly used for server side rendering and serving the web page.

if you don't need SSR and have your own web server for serving the web assets, it's possible, but this is a use case we never considered, so we don't really have out of the box support for it.
