### ISSUE TITLE
.build directory is not built (breaks `gulp dev`)

### ISSUE THREAD

**Issue by jshado1** [electrode-io/electrode#189]
Gulp dev is trying to read a `stats.json` file from `<app>/.build/`, which doesn't exist. This is causing the app to request `main.style.css` instead of `style.<hash>.css`.

I tried manually creating that directory in case the files try to write to it before creating it (and Electrode was swallowing the error), but no luck.

That directory is also not created/written by `gulp build` or by `gulp server`.

Possibly related to #106

**Comment by jchip** [comment]
is this on the latest master, which is still on webpack 1.0?

**Comment by jshado1** [comment]
Yes
