### ISSUE TITLE
errors in yeoman-generated code

### ISSUE THREAD

**Issue by doug-wade** [electrode-io/electrode#194]
Running node 6.9.4 and npm 3.10.10 on my mac, I got a coupla errors from default configuration that comes out of the yeoman generator.

In the browser console: `Service worker registration failed:  DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').`

In the terminal: `webpack bundle is now VALID but has WARNINGS`

Doesn't seem to affect the app much, but is a little jarring.

**Comment by jchip** [comment]
this should be fixed in the latest version
