### ISSUE TITLE
unclear how to use __PRELOADED_STATE__

### ISSUE THREAD

**Issue by doug-wade** [electrode-io/electrode#195]
I see from the generated code that there is a `window.__PRELOADED_STATE__`, which is passed as the initial state:

```
window.webappStart = () => {
  const initialState = window.__PRELOADED_STATE__;
  const store = createStore(rootReducer, initialState);
  render(
    <Provider store={store}>
      <Router history={browserHistory}>{routes}</Router>
    </Provider>,
    document.querySelector(".js-content")
  );
};
```

I'd like to pass the results of a network call, the results of http://api.citybik.es/v2/networks, as the initial state to my application, but I can't see any other reference to how preloaded state gets set.  Should I be dispatching a "fetch initial state" action instead, or is there some way to set preloaded state myself?

**Comment by citelao** [comment]
Check out `src/server/index-view.js`. There's a function called `createReduxStore` which you can modify to set up the initial state of your app, on the server-side, for each request.

There's no magic way of doing things, but you can parse the `request`'s path and do whatever actions you need :)

**Comment by four-eyes-04-04** [comment]
is it really okay to use the `window` object? because it leaks on the console right?
