### ISSUE TITLE
README.md update required to match code for how Roboto font is added

### ISSUE THREAD

**Issue by Crashedmind** [electrode-io/electrode#223]
https://github.com/electrode-io/electrode/blob/master/samples/universal-material-ui/README.md 

> 3. Add material-ui's required font Roboto to server/plugins/webapp/index.html
should be 
> 3. Add material-ui's required font Roboto to client/styles/base.css

**Comment by animesh10** [comment]
PR updating the Readme: https://github.com/electrode-io/electrode/pull/280
