### ISSUE TITLE
electrode-archetype-react-component* dependencies outdated

### ISSUE THREAD

**Issue by DavidOrchard** [electrode-io/electrode#227]
The dependencies are very outdated, such as "eslint": "^1.7.0" whereas app is more update to date "eslint": "^3.9.1". Among other things, this causes incompatibilities in custom eslint rules for a component that is then included in an app.

**Comment by cross311** [comment]
#251

**Comment by cross311** [comment]
Looks like @didi0613 is moving ahead with this!  @DavidOrchard

**Comment by didi0613** [comment]
@cross311  Yes i am currently working on updating archetype component.
eslint part has been merged & currently working on upgrading webpack v1 to v2

**Comment by animesh10** [comment]
closing since https://github.com/electrode-io/electrode/pull/251 is merged.
