### ISSUE TITLE
Conditionally adding custom javascript to head

### ISSUE THREAD

**Issue by LeeFrancis** [electrode-io/electrode#230]
How do I Add my own custom JavaScript to the head at run time?
It looks like I can add my own index.html by overriding htmlFile in the config but I want to conditionally add a piece of js to the head?

**Comment by citelao** [comment]
Useful for injecting Google Analytics ID from config.

Not possible at the moment 😁

**Comment by dennisat** [comment]
Try with Helmet [see this pr](https://github.com/electrode-io/electrode/pull/299)

**Comment by LeeFrancis** [comment]
Works great!! Thanks.
