### ISSUE TITLE
Boilerplate not running in Production mode, test fails

### ISSUE THREAD

**Issue by ShotaMegre** [electrode-io/electrode#232]
Electrode boilerplate not working as from Get Started:
after running:
```
yo electrode
gulp build
```

`npm run prod` - fails.
`gulp check` - fails.

**Comment by ShotaMegre** [comment]
Any updates guys on how to fix it?

**Comment by khayong** [comment]
Here is the solution at https://github.com/electrode-io/electrode/issues/221#issuecomment-284299929

Just change according to the line 
`"prod": "echo 'Starting standalone server in PROD mode'; node ./lib/server/",`

**Comment by animesh10** [comment]
This should be fixed with the new release of the archetype.
If you are getting an error about the `isomorphic-assests` file, as a temporary fix, you can check the path of your `assets-file` in `.isomorphic-loader-config.json`. it should point to the correct location `dist/isomorphic-assets.json`.
