### ISSUE TITLE
Is there any way to optimise the server restarting on all changes?

### ISSUE THREAD

**Issue by andrewdavidcostello** [electrode-io/electrode#235]
I noticed you are using nodemon to watch for changes, however at the moment this seems to be applied to extensions meaning if you change any file it will restart the server. If I want to preview changes quickly I cannot immediately view them in the browser as I am waiting 1 minute each time to view the change?

Is there something that I am doing wrong here or is it expected for the server to restart and take one minute each time before any changes can then be viewed?

Thanks and apologies if this is the wrong place to ask.

**Comment by animesh10** [comment]
Hi, 
As you have noticed, the server watch mode will always watch for any changes to the file extensions mentioned. You can either start the server in a non-watch mode, `gulp server`. Or modify the gulp task in your local to ignore certain files/folders. 
The gulp tasks are defined in `electrode-archetype-react-app/arch-gulpfile.js`. And nodemon documentation for [ignore](https://github.com/remy/nodemon/blob/master/README.md#ignoring-files)

**Comment by codingcircus** [comment]
@animesh10 Could you maybe elaborate a little bit more, on how to extend the gulpfile? I couldn't find any code examples for this and the server-watch task especially looks like it has a lot of dependencies.
