### ISSUE TITLE
upgrade react-hot-loader to version 3.x

### ISSUE THREAD

**Issue by nzeugaa** [electrode-io/electrode#244]
I'm having this issue while using react-form(v6.x) with electrode  : 

> Cannot read property 'wrapped' of undefined

This error is caused by react-hot-loader (^1.2.8) dependency in electrode-archetype-react-app-dev. Upgrading react-hot-loader to version 3.x seems to be the solution of this problem. 

I've tried to modify electrode-archetype-react-app-dev inside node_modules but did not succeed at this point to get this error off.

Some useful links : 
[https://github.com/erikras/redux-form/issues/1262](https://github.com/erikras/redux-form/issues/1262)
[https://github.com/erikras/redux-form/issues/1655](https://github.com/erikras/redux-form/issues/1655)
[https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30](https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30)

**Comment by davidalee** [comment]
Any progress on this?

**Comment by jchip** [comment]
hot module reload has been updated
