### ISSUE TITLE
How to add Intl provider when doing SSR.

### ISSUE THREAD

**Issue by cross311** [electrode-io/electrode#250]
I cannot figure out how to get the electrode react router to add providers (IntlProvider) around the routes when running on the server side.  I can add the providers in app.jsx which works for client side, but throws an error on server side because the provider context does not exist.

I assume this has already been figured out since the generators for components use IntlProvider.

Thanks!

**Comment by cross311** [comment]
@jchip any examples?

**Comment by jmcriffey** [comment]
I am going to look into this today @cross311. I'll make sure everything works and get an example together.

**Comment by jmcriffey** [comment]
The issue boils down to trying to set up `IntlProvider` on a client-only component, like `app.jsx`. Basically, we need to make sure that `IntlProvider` is set up on a shared component, like `home.jsx`. 

A more involved solution involves moving your router and redux setup to a component that the server can interact with. That is much more complicated, as you either need to set up initial state in your server or have your app gracefully handle an empty initial state.

I've put together a quick example, and here are some files that might be of interest:

- https://github.com/jmcriffey/electrode-react-intl-example/blob/master/src/client/components/home.jsx
- https://github.com/jmcriffey/electrode-react-intl-example/blob/master/src/client/components/welcome.jsx
- https://github.com/jmcriffey/electrode-react-intl-example/blob/master/src/client/lang/en.json

**Comment by cross311** [comment]
So what you are actually recommending is create an HOC that has the wrappers that are needed for URL or route registered components.

```js
import React, {PropTypes} from "react";

import "intl";
import "intl/locale-data/jsonp/en";
import {IntlProvider, addLocaleData} from "react-intl";
import {SomeOtherProvider} from "some-other-provider";

const locale = "en";
const messages = require(`../lang/${locale}.json`);
const localeData = require(`react-intl/locale-data/${locale}`);

addLocaleData(localeData);

export default (Component) => {
  return (props) => {
    (
      <IntlProvider locale={locale} messages={messages}>
        <SomeOtherProvider>
          <Component {...props} />
        </SomeOtherProvider>
      </IntlProvider>
    )
  }
}

class Home extends React.Component {
  render() {
    const props = this.props;
    const {checked, value} = props;
    return (
      <IntlProvider locale={locale} messages={messages}>
      </IntlProvider>
    );
  }
}

Home.propTypes = {
  checked: PropTypes.bool,
  value: PropTypes.number.isRequired
};

const mapStateToProps = (state) => {
  return {
    checked: state.checkBox.checked, value: state.number.value
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    onChangeCheck: () => {
      dispatch(toggleCheck());
    },
    onIncrease: () => {
      dispatch(incNumber());
    },
    onDecrease: () => {
      dispatch(decNumber());
    }
  };
};

```

**Comment by jmcriffey** [comment]
@cross311 Yep that seems like it should work. The main goal here is simply getting `IntlProvider` on the server near the top of the component tree.

**Comment by cross311** [comment]
Cool that makes sense. Just wanted to get something in the issue that was a copy and paste fix.  Thanks for looking into that @jmcriffey !!

**Comment by cross311** [comment]
Updated my comment with the actual code that worked.
