### ISSUE TITLE
Document extending webpack configuration

### ISSUE THREAD

**Issue by karlhorky** [electrode-io/electrode#262]
I didn't find documentation on extending the webpack config. Does this still need to be documented?

https://github.com/electrode-io/electrode/issues/97#issuecomment-274150029

**Comment by animesh10** [comment]
PR for documentation: https://github.com/electrode-io/electrode/pull/284

**Comment by jchip** [comment]
https://docs.electrode.io/chapter1/intermediate/app-archetype/webpack-config.html#overriding
