### ISSUE TITLE
Publish new versions of packages?

### ISSUE THREAD

**Issue by karlhorky** [electrode-io/electrode#265]
Is is possible to publish new versions of the npm packages that have been updated? I [asked in gitter](https://gitter.im/electrode-io/electrode?at=58de772a8e4b63533d823665) as well.

**Comment by animesh10** [comment]
Hi, There are a few updates that we would like to include in the new versions. We would be publishing the packages soon.

**Comment by cross311** [comment]
There are a lot of things sitting that we really want like node engines.  What timeframe are we talking.

**Comment by cross311** [comment]
Any update on this?  Still have work around my team is having to do because of the node engines.

**Comment by animesh10** [comment]
We're planning for sometime next week.

**Comment by cross311** [comment]
Is there a nightly build test package we can subscribe to?  Since this is such a quick-moving project would love to be able to get access to things even if they are still a little raw.

**Comment by animesh10** [comment]
We just released new versions, nightly builds are a good suggestion.
