### ISSUE TITLE
How to debug the server side application?

### ISSUE THREAD

**Issue by dennisat** [electrode-io/electrode#277]
To debug the gulp task you can use this (in package.json) `"start:debug": "node --inspect $(which gulp) dev",` but this is not debugging the server side code... probably it runs on different instance (node js call).

**Comment by didi0613** [comment]
@dennisat please try to logging the contents by adding console.log inside of webpack configurations to check the values. Server side cannot break by debugger.

**Comment by animesh10** [comment]
@dennisat : Did you try `gulp build` followed by `gulp server-debug` ?

**Comment by dennisat** [comment]
Based on this I made [this PR](https://github.com/electrode-io/electrode/pull/300) with some gulp tasks to debug with dev tools
