### ISSUE TITLE
How to set the meta tags {{META_TAGS}} on each request? 

### ISSUE THREAD

**Issue by dennisat** [electrode-io/electrode#281]
What I want is a route-specific meta tags assignment.
On each server side page rendering I want to assign specific meta tags inside the head.

**Comment by caoanhhao** [comment]
@dennisat yeah. we can.

in **config/default.js**. add **tokenHandler** to you path options.
<pre>webapp: {
      module: 'electrode-react-webapp/lib/hapi',
      options: {
        pageTitle: 'SKYPERRY | Agency Influencers Marketing in Viet Nam',
        paths: {
          '/{args*}': {
            content: {
              module: './{{env.APP_SRC_DIR}}server/views/index-view'
            },
            tokenHandler: './{{env.APP_SRC_DIR}}server/views/index-handler.js',
          }
        },
        serverSideRendering: true,
        htmlFile: './{{env.APP_SRC_DIR}}server/views/index.html'
      }
    },</pre>

in file **server/views/index-view.jsx**. add your meta tag to request object
<pre>module.exports = (req) => {
  const app = req.server && req.server.app || req.app
  if (!app.routesEngine) {
    app.routesEngine = new ReduxRouterEngine({routes, createReduxStore});
  }
  req.meta = '<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">'
  return app.routesEngine.render(req);
}
</pre>

create file **server/views/index-handler.js** ( a copy of "electrode-react-webapp/lib/custom-token.js" ).  look at **console.log(context.$.request.meta)**
<pre>'use strict';

const CONTENT_MARKER = 'SSR_CONTENT';
const HEADER_BUNDLE_MARKER = 'WEBAPP_HEADER_BUNDLES';
const BODY_BUNDLE_MARKER = 'WEBAPP_BODY_BUNDLES';
const TITLE_MARKER = 'PAGE_TITLE';
const PREFETCH_MARKER = 'PREFETCH_BUNDLES';
const META_TAGS_MARKER = 'META_TAGS';
const CRITICAL_CSS_MARKER = 'CRITICAL_CSS';
const groupScripts = require('electrode-react-webapp/lib/group-scripts');

module.exports = function setup(options) {
  const routeOptions = options.routeOptions
  const routeData = options.routeData
  const WEBPACK_DEV = routeData.WEBPACK_DEV
  const assets = routeData.assets
  const devBundleBase = routeData.devBundleBase
  const prodBundleBase = routeData.prodBundleBase;
  const iconStats = routeData.iconStats
  const criticalCSS = routeData.criticalCSS;
  const bundleManifest = () => {
    if (!assets.manifest) {
      return '';
    }
    return WEBPACK_DEV
      ? `${devBundleBase}${assets.manifest}`
      : `${prodBundleBase}${assets.manifest}`;
  };
  const bundleJs = data => {
    if (!data.renderJs) {
      return '';
    }
    return WEBPACK_DEV
      ? data.devJSBundle
      : (data.jsChunk && `${prodBundleBase}${data.jsChunk.name}`) || '';
  };
  const htmlifyScripts = (scripts, scriptNonce) => {
    return scripts
      .map(
        x =>
          typeof x === 'string'
            ? `<script${scriptNonce}>${x}</script>\n`
            : x.map(n => `<script src='${n.src}'></script>`).join('\n')
      )
      .join('\n');
  };
  return {
    [CONTENT_MARKER]: context => {
      return context.content.html || '';
    },
    [TITLE_MARKER]: () => {
      return `<title>${routeOptions.pageTitle}</title>`;
    },
    [HEADER_BUNDLE_MARKER]: context => {
      const data = context.$.data;
      const manifest = bundleManifest();
      const manifestLink = manifest ? `<link rel='manifest' href='${manifest}' />\n` : '';
      const css = WEBPACK_DEV
        ? data.devCSSBundle
        : (data.cssChunk && `${prodBundleBase}${data.cssChunk.name}`) || '';
      const cssLink = css && !data.criticalCSS ? `<link rel='stylesheet' href='${css}' />` : '';
      const htmlScripts = htmlifyScripts(
        groupScripts(routeOptions.unbundledJS.enterHead).scripts,
        context.$.data.scriptNonce
      );
      return `${manifestLink}${cssLink}${htmlScripts}`;
    },
    [BODY_BUNDLE_MARKER]: context => {
      const js = bundleJs(context.$.data);
      const jsLink = js ? { src: js } : '';
      const ins = routeOptions.unbundledJS.preBundle
        .concat([jsLink])
        .concat(routeOptions.unbundledJS.postBundle);
      const htmlScripts = htmlifyScripts(groupScripts(ins).scripts);
      return `${htmlScripts}`;
    },
    [PREFETCH_MARKER]: context => {
      return !context.content.prefetch
        ? ''
        : `<script${context.$.data.scriptNonce}>${context.content.prefetch}</script>`;
    },
    [META_TAGS_MARKER]: context => {
      console.log(context.$.request.meta)
      return `${context.$.request.meta}`;
    },
    [CRITICAL_CSS_MARKER]: context => {
      return criticalCSS ? `<style${context.$.data.styleNonce}>${criticalCSS}</style>` : '';
    },
    INITIALIZE: () => undefined,
    HEAD_CLOSED: () => undefined,
    AFTER_SSR_CONTENT: () => undefined,
    BODY_CLOSED: () => undefined,
    HTML_CLOSED: () => undefined
  };
};
</pre>
