### ISSUE TITLE
use next.js with electrode

### ISSUE THREAD

**Issue by danutc** [electrode-io/electrode#302]
Do you think it is possible to use next.js with electrode?

https://github.com/zeit/next.js/

good short description is here: https://learnnextjs.com/basics/getting-started

**Comment by jchip** [comment]
I am not sure, but could you please also open an issue in next.js and ask whether it's possible to use it with electrode?  Thanks.

**Comment by danutc** [comment]
I asked the question here: https://github.com/zeit/next.js/issues/1850

**Comment by selique** [comment]
@danutc i go try do it this month, if u know more enter in contact
