### ISSUE TITLE
`gulp dev` fails with electrode 2.4

### ISSUE THREAD

**Issue by LuckStock** [electrode-io/electrode#303]
Error: 'Cannot read property 'socketPort' of undefined'
Solution: fix the issue in:
> electrode-webpack-reporter/lib/webpack-reporter.js

Change: options.socketPort to this.options.socketPort

**Comment by FreaKzero** [comment]
Anyone knows when a new release is planned with the fix for this and the other pullrequests ?

**Comment by cross311** [comment]
@seansean11 can you open a pull request up with your change.

**Comment by cross311** [comment]
Duplicate: #295
