### ISSUE TITLE
React Router out of date

### ISSUE THREAD

**Issue by TheLordHighExecutioner** [electrode-io/electrode#310]
Some code uses outdated React Router modules (for example, using browserHistory + Router instead of BrowserRouter). I'd love to do some quick updating!

**Comment by animesh10** [comment]
Thanks for pointing that out! We need to upgrade our react router as we are a few versions behind.

**Comment by jchip** [comment]
react-router v4 severely changed the way routing works.  this will take some time.

**Comment by idhard** [comment]
is there some plan to make the upgrade  or is something you don't see  in the pipeline for a while ?  thanks

**Comment by dan3721** [comment]
Is there a roadmap / eta for router v4 support?

**Comment by jchip** [comment]
Is there any feature v4 offers that makes significant diff?  I want to focus on code splitting, improve docs, and developer experience in this quarter.

**Comment by dan3721** [comment]
We would like to utilize [Nesting Routes](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#nesting-routes), as Route is now an actual component, so we can keep the child routes with the sub modules as opposed to the pre v4 editions in which there is a single routes config. We have multiple independent teams working and I would like to not have to have them meet and compete in that single routes config.

**Comment by qbitza** [comment]
Also regular expression matching

**Comment by ryx** [comment]
Hi. Is there any e.t.a. when React Router v4 will make it's way into electrode?

**Comment by karanmartian** [comment]
Hi is React router v4 supported as yet with the latest release of electrode?

**Comment by ryx** [comment]
Hi @jchip, since the last official response from the electrode team regarding this (quite popular) topic seems to be almost one year old now - is there any chance to get an update on this? Thanks in advance.

**Comment by jchip** [comment]
sorry this took a while.

coming soon (this week).  It will be a major change, so need to update all samples and generator etc.

**Comment by jchip** [comment]
v2 of redux router engine released.

electrode-ignite and generator also generates new apps to use that.

doc https://docs.electrode.io/advanced/stand-alone-modules/redux-router-engine
