### ISSUE TITLE
Error: Cannot find module './partial/stylus.js'

### ISSUE THREAD

**Issue by aleplusplus** [electrode-io/electrode#311]
Error: Cannot find module './partial/stylus.js'

electrode-archetype-react-component/config/webpack/webpack.config.js:16:22

**Comment by didi0613** [comment]
@aleplusplus Hi, can you please let me know your version of electrode-archetype-react-component?
Thanks

**Comment by LeeFrancis** [comment]
@aleplusplus , I think this has been taken care of in this PR : https://github.com/electrode-io/electrode/pull/312

**Comment by sergesemashko** [comment]
I have the same error using `1.4.1`. 
But if I comment [`const stylusConfig = require("./partial/stylus.js");`](https://github.com/electrode-io/electrode/blob/webpack-1.0/packages/electrode-archetype-react-component/config/webpack/webpack.config.js#L16) it seemed to be going through:
```js
// ./node_modules/electrode-archetype-react-component/config/webpack/webpack.config.js
"use strict";
const path = require("path");

const archDevRequire = require("electrode-archetype-react-component-dev/require");
const _ = archDevRequire("lodash");


const babelConfig = require("./partial/babel.js");
const stylesConfig = require("./partial/styles.js");
const defineConfig = require("./partial/define.js");
const fontsConfig = require("./partial/fonts");
const imageConfig = require("./partial/images.js");
const jsonConfig = require("./partial/json.js");
const optimizeConfig = require("./partial/optimize.js");
const sourceMapsConfig = require("./partial/sourcemaps.js");
// const stylusConfig = require("./partial/stylus.js"); - references to non-existing file + unused variable

```

I'm going to try latest `2.0.0` version

**Comment by animesh10** [comment]
@sergesemashko : yes the latest `2.0.0` version should take care of that.

**Comment by sergesemashko** [comment]
Dependency upgrade did actually work. I guess, [this PR](https://github.com/electrode-io/electrode/pull/312/files) should eliminate the confusion. Currently, electrode-generator installs `electrode-archetype-react-component@^1.0.0`
