### ISSUE TITLE
Module build failed: SyntaxError on Component arrow function bindings

### ISSUE THREAD

**Issue by guymorita** [electrode-io/electrode#326]
./src/client/components/recipe-list.jsx
Module build failed: SyntaxError: Unexpected token

```
 12 |   }
  13 | 
> 14 |   _onDeleteRecipe = (id) => {
     |                   ^
  15 |     this.props._onDeleteRecipe(id);
  16 |   }
  17 | 

 @ ./src/client/components/cookbook.jsx 29:18-42
 @ ./src/client/routes.jsx
 @ ./src/client/app.jsx
 @ multi (webpack)-dev-server/client?http://localhost:2992 ./app.jsx
```

Binding arrow functions should be valid in ES6. Any reason why this doesn't work?

**Comment by rebmullin** [comment]
i extended the babelrc files that were provided:

```javascript
{
  "extends": "electrode-archetype-react-app-dev/config/babel/babelrc-client",
  "presets": [
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "typecheck",
    "syntax-flow",
    "transform-flow-strip-types",
    "transform-decorators-legacy",
    "add-module-exports"
  ]
}
```
not sure if you'll need all of this but it should help with a lot of ES6

**Comment by jchip** [comment]
there is no reason you should get that error.  please provide sample or steps to repro the issue.

**Comment by guymorita** [comment]
The only step was cloning the getting-started repo. I'll try to reproduce later and will have more detailed steps / specs.

**Comment by jchip** [comment]
I may have repro this, looking.

**Comment by jchip** [comment]
The upgrade from isparta-loader to istanbul-instrument-loader caused karma test to fail on some ES6 syntax like the spread operator, see https://github.com/electrode-io/electrode/pull/464 and https://github.com/electrode-io/electrode/pull/465, but w/o info on how you even got your error, I am not sure if it's related.
