### ISSUE TITLE
webpack-dashboard integration?

### ISSUE THREAD

**Issue by isaachinman** [electrode-io/electrode#33]
Really like the looks of this project, and am excited to dig into it in the coming weeks.

My initial question has to do with tooling, not core tech: are there any plans to incorporate [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) into the dev environment? I've grown to really value it, and I think it could be particularly helpful in this case as well.

If there's interest, I can also look into a PR to get it up and running.

![screen shot 2016-10-15 at 17 59 30](https://cloud.githubusercontent.com/assets/10575782/19411400/3a541c24-9301-11e6-9c17-11f4c907eda8.png)

**Comment by jchip** [comment]
Hi, we have a bunch of HTML based tools that does similar things and we'd like to keep them as the defaults.  I think enabling webpack-dashboard would also be a cool option, but I'd like that to be an opt-in.  I am pondering on implementing some kind of facility to support archetype add-ons so users can create their own add-ons for archetypes that support custom features.

**Comment by isaachinman** [comment]
> HTML based tools

Can you point me in the right direction? I wasn't aware of this.

**Comment by ananavati** [comment]
https://github.com/electrode-io/electrode-webpack-reporter/pull/3
