### ISSUE TITLE
update paths in documentation

### ISSUE THREAD

**Issue by varoonsahgal** [electrode-io/electrode#330]
This page:

https://electrode.gitbooks.io/electrode/content/chapter1/intermediate/create-a-reusable-component/low-level-components.html

Currently points to `<your-awesome-component>/src/components/guest-list.jsx`, I believe it should instead point to `<your-awesome-component>/src/client/components/guest-list.jsx` instead.

Note the `client` directory in new path - the directory structure from the Electrode generator is `src/client` and `src/server`.  Unless I am missing something here, a lot of other pages in the documentation would need to be updated to reflect this directory structure (too many for me to list), for instance this one:

https://electrode.gitbooks.io/electrode/content/chapter1/intermediate/create-a-reusable-component/develop-styles.html

**Comment by didi0613** [comment]
@varoonsahgal  The original documentation is followed by the old version without src/lib mode.
Thanks for pointing this out, will update.

**Comment by didi0613** [comment]
The docs have been updated. Please check.
