### ISSUE TITLE
Redirecting to another URL on Electrode Server

### ISSUE THREAD

**Issue by rcbitencourt** [electrode-io/electrode#334]
Hi guys, i need some help and i have the following case :

We receive a non-well parsed params on our Electrode instance.

**What we need?**
We need to parse this params and redirect to a well-parsed params url, it have to be on server side, and we have to redirect with statusCode 301/302.

**Our problem?**
We tried using the match params on createReduxStore example, but, looking out the code, it doesn't anything when trying using the redirectLocation prop.

Probably it's easy, and we didn't realize yet how to do, but we need some help.
Is there a method for that? Or some redirect example on index-view.js?

Thanks and Congrats for the project!

**Comment by jchip** [comment]
could you give some example of your malformed URLs?  

The routes for the `paths` from electrode-react-webapp are setup here https://github.com/electrode-io/electrode/blob/4d7e6c33e43409b8b20d5d16368d347acad3a277/packages/electrode-react-webapp/lib/hapi/index.js#L19

that then call the handler for each route here https://github.com/electrode-io/electrode/blob/4d7e6c33e43409b8b20d5d16368d347acad3a277/packages/electrode-redux-router-engine/lib/redux-router-engine.js#L61

If your URL is just query params that's malformed, then we need to let you have a chance to inspect the URL before `routeHandler` is invoked here https://github.com/electrode-io/electrode/blob/4d7e6c33e43409b8b20d5d16368d347acad3a277/packages/electrode-react-webapp/lib/hapi/index.js#L33

For now, you can override the registerRoutes plugin with your own: https://github.com/electrode-io/electrode/blob/4d7e6c33e43409b8b20d5d16368d347acad3a277/packages/electrode-react-webapp/lib/hapi/index.js#L10

**Comment by devourment77** [comment]
@jchip Would this also be the case if we wanted to remove trailing slashes and doing a 302 redirect?  Doing this for every route can get repetitive.
```
<Redirect from="some-view/:slug/" to="some-view/:slug" />
<Route path="some-view/:slug" component={SomeViewContainer} />
```
