### ISSUE TITLE
electrode-react-webapp: Obtaining koa context in view (Feature request)

### ISSUE THREAD

**Issue by sergesemashko** [electrode-io/electrode#335]
First of all, thanks for open sourcing Electrode, it's great!

I've been trying to obtain [koa state from context](http://koajs.com/#context) inside of view, but there is only request object passed in parameters.

My config looks like:
```js
module.exports = {
  //...
  'webapp': {
      'module': 'electrode-react-webapp/lib/koa',
      'options': {
        'pageTitle': 'test-electrode-app',
        'paths': {
          '*': {
            'content': {
              'module': './{{env.APP_SRC_DIR}}/server/views/index-view'
            }
          }
        }
      }
    }
  }
//...
}
```

Main view:
```js
// './server/views/index-view'
module.exports = (req) => {
  const app = req.server && req.server.app || req.app;
  const criticalData = this.state.criticalData // koa state
  const createReduxStore = (req, match) => {
     // use criticalData to generate store
  };
  if (!app.routesEngine) {
    app.routesEngine = new ReduxRouterEngine({routes, createReduxStore});
  }

  return app.routesEngine.render(req);
};
```

I've been trying to move my current project to electrode, and this became a blocker for me, as I'm passing some critical info through koa state from upstream middlewares.

It would be great if we could replace `request` by koa context as `ctx` [on this line](https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/react-webapp.js#L173) in next major version update of `electrode-react-webapp`. 
That would expose koa context, which already contains `request` as well as other useful [koa context's](http://koajs.com/#context) data, like state, cookies, app, response and etc.

Default view code would look like:
```js
module.exports = (ctx) => {
  const app = ctx.app ;
  if (!app.routesEngine) {
    app.routesEngine = new ReduxRouterEngine({routes: getRoutes(), createReduxStore});
  }

  return app.routesEngine.render(ctx);
};
```

Any thoughts or help regarding this issue is appreciated.

**Comment by animesh10** [comment]
@sergesemashko Thanks for using electrode! we will make sure we address in an upcoming release.
