### ISSUE TITLE
electrode-react-webapp: Ability to use custom `index.html` (Feature request)

### ISSUE THREAD

**Issue by sergesemashko** [electrode-io/electrode#336]
Currently, there is no way to override anything in page template as it's [hardcoded](https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/react-webapp.js#L261) to `./lib/index.html`. That complicates the usage of [react-side-effect](https://github.com/gaearon/react-side-effect) modules on server, as there is no way to reflect side effect states in markup.

Example use case:
`bodyAttributes` and `htmlAttributes` from [react-helmet](https://github.com/nfl/react-helmet) are not reflected in markup from server and applied only in browser, which causes repaints and some other undesirable effects.

I could help with the pull request if the change sounds good.

**Comment by sergesemashko** [comment]
nvm, figured the way to override it through [options](https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/react-webapp.js#L274)

**Comment by joaodfmota** [comment]
> @sergesemashko Can you elaborate a bit?

``` config/default.js ```

Add: ```htmlFile: "./{{env.APP_SRC_DIR}}/index.html",``` on ```webapp.options```
``` JS
...
    module: "electrode-react-webapp/lib/express",
    options: {
      pageTitle: "web-app",
      htmlFile: "./{{env.APP_SRC_DIR}}/index.html",
      insertTokenIds: false,
...
```
