### ISSUE TITLE
Link to sample applications is a 404 in readme

### ISSUE THREAD

**Issue by kumar303** [electrode-io/electrode#338]
From the [readme](http://www.electrode.io/docs/what_is_electrode.html) :

> Some sample applications can be found under the samples directory.

The samples link is a 404. What is the updated link?

The section I was looking at is at the bottom here (I cannot find a way to link to it):

<img width="815" alt="screenshot 2017-05-25 11 42 25" src="https://cloud.githubusercontent.com/assets/55398/26460515/7ed347ac-413f-11e7-9bb1-f83d22f9204d.png">

**Comment by animesh10** [comment]
Thanks for reporting the issue, and thanks for using Electrode.
