### ISSUE TITLE
How to call a webservice

### ISSUE THREAD

**Issue by Miteshivgroup** [electrode-io/electrode#357]
As per the documentation of [electrode-redux-router-engine](https://www.npmjs.com/package/electrode-redux-router-engine) I can call API, can you provide an example to fetch data  from web service using Promise(blue-bird) or do i need to use axios to call an API and provide the data too store on server side.
So what is requirement is to show and hide elements according to the configuration please help me to find a way because I am planning to use [memcached](https://memcached.org/about) to fetch data, if I dont get the result from that I want to call an API to fetch the configuration and render the page accordingly.

**Comment by jchip** [comment]
Hi, sorry, this is out of scope for Electrode.
