### ISSUE TITLE
css without css-modules

### ISSUE THREAD

**Issue by SnowDiamond** [electrode-io/electrode#361]
I'm trying to migrate my existing project to electrode platform. For now, I have a problem with css styles that settled like classes or id. For example, my code:

```javascript
import React from 'react';

export default () => (
    <h1 className='welcome'>Hello</h1>
);
```
and styles.css (imported in higher component):

```css
.welcome {
  color: red;
}
```

In this case, styles won't affect tag h1, but I need it because all project uses css styles in this way. Is it possible to configure electrode to use css in a regular way?

**Comment by animesh10** [comment]
You can take a look at our [sample app](https://github.com/electrode-io/electrode/tree/master/samples/universal-react-node), we are using a top level bases.css file as well: https://github.com/electrode-io/electrode/tree/master/samples/universal-react-node/src/client/styles

**Comment by seansean11eis** [comment]
@animesh10 I don't think that will work.  I've been trying to figure out an easy way to disable CSS modules for certain files with no luck.  By importing `import "./styles/base.css";` like the sample app does your code will pass through the "extract-style" partial and will mangle the classes.

**Comment by jchip** [comment]
Trying to solve this with using CSS as modules in the code will not work.  For now, you would have to manually add a `<link` to your index HTML to load the raw CSS you want.  

Right now, the react-webapp module we have isn't very flexible and it's got this header bundle here https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/react-webapp.js#L185.

react-webapp is in fact a much simplified version of our internal one.  

We are working on some ideas to make a react-webapp that supports some kind of plugins so it's a lot more flexible for you to customize how your index HTML is constructed, but originally I was expecting each app to copy react-webapp if it needs significant customization.

**Comment by jchip** [comment]
Of course, maybe postcss or css module loader etc have an option to let you white list CSS files, but I have to check into that.

**Comment by seansean11eis** [comment]
@jchip great to hear that you are looking into adding flexibility to the react-webapp module...we have run into quite a few instances where we wanted to inject scripts or styles into the header bundle, during SSR (i.e. dynamic localization scripts, dynamic CSS theming, etc...), but have had to resort to using Helmet on the client, which doesn't always work the way we need it to (especially if you need to dynamically include a file).

For disabling CSS modules for the entire project, I would think that you could create a custom webpack config following these instructions https://github.com/electrode-io/electrode/blob/master/docs/chapter1/intermediate/app-archetype/webpack-config.md.  You could then disable the `_extract-styles` and enable a custom version of this, removing the css modules portion.
