### ISSUE TITLE
Demo server for electrode:component

### ISSUE THREAD

**Issue by mbaertschi** [electrode-io/electrode#365]
Hi all

In the old release with the webpack1.0 we had a demo-server for component development (with the electrode-component generator). With the new generator (electrode:component and electrode:component-add) we received the demo-app which, however:
- has no hot reload for component changes (components being developed under /packages/\<component>)
- installs the component as a package dependency
- forces the developer to remove the package and reinstall it and restart the demo-app from scratch for every single change made in the component in the packages folder

This tells me that the demo-app is not intended to be used for component development right? Is there another possibility? It would be great to have an environment like the old demo-server where one was able to implement components with hot-reload feature enabled.

Thx,
Michael

**Comment by didi0613** [comment]
Hi Michael,

Thank you so much for your suggestions. We are working on the component electrode-generator right now. Will release the auto reload modules feature in the next release.

**Comment by jchip** [comment]
this is fixed in latest component archetype.
