### ISSUE TITLE
Server side unit test of index-view.jsx fail

### ISSUE THREAD

**Issue by adaniliuk** [electrode-io/electrode#38]
Hello,

It seems like server side unit tests of index-view.jsx fail:
- `gulp test-server-dev` fails with **SyntaxError: Unexpected token import** error because of lack of **--compilers** mocha option;
- even if option is added, non js resources (like scss, svg, etc) fail to load. Use `npm run test:server:dev` in the provided fork to reproduce this.

There is fork demonstrating both cases - https://github.com/adaniliuk/electrode-boilerplate-universal-react-node

**Comment by adaniliuk-edmunds** [comment]
Just in case my dev environment is:

Windows 10
node v6.9.1
npm v3.10.8

**Comment by citelao** [comment]
+1

**Comment by tbohlen** [comment]
+1 running into the same issue testing my new electrode project.

**Comment by animesh10** [comment]
fixed in: https://github.com/electrode-io/electrode/pull/224

**Comment by animesh10** [comment]
@tbohlen are you facing this issue on windows as well ?

**Comment by tbohlen** [comment]
@animesh10 No, I'm on a mac running Sierra (10.12.3)

I just replicated the issue I was running into in a new project (I had fixed it by adding in a babel-register script for server-side testing). I _think_ its the same as what you're running into, @adaniliuk but I could be wrong:

- I create a new server file (in this case I made a dummy `adder.js` file) that `import`s something.
- I created a new test file for it (`adder.spec.js`). I `require` adder.js here.
- I run `gulp check`

Result: `SyntaxError: Unexpected token import` thrown at the `import` line in `adder.js`

As far as I can tell, either all server code has to be written in es5, or you need a transpiler in place for mocha to use to convert everything before running your tests. Not sure which is intended in the code base, but I would certainly prefer the latter come by default :)

**Comment by jchip** [comment]
In general, you unit test code in client with karma test only.  server side code should be tested as pure server side code.

To test client code as part of server, a new type of tests would be needed, something like `test-ssr` maybe.

Close for now and will revisit if I have time.
