### ISSUE TITLE
Application not working on other client machine

### ISSUE THREAD

**Issue by Miteshivgroup** [electrode-io/electrode#420]
Hello,
Please check the files which searches files in the client browser please have a look on the same.
I have attached the screenshot which I am facing please do let me know if anything can be done to resolve 
![2017-06-22](https://user-images.githubusercontent.com/22392408/27438485-0551c304-5783-11e7-8f91-b02c23285b6c.png)

There is another problem where I get a response as mentioned in screenshot, please do mention the steps on you documented page
![clap](https://user-images.githubusercontent.com/22392408/27438835-0d4afd40-5784-11e7-85b5-6c07281e11ee.png)

Thanks,
Mitesh

**Comment by jchip** [comment]
your first image is too blurry.

your second problem is because you are not using app archetype v3 but you try to use clap, which is for v3 only.

**Comment by Miteshivgroup** [comment]
Sorry for the blurry image here is another screenshot, please do have a look 
![remote](https://user-images.githubusercontent.com/22392408/27474066-c6c8a408-581e-11e7-83c2-52766ca639a7.png)
And for the second part where should I need to change because the application which I am referring is the fresh new application created by command yo:electrode [yo:electrode](http://www.electrode.io/docs/get_started.html).

**Comment by jchip** [comment]
not sure what's the problem, what am I supposed to look for, etc.

**Comment by Miteshivgroup** [comment]
The problem is if I open the application in browser in client's machine application is not working properly, just for instance if my hit is on 192.168.0.108:3000 main.style.css should also find in 92.168.0.108:3000 but it is finding it on local machine.

**Comment by Miteshivgroup** [comment]
Hello @jchip ,
Thank you for your valuable time, this problem got resolved by add SET WEBPACK_HOST=192.168.0.112 in node environment.
Thanks once again and you are doing a great work.
