### ISSUE TITLE
the new generator 3.0.2 & xclap has issues with windows

### ISSUE THREAD

**Issue by gkarwchan** [electrode-io/electrode#421]
I used the new generator (version 3.0.2) to generate a new application.
When I do "clap dev", it gives me this error on Windows 10

error: uncaughtException: Invalid regular expression: /\node_modules\/: \ at end of pattern
{ date: 'Thu Jun 22 2017 08:22:18 GMT-0600 (Mountain Daylight Time)',
  process:
   { pid: 2476,
     uid: null,
     gid: null,
     cwd: 'C:\\code\\hello-electrode',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v6.10.3',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\Users\\gkarwchan\\AppData\\Roaming\\npm\\node_modules\\xclap-cli\\clap.js',
        'dev' ],

.....
......

 stack:
   [ 'SyntaxError: Invalid regular expression: /\\node_modules\\/: \\ at end of pattern',
     '    at RegExp (native)',
     '    at Object.replace (C:\\code\\hello-electrode\\node_modules\\xsh\\lib\\path-cwd-nm.js:18:22)',
     '    at clap (C:\\code\\hello-electrode\\node_modules\\xclap\\cli\\clap.js:96:48)',

====================
Another note.
On windows, when you submit the command "clip dev" from a directory that contains a file "clip.js", windows by default will try to run clip.js in windows host script 

so to run it through xclap you should run the xclap that is in the general npm repository, like this:

c:\users\your-user-name\appdata\roaming\npm\clap.cmd clap.js

is there a way to fix this?

**Comment by jchip** [comment]
Thanks for the report.  I haven't had a chance to test this on Windows yet.  I will try it and fix the issue soon.

**Comment by jchip** [comment]
the syntaxerror is fixed.

for now, windows directly trying to invoke the file `clap.js` can be resolved by using the alias command `xclap`.  I will rename the file to `clapfile.js`.
