### ISSUE TITLE
Set generateScopedName to [local]

### ISSUE THREAD

**Issue by Patricknew** [electrode-io/electrode#444]
In main.style.css, all the classnames and id names are changed to something like: #content__test___M6sKt. So all css are not applied. Same problem as #333 . 

But I see in [['electrode-archetype-react-app']](https://github.com/electrode-io/electrode/blob/26be7d987662131c0d9489f0340c31401378181d/packages/electrode-archetype-react-app/supports.js#L8) , there is 

`options.generateScopedName = options.generateScopedName || "[hash:base64]";`. 

How can I override it to [local], so that names wouldn't get modified?

FYI:     "electrode-archetype-react-app": "^2.0.0",
    "electrode-auto-ssr": "^1.0.0",
    "electrode-confippet": "^1.0.0",
    "electrode-react-ssr-caching": "^0.1.3",
    "electrode-react-webapp": "^1.1.0",
    "electrode-redux-router-engine": "^1.2.2",
    "electrode-server": "^1.0.0",
    "electrode-static-paths": "^1.0.0",

**Comment by jchip** [comment]
Hi, thanks for the report.  This is an issue with the CSS Module webpack partial at the moment.  The generateScopedName is only in the server side run time code.  The original author has moved to other projects so we have to figure it out first.

**Comment by Patricknew** [comment]
Thank you @jchip 

Right now, I'm just using `:global()` in base.css. The names are not changed. Please keep me updated.
