### ISSUE TITLE
How to update meta tags for SEO when using server-side rendering?

### ISSUE THREAD

**Issue by srinikandula** [electrode-io/electrode#453]
This is more of a question which requires a detailed answer but I don't know where else I asked this question. If I'm building my app with electrode how do I update the meta tags on the component pages so that the search engines will index the pages?

-Srini

**Comment by jchip** [comment]
The best way to do that is to copy electrode-react-webapp's index.html and customize it for your app, and then specify the `htmlFile` option in your electrode-react-webapp plugin's `options`, in `config/default.json`.

index.html:
https://github.com/electrode-io/electrode/blob/dcef48abb2a0477ebbd5d1aed957d0f77981a96c/packages/electrode-react-webapp/lib/index.html

Specify `htmlFile` in your webapp plugin's options, sample here:
https://github.com/electrode-io/electrode/blob/dcef48abb2a0477ebbd5d1aed957d0f77981a96c/samples/universal-react-node/config/default.json#L27
