### ISSUE TITLE
404 on serverside route created via server plugin

### ISSUE THREAD

**Issue by iamkevingreen** [electrode-io/electrode#47]
I followed the [basic tutorial](http://www.electrode.io/docs/build_server_plugin.html) on the website to create my own plugin to serve as a backend route to mailchimp, it works entirely fine on my local but throws a 404 in production (in this case heroku), and yes I have the process environments set for mailchimp. I'm experiencing this on both this simple implementation and much further built out implementation. 

https://murmuring-garden-21141.herokuapp.com/

I have very minimally modified the boilerplate to extend a simple mailchimp subscription to bypass the double optin. 

The server route plugin is configured here:

https://github.com/the-couch/mailchimp-electrode/blob/master/server/plugins/mailchimp/index.js

And is called on the client here: 
https://github.com/the-couch/mailchimp-electrode/blob/master/client/components/home.jsx

I've also tested it in postman and get the right responses locally but 404s via heroku. 

I've reverted my real project to the standard mailchimp embed form, because this error only arose in production, the project is very vanilla in functionality, and I don't use any of the redux/state stuff either just render the single home component here:

https://github.com/the-couch/mailchimp-electrode/blob/master/client/app.jsx

**Comment by ananavati** [comment]
@iamkevingreen 

thanks for reporting the issue and checking out electrode, we will look into your repo and try to repro this issue.

**Comment by jchip** [comment]
You should put your mailchimp plugin here https://github.com/the-couch/mailchimp-electrode/blob/4a6e98cb3a197ed8a37275e817cf6e100978554f/config/development.json#L3-L5 in your `config/default.json` so it gets load for all `NODE_ENV` settings.
