### ISSUE TITLE
Documentation is down!

### ISSUE THREAD

**Issue by martineboh** [electrode-io/electrode#475]
The electrode documentation on Electrode.io is down.

**Comment by donsalari** [comment]
seems to be working now.
http://www.electrode.io/

**Comment by martineboh** [comment]
Oh, ok...thanks.

**Comment by didi0613** [comment]
Hi @martineboh
http://www.electrode.io/docs/get_started.html Works for me as well.
Can you please try: https://docs.electrode.io/

**Comment by martineboh** [comment]
Still not working. I am getting **docs.electrode.io’s server DNS address could not be found** for http://www.electrode.io/docs/get_started.html and getting **docs.electrode.io’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN** for https://docs.electrode io/

**Comment by donsalari** [comment]
I am able to load the website. Could try a hard refresh your webpage? Also, clearing cache might just help too.
