### ISSUE TITLE
`clap dev` fails...

### ISSUE THREAD

**Issue by LuckStock** [electrode-io/electrode#490]
Just installed a Electrode according to instructions given in Get Started. 
`clap dev` fails with Webpack bundle is now Valid but has Errors with no hints what error we're facing.
Running with NodeJS 8.2.1 and npm 5.3.0 on Windows 10 machine.
Tried with Hapi and Express, none of them work.

Please test it before pushing.

**Comment by jchip** [comment]
there's no need to get all rude about it.

webpack-dev-server just published 2.6.0 2 hours ago that's causing this, yeah, it'd be nice if they test electrode before pushing.

**Comment by jchip** [comment]
Until we figure what's going on, the work around is do this manually:

```bash
rm -rf node_modules/webpack-dev-server
npm i webpack-dev-server@2.5.1
```

and use lock file to lock it to version 2.5.1.

**Comment by LuckStock** [comment]
Any news regarding the open issue?
