### ISSUE TITLE
latest webpack-dev-server 2.6.0 is causing `clap dev` to fail.

### ISSUE THREAD

**Issue by rl-0x000** [electrode-io/electrode#491]
Brand new install of yoeoman, etc. Up-to-date node + npm:

node 8.1.4
npm 5.3.0

> npm install -g yo generator-electrode xclap-cli
> yo electrode
>... NOTE: No difference seen when choosing different servers, quotes, etc
>
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electrode-archetype-opt-inferno@0.1.1 (node_modules/electrode-archetype-opt-inferno):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electrode-archetype-opt-inferno@0.1.1 preinstall: `node optional-check.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> added 1544 packages in 120.502s
> 
> Your new Electrode application is ready!
> 
> Type 'clap dev' to start the server.
> 
>clap dev 
> ...
> [nodemon] 1.11.0
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: .etmp/bundle.valid.log /Users/robertl/proj/electrode-test/src/server/**/* /Users/robertl/proj/electrode-test/config/**/*
> info: No custom webpack config webpack.config.dev.js found in dirs CWD; CWD/archetype/config/webpack
> info: Entry point configuration /Users/robertl/proj/electrode-test/src/client/entry.config.js is not found, using default entry point...
> Just FYI: optional module not found; Path "/Users/robertl/proj/electrode-test/config/sw-config.js"
> Just FYI: optional module not found; Path "/Users/robertl/proj/electrode-test/config/default.json"
> info: Not disabling NodeSourcePlugin.  NODE_ENV: 'development'
>  10% building modules 1/1 modules 0 active
> Project is running at http://localhost:2992/
> webpack output is served from http://localhost:2992/js/
> webpack bundle is now VALID but has ERRORS
> 

http://localhost:2992/reporter/legacy shows 

> ERROR in (webpack)-dev-server/client?http://localhost:2992
> Module not found: Error: Can't resolve 'webpack/hot' in '/Users/robertl/proj/electrode-test/node_modules/webpack-dev-server/client'
>  @ (webpack)-dev-server/client?http://localhost:2992 79:15-65
>  @ multi (webpack)-dev-server/client?http://localhost:2992 ./app.jsx

webpack/hot 'appears' to be present:

> ~/proj/electrode-test$ ls node_modules/webpack/hot
> dev-server.js		emitter.js		log-apply-result.js	only-dev-server.js	poll.js			signal.js

**Comment by jchip** [comment]
this has been reported before so changing title to reflect the cause.

webpack-dev-server 2.6.0 was published yesterday and caused issues.

Until we figure out what's going on, the workaround is to do the following after `npm install`:

```bash
rm -rf node_modules/webpack-dev-server
npm i webpack-dev-server@2.5.1
```

and update lock file to lock it to 2.5.1.

**Comment by rl-0x000** [comment]
Thanks for the fast response - working well now. Apologies for the duplicate issue... clearly my search foo failed me :-(
