### ISSUE TITLE
Production Build fails with Axios (probably webpack related issue)

### ISSUE THREAD

**Issue by LuckStock** [electrode-io/electrode#493]
Importing Axios (v 0.16.2) in the project breaks the production build (`clap build`), though `clap dev` works without warnings.
Guess it's an issue with webpack, though I didn't have same issue with previous version of Electrode.
`[18:43:05] >>Failed Execute electrode/build-dist-min webpack --config D:\Projects\luckstock\electrode\core\node_modules\electrode-archetype-react-app-dev/config/webpack/webpack.config.js --colors (28.91 sec)
[18:43:05] >Done Process electrode/build-dist serial array [".clean.build","build-dist-dll","build-dist-min","build-dist:flatten-l10n","build-dist:merge-isomorphic-assets","copy-dll","build-dist:clean-tmp"] (28.95 sec)
[18:43:05] Done Process electrode/build serial array ["build-dist",".build-lib","ss-prod-react",".check.top.level.babelrc"] (28.95 sec)
 Execution Failed - Errors:
 1  shell cmd 'webpack --config D:\Projects\luckstock\electrode\core\node_modules\electrode-archetype-react-app-dev/config/webpack/webpack.config.js --colors' exit code 2
    at error (D:\Projects\luckstock\electrode\core\node_modules\xsh\lib\exec.js:9:17)
    at shell.exec (D:\Projects\luckstock\electrode\core\node_modules\xsh\lib\exec.js:42:23)
    at D:\Projects\luckstock\electrode\core\node_modules\shcmd\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)`

**Comment by LeeFrancis** [comment]
I am having the same problem.
"Failed Execute electrode/build-dist-min webpack --config ~/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.js --colors (46.93 sec)"

Some errors that occur in my terminal look like : 
"ERROR in /Users/lee/testui/~/follow-redirects/index.js
Module not found: Error: Can't resolve 'http' in '/Users/lee/testui/node_modules/follow-redirects'

**Comment by uchwyt** [comment]
I had the same problem but with SuperAgent.

With some research i found out that this error was caused by disabling NodeSourcePlugin (by default it's turned off on production). After enabling this plugin (webpack partial node)  `clap build` works like a charm.

**Comment by jchip** [comment]
I don't know anything about axios other than it's a `Promise based HTTP client for the browser and node.js`, but that error means it's using Node's native `http` module and may be causing it to be included into your browser JS bundle.  That's bad, all caps.  You are getting that error because by default NodeSourcePlugin is disabled in electrode app archetype v3.  You can enable it again.  See here https://github.com/electrode-io/electrode/blob/master/packages/generator-electrode/generators/app/templates/xclap.js#L11.  For more details, see blog https://medium.com/walmartlabs/webpack-optimization-a-case-study-92b130334b6c

It's a good thing you got the error.

My recommendation is to use https://github.com/bitinn/node-fetch.

**Comment by LeeFrancis** [comment]
Great blog, very enlightening. Just to test I enabled NodeSourcePlugin and it worked but I will leave disabled and refactor. Thanks.

**Comment by LuckStock** [comment]
Reasonable.
Refactoring the code to substitute Axios to Fetch API, though it may need polyfill on IE and older browsers. Hope it will work.

**Comment by LuckStock** [comment]
I've refactored the code to use isomorphic-fetch (based on node-fetch).
While `clap dev` works, `clap build` fails with the multiple errors pointing to system libs missing:

```
ERROR in D:/Projects/luckstock/electrode/core/~/node-fetch/index.js                                               
Module not found: Error: Can't resolve 'url' in 'D:\Projects\luckstock\electrode\core\node_modules\node-fetch'    
 @ D:/Projects/luckstock/electrode/core/~/node-fetch/index.js 8:16-30 9:18-32                                     
 @ D:/Projects/luckstock/electrode/core/~/isomorphic-fetch/fetch-npm-node.js                                      
 @ D:/Projects/luckstock/react/plugins/microservices.js                                                           
 @ ./actions/formActions.js                                                                                       
 @ ./components/auth/login.jsx                                                                                    
 @ ./routes.jsx                                                                                                   
 @ ./app.jsx                                                                                                      
                                                                                                                  
ERROR in D:/Projects/luckstock/electrode/core/~/node-fetch/lib/request.js                                         
Module not found: Error: Can't resolve 'url' in 'D:\Projects\luckstock\electrode\core\node_modules\node-fetch\lib'
 @ D:/Projects/luckstock/electrode/core/~/node-fetch/lib/request.js 8:16-30                                       
 @ D:/Projects/luckstock/electrode/core/~/node-fetch/index.js                                                     
 @ D:/Projects/luckstock/electrode/core/~/isomorphic-fetch/fetch-npm-node.js                                      
 @ D:/Projects/luckstock/react/plugins/microservices.js                                                           
 @ ./actions/formActions.js                                                                                       
 @ ./components/auth/login.jsx                                                                                    
 @ ./routes.jsx                                                                                                   
 @ ./app.jsx                                                                                                      
                                                                                                                  
ERROR in D:/Projects/luckstock/electrode/core/~/node-fetch/index.js                                               
Module not found: Error: Can't resolve 'https' in 'D:\Projects\luckstock\electrode\core\node_modules\node-fetch'  
 @ D:/Projects/luckstock/electrode/core/~/node-fetch/index.js 11:12-28                                            
 @ D:/Projects/luckstock/electrode/core/~/isomorphic-fetch/fetch-npm-node.js                                      
 @ D:/Projects/luckstock/react/plugins/microservices.js                                                           
 @ ./actions/formActions.js                                                                                       
 @ ./components/auth/login.jsx                                                                                    
 @ ./routes.jsx                                                                                                   
 @ ./app.jsx                                                                                                      
                                                                                                                  
ERROR in D:/Projects/luckstock/electrode/core/~/node-fetch/index.js                                               
Module not found: Error: Can't resolve 'http' in 'D:\Projects\luckstock\electrode\core\node_modules\node-fetch'   
 @ D:/Projects/luckstock/electrode/core/~/node-fetch/index.js 10:11-26                                            
 @ D:/Projects/luckstock/electrode/core/~/isomorphic-fetch/fetch-npm-node.js                                      
 @ D:/Projects/luckstock/react/plugins/microservices.js                                                           
 @ ./actions/formActions.js                                                                                       
 @ ./components/auth/login.jsx                                                                                    
 @ ./routes.jsx                                                                                                   
 @ ./app.jsx                                                                                                      
```

I'm unable to build a production ready bundle. Tried to install isomorphic-fetch, node-fetch, url, etc manually, but it doesn't work.

**Comment by LuckStock** [comment]
jchip,
Removed isomorphic-fetch, changed it with node-fetch (tried both - stable and next 2.0alpha versions). 
Receiving the same errors:
"Can't resolve 'http' in...."
"Can't resolve 'stream'..."
"Can't resolve 'url' in....."
...
What is the solution to use fetch then?
Turns there is no other way, but switch "NodeSourcePlugin" on, as most of apps are dependent on calling external APIs for fetching the data.

**Comment by jchip** [comment]
@LuckStock sorry about that.  there's some default config that's no longer applying.

Temporary work around you can do is, in your `webpack.config.js`, do:

```js
module.exports = {
  resolve: {
    aliasFields: ["browser"],
    mainFields: ["browser", "module", "main"]
  }
};
```

I will work on a release to fix this.

The changes to fix this was merged into webpack, unfortunately it was released along with the breaking changes that caused it to bump to version 3, and updating to webpack 3 is still WIP.

**Comment by LuckStock** [comment]
@jchip Thank you, I've added a custom webpack.conf.js file with the contents you advised above to the root folder of the project and it worked!
