### ISSUE TITLE
webpack-dev-server 2.6.0 cause `clap dev` to fail.

### ISSUE THREAD

**Issue by mcrowder65** [electrode-io/electrode#494]
I am creating a new electrode app with a standard, `yo electrode` and then accept all the defaults except create a new folder, and I am doing single quotes instead of double quotes. And it produces a invalid webpack bundle.. ```Project is running at http://localhost:2992/
webpack output is served from http://localhost:2992/js/
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
webpack bundle is now INVALID
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter```

Also, when I go to the reporter, I don't get any meaningful errors.

![image](https://user-images.githubusercontent.com/10186520/28530696-4e1089c8-705a-11e7-8757-4dfb34020637.png)

**Comment by jchip** [comment]
this has been reported before so changing title to reflect the cause.

webpack-dev-server 2.6.0 was published yesterday and caused issues.

Until we figure out what's going on, the workaround is to do the following after `npm install`:

```bash
rm -rf node_modules/webpack-dev-server
npm i webpack-dev-server@2.5.1
```

and update lock file to lock it to 2.5.1.

Please keep issue open so others will see it.  thanks.
