### ISSUE TITLE
Integrating a component in to an external app

### ISSUE THREAD

**Issue by srinikandula** [electrode-io/electrode#501]
I have created an electrode component using the archetype 'yo electrode:component' let's call it ptd-product-tile(the component class is named 'PtdProductTile'. I also created and an application using 'yo electrode' let's call it ptd-frame. I published my component to npm repository and added it to the dependencies in package.json of my application. When I try to import the component in to 'frame/src/client/components/home.jsx' using the below line I see an error.

`import { PtdProductTile } from 'ptd-product-tile';`

the error I see is here 

> ./src/client/components/home.jsx
Module not found: Error: Can't resolve 'ptd-product-tile' in '/Users/xyz/code/frame/src/client/components'
 @ ./src/client/components/home.jsx 35:22-49
 @ ./src/client/routes.jsx
 @ ./src/client/app.jsx
 @ multi (webpack)

I see the component is downloaded in to node_modules in the application but I don't know how I can use in the application. Can somebody help?

**Comment by jchip** [comment]
check spelling

**Comment by srinikandula** [comment]
Thank you, but do you have any suggestion about the issue in question? Can the components built using electrode:component used by an application other than the demo-app built in to the component? If so can you please point me to an example?

**Comment by heltonvalentini** [comment]
I have run into the same issue.
Create a new App with: `yo electrode`
Created a new component with: `yo electrode:component`

Published my new component on NPM.
After that added the import on `<App>/src/client/routes.jsx` with: `import {TestComponentHelton} from 'test-component-helton';`

And then: `clap dev` on App's root.

Have the following error:
```
./src/client/routes.jsx
Module not found: Error: Can't resolve 'test-component-helton' in '.../<App>/src/client'
 @ ./src/client/routes.jsx 16:27-59
 @ ./src/client/app.jsx
 @ multi (webpack)
```
My global packages are:
```
├── generator-electrode@3.3.0
├── npm@3.10.10
├── xclap-cli@0.1.2
└── yo@2.0.0
```

Everything runs fine on component's demo-app.

**Comment by dan3721** [comment]
test-component-helton should be listed as a package dependency in the App's package.json

the import in the App's route.jsx should then be referencing it via node_modules (as opposed to .../<App>/src/client)

**Comment by heltonvalentini** [comment]
It is listed as a package dependency from `node_modules`. It's imported like you mentioned.
I think you misread webpack's error. The error was thrown from `<App>/src/client/`
My component was published on npm and installed via `npm install`.
Then imported like: `import {TestComponentHelton} from 'test-component-helton';` meaning it should look for it on `node_modules` but somehow webpack can't resolve it.

**Comment by jchip** [comment]
see demo app and component:

**Comment by jchip** [comment]
https://github.com/electrode-io/electrode-demo-app
https://github.com/electrode-io/electrode-demo-component
