### ISSUE TITLE
Cant start with electrode app - Guide is misleading.

### ISSUE THREAD

**Issue by idsingh** [electrode-io/electrode#506]
Following this guide - 
[http://www.electrode.io/docs/get_started.html](url)

Errors

1. clap dev -> 
output ->
`[20:18:31] xclap version 0.2.9 at /usr/local/lib/node_modules/xclap
[20:18:31] CWD is /Users/inder/Data/Development/Repositories/gitlab/koodoit
[20:18:31] Loaded CWD/gulpfile.js
[20:18:31] No tasks found - please load some.

Usage: clap [options] [--] [task1 [task options] task2 [task options] ...]
 Help: clap -h  Example: clap build`

2. Then i noticed that after generating the project, it asks to run **gulp dev**  instead of clap dev. (Please update the documentation, its really misleading). So After running the error - 
`
[19:58:02] Using gulpfile ~/Data/Development/Repositories/gitlab/koodoit/gulpfile.js
[19:58:02] Starting 'dev-$deps$'...
[19:58:02] Starting '.remove-log-files'...
[19:58:02] Finished '.remove-log-files' after 215 μs
[19:58:02] Starting '.development-env'...
[19:58:02] Finished '.development-env' after 99 μs
[19:58:02] Starting '.clean.build'...
[19:58:02] Starting '.clean.dist'...
[19:58:02] Finished '.clean.dist' after 4.17 ms
[19:58:02] Starting '.clean.dll'...
[19:58:02] Finished '.clean.dll' after 666 μs
[19:58:02] Finished '.clean.build' after 5.77 ms
[19:58:02] Starting '.mk-dist-dir'...
[19:58:02] Finished '.mk-dist-dir' after 773 μs
[19:58:02] Finished 'dev-$deps$' after 9.32 ms
[19:58:02] Starting 'dev'...
[19:58:02] Starting '.webpack-dev'...
[19:58:02] Finished '.webpack-dev' after 31 μs
[19:58:02] Starting 'wds.dev'...
[19:58:02] Starting 'server-watch-$deps$'...
[19:58:02] Starting '.init-bundle.valid.log'...
[19:58:02] Finished '.init-bundle.valid.log' after 352 μs
[19:58:02] Finished 'server-watch-$deps$' after 815 μs
[19:58:02] Starting 'server-watch'...
[19:58:02] Starting 'generate-service-worker'...
[19:58:02] Finished 'generate-service-worker' after 271 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/inder/Data/Development/Repositories/gitlab/koodoit/src/server/**/* /Users/inder/Data/Development/Repositories/gitlab/koodoit/config/**/*
info: No custom webpack config webpack.config.dev.js found in dirs CWD; CWD/archetype/config/webpack
info: Entry point configuration /Users/inder/Data/Development/Repositories/gitlab/koodoit/src/client/entry.config.js is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
Just FYI: optional module not found; Path "/Users/inder/Data/Development/Repositories/gitlab/koodoit/config/sw-config.js"
Just FYI: optional module not found; Path "/Users/inder/Data/Development/Repositories/gitlab/koodoit/config/default.json"
 10% building modules 1/1 modules 0 active                                    p Project is running at http://localhost:2992/
webpack output is served from http://localhost:2992/js/
webpack bundle is now VALID but has ERRORS                                    / webpack report is served from http://localhost:2992/reporter

`

_Fixed this by changing the version of webpack-dev-server to 2.5.1_

3.  After this, On running gulp dev, m facing this issue - 
`[20:12:21] Using gulpfile ~/Data/Development/Repositories/gitlab/koodoit/gulpfile.js
[20:12:21] Starting 'dev-$deps$'...
[20:12:21] Starting '.remove-log-files'...
[20:12:21] Finished '.remove-log-files' after 355 μs
[20:12:21] Starting '.development-env'...
[20:12:21] Finished '.development-env' after 52 μs
[20:12:21] Starting '.clean.build'...
[20:12:21] Starting '.clean.dist'...
[20:12:21] Finished '.clean.dist' after 5.07 ms
[20:12:21] Starting '.clean.dll'...
[20:12:21] Finished '.clean.dll' after 743 μs
[20:12:21] Finished '.clean.build' after 6.77 ms
[20:12:21] Starting '.mk-dist-dir'...
[20:12:21] Finished '.mk-dist-dir' after 657 μs
[20:12:21] Finished 'dev-$deps$' after 11 ms
[20:12:21] Starting 'dev'...
[20:12:21] Starting '.webpack-dev'...
[20:12:21] Finished '.webpack-dev' after 38 μs
[20:12:21] Starting 'wds.dev'...
[20:12:21] Starting 'server-watch-$deps$'...
[20:12:21] Starting '.init-bundle.valid.log'...
[20:12:21] Finished '.init-bundle.valid.log' after 418 μs
[20:12:21] Finished 'server-watch-$deps$' after 873 μs
[20:12:21] Starting 'server-watch'...
[20:12:21] Starting 'generate-service-worker'...
[20:12:21] Finished 'generate-service-worker' after 430 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/inder/Data/Development/Repositories/gitlab/koodoit/src/server/**/* /Users/inder/Data/Development/Repositories/gitlab/koodoit/config/**/*
info: No custom webpack config webpack.config.dev.js found in dirs CWD; CWD/archetype/config/webpack
info: Entry point configuration /Users/inder/Data/Development/Repositories/gitlab/koodoit/src/client/entry.config.js is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
Just FYI: optional module not found; Path "/Users/inder/Data/Development/Repositories/gitlab/koodoit/config/sw-config.js"
Just FYI: optional module not found; Path "/Users/inder/Data/Development/Repositories/gitlab/koodoit/config/default.json"
 10% building modules 1/1 modules 0 active                                    p Project is running at http://localhost:2992/
webpack output is served from http://localhost:2992/js/
 10% building modules 5/7 modules 2 active ...t/node_modules/webpack/hot/emitter.js/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
 11% building modules 10/13 modules 3 active ...koodoit/node_modules/events/events.js/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
 13% building modules 25/31 modules 6 active ...de_modules/css-loader/lib/css-base.js/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
 13% building modules 29/34 modules 5 active ...s/html-entities/lib/html5-entities.js/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
 26% building modules 138/169 modules 31 active ...-client/lib/transport/sender/jsonp.js/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
 94% asset optimization                                                       / Starting to optimize CSS...
Processing main.style.46d179c207bc573b2927.css...
Processing main.style.css...
Processed main.style.46d179c207bc573b2927.css, before: 321, after: 83, ratio: 25.86%
Processed main.style.css, before: 293, after: 83, ratio: 28.33%
webpack bundle is now VALID
webpack report is served from http://localhost:2992/reporter
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/server/index.js`
/Users/inder/Data/Development/Repositories/gitlab/koodoit/node_modules/electrode-archetype-react-app-dev/config/babel
info: APP_SRC_DIR set to src/
info: OptimizeModulesForProduction - skipping since NODE_ENV !== "production"
 > isomorphic-loader extend require: webpack dev server mode - config is now valid.
/Users/inder/Data/Development/Repositories/gitlab
(node:29163) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Couldn't find preset "es2015" relative to directory "/Users/inder/Data/Development/Repositories/gitlab"

`
**Unhandled promise rejection (rejection id: 1): Error: Couldn't find preset "es2015" relative to directory** 

Below are the node and npm versions - 

node - 6.9.1
npm - 3.10.8

Request your support in this issue

**Comment by jchip** [comment]
Your system is very confused about its NodeJS installation.

1.  You have a global default NodeJS binary installed at /usr/local
2. You somehow installed `xclap` globally.  There's never any instruction to tell you to do that.  You are suppose to install `xclap-cli` globally only.
3. You are using Electrode modules that are at least a month old.

Please remove every trace of NodeJS from your system, follow the instructions here https://docs.electrode.io/overview/requirements.html, and use nvm to manage your NodeJS installation.

**Comment by idsingh** [comment]
@jchip  Hey, Thanks for the revert

I agree to the second point. I have already done that and m still facing same error and anyhow even if i did install xclap globally, i dont get why it is picking the gulpfile.js from the project folder and not able to call the dev task.

Coming to point-3 - I was using freshly installed generator, xclap-cli and yeoman and bootstraped a project using yo electrode and m still facing the same error i,e error in point-3

Now lastly coming to nodeJS installation -I dont believe There is no fault in it because m already using nvm to manage the version.

Hope you can provide me a meaningful RCA for this issue cz I have tried it on 3 systems and check this issue too which was logged by someone else #502 .

**Comment by jchip** [comment]
It may be OK to install node globally at system level on a production machine where you would not install any custom modules globally.

On a dev machine where you need to install utilities globally and constantly need to update them, using node globally definitely is troublesome and the reason you are running into this issue.

**Comment by jchip** [comment]
> Now lastly coming to nodeJS installation -I dont believe There is no fault in it because m already using nvm to manage the version.

You are not using the NodeJS from nvm.  See path: `/usr/local/lib/node_modules/xclap`

**Comment by idsingh** [comment]
@jchip

this is my version for electrode generator- 3.2.0 and i checked its the latest one.

You r right. I am using the global node(Forgot to switch to nvm version).
But I dont think electrode is dependent on nvm in any way. Let me know if it is.

Anyhow, I got the issue fixed by adding .babelrc file in root project folder with the content -
{
  presets: ["es2015", "react"]
}

So I think it was a babel related issue and not a node version  related one. Hope it helps someone. 
So 2 additional steps to get the electrode setup running based on current code generated - 
1.Used Webpack-2.5.1
2. added .babelrc in project dir. 

I am sure if its not my system specific, But I checked on 3 of another systems and your RCA is not holding up pal.

**Comment by jchip** [comment]
No, whatever you are doing is because of your installation.  Latest Electrode work as is.

Of course electrode is dependent on nvm.  It depends on nvm to setup a proper NodeJS env.

**Comment by idsingh** [comment]
@jchip 

All right, Got your point but it didnt work. Thanks a lot for your support and time. :)

**Comment by jchip** [comment]
correction: Electrode depends on a properly setup NodeJS env.  nvm is recommended, and if you use nvm, it's a dependency.

I just followed the getting started instructions on my system, worked perfectly w/o any modifications.

```
nvm use 6.10.2
nvm uninstall 6.11.1
nvm install 6.11.1
nvm use 6.11.1
npm install -g yo generator-electrode xclap-cli
yo electrode
cd test-app
clap dev
```
