### ISSUE TITLE
electrode-ui-config package doesn't work

### ISSUE THREAD

**Issue by ALeschinsky** [electrode-io/electrode#508]
1) create a new electrode app
2) npm install electrode-ui-config --save
3) Add `ui` to the configuration as explained in readme
4) `import Config from 'electrode-ui-config';` on the client
5) `console.log(Config);` - expected the `ui` key to contain options provided in configuration, but it's always empty... we'll have to create a REST API endpoint and read the configuration options via API, but that's clearly a waste... I tried Express and Hapi for the server side, to no effect...

**Comment by jchip** [comment]
it's not released yet. :)

**Comment by jchip** [comment]
still work in progress

**Comment by ALeschinsky** [comment]
When do you think it can be expected? I had to do this workaround in `app.jsx`:

```
  fetch('/config')
    .then(config => config.json())
    .then(config => _.merge(Config, config))
    .then(() =>
      render(
        <Provider store={store}>
```

This is clearly less than ideal... Is there a way I could modify the HTML rendered on the server? I would just add the config into a variable in the `<head>` to save the async call or something like that...

**Comment by jchip** [comment]
@dvonlehman is working on open sourcing these modules.  He's putting together a small demo.

**Comment by ALeschinsky** [comment]
Is this package still work in progress? Our current solution is we added `/archetype/config/webpack/webpack.common.js` with this:
```
const webpack = require('webpack');
const config = require('electrode-confippet').config;
module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      __UI_CONFIG__: JSON.stringify(config.ui)
    })
  ]
};
```

`__UI_CONFIG__` then is available in `app.jsx`. The only problem is that `clap dev` doesn't pick it up correctly, we have to stop and rebuild when configuration is changed, but that's not a big deal. Hopefully this helps someone with the same problem.

**Comment by abhiisheek** [comment]
Still seeing the issue.

 `electrode-ui-config` is it ready to use ? If yes, please share the sample or example.

**Comment by devourment77** [comment]
Would this be the proper way to expose process.env.NODE_ENV to the UI (using electrode-ui-config)?

**Comment by danivegamx** [comment]
@dvonlehman @jchip can we contribute to help finish this package?

**Comment by jchip** [comment]
@danivegamx this package is actually complete, but we need other parts to get this working isomorphically and they are for our internal modules.  Let me check and bring them to the OSS version.

**Comment by brandonburkett** [comment]
One way we ended up doing this for our app is simply to sync the config.ui object to redux via SSR.  This means it is accessible via connected components, so slightly different than accessing via config import like the backend.

```
const createReduxStore = async ({ req, location, match }) => {
  const userAccount = await getUserFromCookie(req);

  const store = configureStore({
    history: createMemoryHistory({
      initialEntries: [req.url.path],
    }),
    initialState: {
      config: Object.assign(config.ui, {
        base: `${req.headers['x-forwarded-proto'] || req.server.info.protocol}://${req.info.host}/`,
      }),
      users: {
        userAccount,
      },
    },
  });

/* more code */
}
```
