### ISSUE TITLE
Splitting up vendor and app js files.

### ISSUE THREAD

**Issue by LeeFrancis** [electrode-io/electrode#520]
Hi, I am looking to split up my vendor and app js files. 
I created a custom webpack which generates the files fine,
but at run time, I  found myself getting into the inner workings of react-webapp.js. 
Debugging this shows that chunkSelector returns an object of 
```
{
css: "main",
js: "main"
}
```
even if I create a custom chunk-selector that returns multiple js values, eg ["app", "vedor"], react-webpack.js only deals with strings.

**Comment by mspoerer** [comment]
@LeeFrancis How did you solve this issue?
