### ISSUE TITLE
demo app dosent run

### ISSUE THREAD

**Issue by dan3721** [electrode-io/electrode#526]
## Type of issue

bug

----

## My environment

* *OS version/details*: `eg. MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0`
* *Node version:* `8.2.1`
* *npm version:* `5.3.0`
* *Version of yo :* `2.0.0`

## Expected behavior

Demo app starts and hosts component when following the steps in the foo/packages/foo/README.md

## Current behavior

Execution fails with error indication that the dev task is not found.

## Steps to reproduce the behavior

```
$ yo electrode:component
$ cd foo/packages/foo
$ npm install
$ clap dev
```

## Command line output

```
Daniels-MBP:foo dan$ clap dev
[19:02:22] xclap version 0.2.9 at /Users/dan/devel/scratch/foo/packages/foo/node_modules/xclap
[19:02:22] CWD is /Users/dan/devel/scratch/foo/packages/foo
[19:02:22] Loaded CWD/xclap.js
[19:02:22] Added CWD/~/.bin to PATH
 Execution Failed - Errors: 
 1  Task dev not found
```

**Comment by jchip** [comment]
thanks for reporting this.  the READMEs may not be correct and needs update.

the demo-app is in the top level of the repo.

it's a lerna repo so need to `npm install` at top level and then do bootstrap 

```
cd foo
npm i
npm run bootstrap
cd demo-app
npm i
clap dev
```

we will look into add more npm scripts at the top level for these.

**Comment by didi0613** [comment]
@dan3721 Hi thanks for reporting this, please using `demo-app` for previewing your components. basically go to your `demo-app` directory and run `clap dev`. Open browser localhost:3000 and you will see the preview.

For more info, please refer the docs here: https://docs.electrode.io/chapter1/quick-start/start-with-component.html
And here is the PR for fixing this readme: https://github.com/electrode-io/electrode/pull/535

**Comment by dan3721** [comment]
Thanks! All working as expected.
