### ISSUE TITLE
running on production mode still require "src" folder

### ISSUE THREAD

**Issue by gkarwchan** [electrode-io/electrode#576]
running: npm run prod, still require "src" folder.
I run : clap build, which will generate two folders: lib, and dist.
But deleting the "src" folder and running : npm run prod, will not work.

OS version: all OS
Node version: 6
npm version:3.10 & 5.3

## Expected behavior

I am expecting that we don't need src folder in production, specially all its code are copied to lib folder.

## Current behavior
The application will give error if the src folder doesn't exist.

## Steps to reproduce the behavior

run: npm run build (or clap build)
delete src folder
run : npm run prod

**Comment by jchip** [comment]
thanks for filing the issue.  could you add more details about the error please?

**Comment by jchip** [comment]
need more details please.  tried it with newly generated app and it's fine.

**Comment by LuckStock** [comment]
It works fine without src folder for me, though I have another complain, the "dist" folder is hard-coded in electrode sources, so it doesn't allow us to move the project files to another folder/outside of the project dir.
So even, if we configure the webpack config and other config files, it still depends on dist folder to exist under the same path as lib folder.
Therefore, copying the lib folder contents to run the server and contents of dist to the final folder on production machine doesn't work. We're forced to copy the whole project to production machine, and building the project there to run it.
Is it possible to configure the location of dist folder and its contents?
