### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by jchip** [electrode-io/electrode#581]
Some issues with updating to React 16 occur with unit testing.

Currently we are using these modules to support testing in React 15:

- https://github.com/facebook/react/tree/master/packages/react-test-renderer
- https://www.npmjs.com/package/react-addons-test-utils
- chai-shallowly and enzyme 2.x

react-addons-test-utils is deprecated and replaced by `react-dom/test-utils` in react 16.
react-test-renderer has a major v16
enzyme has a major v3 with separate adapters for each version of react

So the problem is it's unlikely we can host both 15 and 16 in a compatible manner.

For now, we can enable react 16 but testing would be broken.

next major version will move to react 16 fully and no longer support lower versions.

**Comment by didi0613** [comment]
Please checkout this gist for more details:
https://gist.github.com/didi0613/efd3f9bf36ca5ff0e80592addf01d17a
