### ISSUE TITLE
update babel-preset-es2015 to babel-preset-env

### ISSUE THREAD

**Issue by jchip** [electrode-io/electrode#591]
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by petiibhuzah** [comment]
i face the the same situation somebody with the solution please!

**Comment by karthikeyana** [comment]
try to install 
`
npm install browserify babelify babel-preset-env`

**Comment by atiyou** [comment]
seems like nobody want to try it 🤔
https://github.com/kottenator/django-compressor-toolkit/issues/5

**Comment by cooervo** [comment]
I tried the solution in here: http://babeljs.io/env

got to .babelrc
change: `"presets": ["es2015"],`
to: `"presets": ["env"]`
