### ISSUE TITLE
Example using MobX

### ISSUE THREAD

**Issue by maxs15** [electrode-io/electrode#629]
Hello guys,

Awesome work !
What do think about adding an exemple to use Electrode with mobx (supporting server rendering) ?
It looks like for now the only possibility is to use redux.. mobx would be a great candidate to show that the framework is open to different state managements librairies.

**Comment by RinatMullayanov** [comment]
I also would be interested to see an example of using `Mobx`.

**Comment by jchip** [comment]
yeah, this would be great.  Added to our Jira board, but we are kind of short hand at the moment.
