### ISSUE TITLE
React Helmet removed?

### ISSUE THREAD

**Issue by karanmartian** [electrode-io/electrode#646]
Hey guys so the latest release of electrode-webapp doesnt have any Helmet server side rendering. It was removed back in August I believe. Could anyone tell me why this was the case? How are we supposed to do server side dynamic title with latest electrode-webapp? This is important for me and many I believe because it affects Search Engine Optimization in a big way.

**Comment by brandonburkett** [comment]
@Bryze You can include a token handler to add in helmet.  This is what I (basically) use inside `/server/token-handler.js`: https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/test/fixtures/react-helmet-handler.js

And in the`config/default.js` you can reference the custom tokenHandler:

```
webapp: {
      module: "electrode-react-webapp/lib/hapi",
      options: {
        pageTitle: "Some Title",
        paths: {
          "/{args*}": {
            htmlFile: "./{{env.APP_SRC_DIR}}/server/views/index.html",
            content: {
              module: "./{{env.APP_SRC_DIR}}/server/views/index-view"
            }
          }
        },
        serverSideRendering: true,
        tokenHandler: "./{{env.APP_SRC_DIR}}/server/token-handler"
      }
    }
```
