### ISSUE TITLE
Can't use alias and externals with custom webpack configuration

### ISSUE THREAD

**Issue by thuannh1027** [electrode-io/electrode#647]
I am trying to customize the webpack configuration. I am using alias to shorten my url declaration and externals for some cases such as: jQuery,...

However, when i import/require, node keeps telling me that "Cannot find module". Please help me out and if you need anything to resolve this, please let me know.

Bug screenshot

`(node:9684) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'Component/home'
(node:9684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

archetype/config/webpack/webpack.config.dev.js

![2](https://user-images.githubusercontent.com/13108786/33134364-1f525fb2-cfd2-11e7-81ca-bb31c2d3d891.PNG)

archetype-debug.log

` {
  "cache": true,
  "plugins": [
    {
      "options": {
        "options": {
          "debug": false
        },
        "test": {}
      },
      "__name": "LoaderOptionsPlugin"
    },
    {
      "filename": "[name].style.[hash].css",
      "id": 1,
      "options": {},
      "__name": "ExtractTextPlugin"
    },
    {
      "options": {
        "size": 4000,
        "preserve": true
      },
      "__name": "CSSSplitWebpackPlugin"
    },
    {
      "options": {
        "options": {
          "context": "D:\\Node\\React\\electrode-boilerplate\\src",
          "stylus": {}
        },
        "test": {}
      },
      "__name": "LoaderOptionsPlugin"
    },
    {
      "opts": {
        "filename": "../server/stats.json",
        "fields": [
          "assetsByChunkName",
          "assets"
        ]
      },
      "__name": "StatsWriterPlugin"
    },
    {
      "config": {
        "valid": false
      },
      "options": {
        "assetsFile": "../isomorphic-assets.json",
        "webpackDev": {
          "url": "http://localhost:2992",
          "addUrl": false
        }
      },
      "__name": "IsomorphicLoaderPlugin"
    },
    {
      "options": {
        "prefix": "icons-[hash]/",
        "emitStats": true,
        "statsFilename": "../server/iconstats.json",
        "persistentCache": true,
        "inject": false,
        "background": "#FFFFFF",
        "logo": "D:\\Node\\React\\electrode-boilerplate\\src\\client\\images\\electrode.png",
        "title": "electrode-boilerplate",
        "icons": {
          "android": true,
          "appleIcon": true,
          "appleStartup": true,
          "coast": false,
          "favicons": true,
          "firefox": true,
          "opengraph": false,
          "twitter": false,
          "yandex": false,
          "windows": false
        }
      },
      "__name": "FaviconsWebpackPlugin"
    },
    {
      "fields": {
        "short_name": "PWA",
        "theme_color": "#FFFFFF"
      },
      "regex": {},
      "__name": "AddManifestFieldsPlugin"
    },
    {
      "config": {},
      "options": {
        "cacheId": "electrode-boilerplate",
        "filename": "service-worker.js",
        "importScripts": [],
        "staticFileGlobsIgnorePatterns": [],
        "mergeStaticsConfig": false,
        "minify": false,
        "staticFileGlobs": [
          "dist/**/*"
        ],
        "stripPrefix": "dist/js/",
        "filepath": "dist/sw.js",
        "maximumFileSizeToCacheInBytes": 4194304,
        "skipWaiting": false,
        "noWarning": true,
        "runtimeCaching": [
          {
            "handler": "fastest",
            "urlPattern": {}
          }
        ]
      },
      "overrides": {},
      "warnings": [],
      "__name": "SWPrecacheWebpackPlugin"
    },
    {
      "opts": {
        "files": [
          {
            "asset": {},
            "output": {
              "filename": "stats.json"
            }
          }
        ],
        "output": {
          "path": "D:\\Node\\React\\electrode-boilerplate\\.etmp"
        }
      },
      "__name": "DiskPlugin"
    },
    {
      "definitions": {
        "process.env.NODE_ENV": "\"development\""
      },
      "__name": "DefinePlugin"
    },
    {
      "sourceMappingURLComment": "\n//# sourceMappingURL=[url]",
      "moduleFilenameTemplate": "webpack:///[resourcePath]",
      "fallbackModuleFilenameTemplate": "webpack:///[resourcePath]?[hash]",
      "options": {
        "sourceMapFilename": "[file].map"
      },
      "__name": "SourceMapDevToolPlugin"
    },
    {
      "filename": "[name].style.css",
      "id": 2,
      "options": {},
      "__name": "ExtractTextPlugin"
    },
    {
      "__name": "NoEmitOnErrorsPlugin"
    }
  ],
  "context": "D:\\Node\\React\\electrode-boilerplate\\src\\client",
  "entry": "./app.jsx",
  "output": {
    "path": "D:\\Node\\React\\electrode-boilerplate\\dist\\js",
    "pathinfo": false,
    "publicPath": "http://localhost:2992/js/",
    "chunkFilename": "[hash].[name].js",
    "filename": "[name].bundle.dev.js"
  },
  "resolve": {
    "alias": {
      "Component": "D:\\Node\\React\\electrode-boilerplate\\src\\client\\components"
    },
    "plugins": [
      {
        "source": "module",
        "path": "node_modules",
        "target": "resolve"
      }
    ],
    "modules": [
      "D:\\Node\\React\\electrode-boilerplate\\src",
      "D:\\Node\\React\\electrode-boilerplate",
      "node_modules"
    ],
    "extensions": [
      ".js",
      ".jsx",
      ".json"
    ]
  },
  "resolveLoader": {
    "modules": [
      "D:\\Node\\React\\electrode-boilerplate\\lib",
      "D:\\Node\\React\\electrode-boilerplate"
    ],
    "plugins": [
      {
        "source": "module",
        "path": "node_modules",
        "target": "resolve"
      }
    ]
  },
  "module": {
    "rules": [
      {
        "test": {},
        "exclude": {},
        "use": [
          {
            "loader": "babel-loader"
          }
        ]
      },
      {
        "test": {},
        "loader": [
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js",
            "options": {
              "omit": 1,
              "remove": true,
              "publicPath": ""
            }
          },
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\style-loader\\index.js"
          },
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\css-loader\\index.js?modules&localIdentName=[name]__[local]___[hash:base64:5]&-autoprefixer"
          },
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\postcss-loader\\index.js"
          }
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "postcss-loader",
            "options": {
              "browsers": [
                "last 2 versions",
                "ie >= 9",
                "> 5%"
              ]
            }
          }
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\url-loader\\index.js",
            "options": {
              "limit": 1000,
              "mimetype": "application/font-woff"
            }
          },
          "D:\\Node\\React\\electrode-boilerplate\\node_modules\\isomorphic-loader\\index.js"
        ]
      },
      {
        "test": {},
        "use": [
          "D:\\Node\\React\\electrode-boilerplate\\node_modules\\file-loader\\index.js",
          "D:\\Node\\React\\electrode-boilerplate\\node_modules\\isomorphic-loader\\index.js"
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\electrode-cdn-file-loader\\index.js",
            "options": {
              "limit": 10000
            }
          },
          "D:\\Node\\React\\electrode-boilerplate\\node_modules\\isomorphic-loader\\index.js"
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "D:\\Node\\React\\electrode-boilerplate\\node_modules\\file-loader\\index.js",
            "options": {
              "name": "manifest.json"
            }
          },
          "D:\\Node\\React\\electrode-boilerplate\\node_modules\\web-app-manifest-loader\\index.js"
        ]
      }
    ]
  },
  "devServer": {
    "https": false,
    "disableHostCheck": true,
    "headers": {
      "Access-Control-Allow-Origin": "*"
    }
  }
}`

**Comment by thuannh1027** [comment]
is there anyone could help me in this case?

**Comment by jchip** [comment]
webpack features like alias and externals only work for webpack, not Node.  In Node, everything falls back to `require`.  Any kind of special behavior has to be done by hacking require.

You have this issue because your UI code is run by server side rendering in Node.  You can turn off SSR by setting in your app config (ie: `config/default.json`), under `plugins.webapp.options.serverSideRendering` to `false`.

**Comment by thuannh1027** [comment]
Thank you so much for this answer!!it save me!!

However, is there any way to work around!? i still need the ssr plugin as well

**Comment by Mairu** [comment]
As workaround you can install **babel-plugin-module-alias** as dev dependency and add the the plugin config in src/client/.babelrc
