### ISSUE TITLE
Question: Is clap meant to be used in Production?

### ISSUE THREAD

**Issue by makstaks** [electrode-io/electrode#730]
Hi there,

I've been reviewing samples and documentation, and I can't determine if `clap` is meant to be used in production. 

**Example 1**
For example, in the Electrode Gitbook [Deploy Your App](https://docs.electrode.io/chapter1/further-develop-app/deploy-your-app.html)

The package.json scripts section looks like this, with a `heroku-postbuild` command using `clap`.

```
"scripts": {
    "start": "if test \"$NODE_ENV\" = \"production\"; then npm run prod; else clap dev; fi",
    "test": "clap test",
    "coverage": "clap check",
    "prod": "echo 'Starting standalone server in PROD mode'; node .",
    "heroku-postbuild": "clap build"
  },
```

Yet the dependencies that will be installed in production doesn't include xclap:

```
"dependencies": {
    "bluebird": "^3.4.6",
    "electrode-archetype-react-app": "^1.0.0",
    "electrode-confippet": "^1.0.0",
    "electrode-redux-router-engine": "^1.2.2",
    "electrode-server": "^1.0.0",
    "electrode-static-paths": "^1.0.0",
    "lodash": "^4.10.1"
  },
```
Side note: Deploying this configuration to Heroku results in an error because `xclap` is not installed.

**Example 2**
In the [Electrode sample project](https://github.com/electrode-samples/electrode-example-app-with-plugin-and-routes/blob/master/package.json) and [this other one](https://github.com/electrode-samples/express-react-redux-webpack/blob/master/package.json), clap isn't used at all.

I can provide other examples, but I'll leave it with these two. Any help will be greatly appreciated.

**Comment by jchip** [comment]
Hi, it's not used in production.  As you can see, the prod script doesn't use it.

**Comment by makstaks** [comment]
@jchip the prod script doesn't use it, but the `"heroku-postbuild": "clap build"` does, so it makes it seem like `clap` can be used in production. [Reference](https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps).

**Comment by jchip** [comment]
As far as I know, one mode of Heroku is not a prod mode.  It expects to download the app from the git repo directly and install all dependencies and then build the app.

**Comment by makstaks** [comment]
Thanks @jchip you've answered by original question that I shouldn't use `clap` in production, so I'll close the issue.  I'll leave the `heroku-postbuild` script discussion as a separate topic.

**Comment by makstaks** [comment]
@jchip sorry re-opening question, I'm still having a hard time reconciling your answer with what I see in your code.  For example, `electrode-archetype-react-app/arch-clap.js`, 

there is this task:

```
const optimizeModuleForProd = module => {
    const modulePath = Path.resolve("node_modules", module);
    assert(shell.test("-d", modulePath), `${modulePath} is not a directory`);
    createGitIgnoreDir(Path.resolve(archetype.prodModulesDir), "Electrode production modules dir");
    const prodPath = Path.join(archetype.prodModulesDir, module);
    const cmd = mkCmd(
      `babel -q ${modulePath} --no-babelrc --ignore dist -D`,
      `--plugins transform-node-env-inline,minify-dead-code-elimination`,
      `-d ${prodPath}`
    );
    return exec(cmd).then(() => {
      const dist = Path.join(modulePath, "dist");
      if (Fs.existsSync(dist)) {
        shell.cp("-rf", dist, prodPath);
      }
    });
  };
```

The entire file makes reference to a production environment.  

So if `clap` isn't meant for production, then why does code like this exist.  What am I missing?

**Comment by jchip** [comment]
that runs at build time to optimize some code for production

**Comment by makstaks** [comment]
Thanks @jchip for confirming. Therefore,  `xclap` is a dependency that needs to be included in the `dependencies` section, because at build time we do in fact use it to build for production.

**Comment by jchip** [comment]
you can add it to your `devDependencies` but it's not required.

**Comment by jshado1** [comment]
@jchip how would Heroku build the app if the builder is a devDependency? Run Prune after building? If certain devDependencies are installed when `clap build` is run, you get #740.

**Comment by jshado1** [comment]
Also, during npm install, it looks like Electrode re-builds itself based on what else is installed, but when you go to subsequently build, Electrode's re-built state is stale and node explodes, saying the dev archetype module is not found.
