### ISSUE TITLE
Clap build app-dev installed explodes

### ISSUE THREAD

**Issue by jshado1** [electrode-io/electrode#740]
## Type of issue

Bug

It's a real pain to be required to un/re- install packages when switching between different modes locally (dev vs build).

----

## My environment

* *OS version/details*: `Mac OSX 10.9.5`
* *Node version:* `6.10.0`
* *npm version:* `3.10.10`
* *Version of yo:* irrelevant

## Expected behavior

It doesn't explode

## Current behavior

It explodes immediately (within 1 second)

## Steps to reproduce the behavior

1. Put `electrode-archetype-react-app` in `dependencies` and `electrode-archetype-react-app-dev` in `devDependencies`
1. Run `npm install`
1. Run `clap build`

## Command line output

```
error: uncaughtException: UglifyJs Plugin Invalid Options

options['compress'] is an invalid additional property

electrode-archetype-react-app-dev/config/webpack/webpack.config.js
```

**Comment by jchip** [comment]
what's app archetype version?

**Comment by jshado1** [comment]
5.1.0

**Comment by jchip** [comment]
can you offer more details on "explodes" please?  I just generated an app with latest electrode-ignite and both `clap build` and `clap dev` work.

We've stopped supporting Node 6 in v5 (ie: no longer running CI with it), but I tested with 6.13.0 and it works also.

**Comment by jshado1** [comment]
`clap build` aborts with the error provided at the bottom of the issue summary.

**Comment by jchip** [comment]
hmm... maybe related to something you have and UglifyJS.  Do you have any custom configs?  If we can isolate what's causing it I'd like to add it to our sample app so it's tested as part of the CI.

**Comment by jshado1** [comment]
We don't use UglifyJS. If we comment out the line in the dev archetype, it's fine.
