### ISSUE TITLE
Consider moving css frameworks for generator

### ISSUE THREAD

**Issue by aequasi** [electrode-io/electrode#749]
Seems like Skeleton hasn't been updated since December of 2014...

Might be time to consider another framework, like [Bulma](https://bulma.io)?

**Comment by didi0613** [comment]
@aequasi Hi Aaron, we are considering using `milligram`. If you wants to get more information, please check [here](https://github.com/milligram).

**Comment by didi0613** [comment]
This one is done. Please close it @jchip
