### ISSUE TITLE
BUG electrode-archetype-react-app-dev  eslint  'TypeError: Cannot read property 'range' of null from template-curly-spacing'

### ISSUE THREAD

**Issue by soundyogi** [electrode-io/electrode#750]
Hiya,
we updated the archetype-react-app-dev today and now linting fails.

Error message:
```TypeError: Cannot read property 'range' of null from template-curly-spacing```

It is known:
https://github.com/babel/babel-eslint/issues/530

**Comment by arty-name** [comment]
Upgrade to babel-eslint@8.2.2 resolved the issue
