### ISSUE TITLE
Deploy app with iisnode

### ISSUE THREAD

**Issue by thuannh1027** [electrode-io/electrode#752]
Could you guy please walk me through to deploy electrode app by using iisnode? I have tried a lot of tutorial articles in the Internet but none works.

**Comment by jchip** [comment]
can you give more details?  how are you deploying? where?  link to iisnode?  have you asked for help from issnode?  

I imagine Electrode doesn't have a lot to do with it.  Have you been able to deploy a simple app?

like the server.js at this page https://hapijs.com/?

**Comment by thuannh1027** [comment]
Sorry for late response, i am using iisnode to deploy an website with Electrode and Express. Here is my web.config

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="iisnode" path="lib/server/index.js" verb="*" modules="iisnode" />
    </handlers>

    <iisnode      
      node_env="%node_env%"
      nodeProcessCountPerApplication="1"
      maxConcurrentRequestsPerProcess="1024"
      maxNamedPipeConnectionRetry="100"
      namedPipeConnectionRetryDelay="250"      
      maxNamedPipeConnectionPoolSize="512"
      maxNamedPipePooledConnectionAge="30000"
      asyncCompletionThreadCount="0"
      initialRequestBufferSize="4096"
      maxRequestBufferSize="65536"
      watchedFiles="*.js;iisnode.yml"
      uncFileChangesPollingInterval="5000"      
      gracefulShutdownTimeout="60000"
      loggingEnabled="true"
      logDirectory="iisnode"
      debuggingEnabled="true"
      debugHeaderEnabled="false"
      debuggerPortRange="5058-6058"
      debuggerPathSegment="debug"
      maxLogFileSizeInKB="128"
      maxTotalLogFileSizeInKB="1024"
      maxLogFiles="20"
      devErrorsEnabled="true"
      flushResponse="false"      
      enableXFF="false"
      promoteServerVars=""
      configOverrides="iisnode.yml"
     />
  </system.webServer>
</configuration>`

It runs well. However, it always redirect to the path "/lib/server". For example, "localhost:8000/lib/server" and i dont know how to configure back to normal path "/".

**Comment by aaroncalderon** [comment]
I was able to deploy the sample app with the following configuration:

The configuration below is set for the node app to recide at the root of the site, and on port 80

## Steps

1.  Cereate a file on the root of your IIS site called `app.js`
    - You can choose the name as you wish, just make shure you update the `web.config` file to reflect your new file name. I used this approach because I was having issues with paths and include commands otherwise
        - [Nested Server](https://github.com/tjanczuk/iisnode/issues/338)
        - [Point iisnode at server.js file nested in folder in an iis website
](https://stackoverflow.com/a/23520004/3991654)
2. Configure your `web.config`. Sample is shown below.

/app.js

```js
require(__dirname + '\\lib\\server\\index.js');
```

/web.config

```xml
<configuration>
  <system.webServer>

    <!-- SAMPLE 

    Indicates that the app.js file is a node.js application 
    to be handled by the iisnode module -->

    <handlers>
      <add name="iisnode" path="app.js" verb="*" modules="iisnode" />
    </handlers>

    <!-- use URL rewriting to redirect the entire branch of the URL namespace
    to app.js node.js application; 
        
    Additional Configuration Ideas
    https://tomasz.janczuk.org/2012/05/yaml-configuration-support-in-iisnode.html
    -->
    
    <rewrite>
      <rules>
          <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">  
                <match url="iisnode"/>  
          </rule>  
          <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">                      
              <match url="^/app.js\/debug[\/]?" />  
          </rule>  
          <rule name="StaticContent">  
                <action type="Rewrite" url="{{REQUEST_URI}}"/>  
          </rule>  
          <rule name="DynamicContent">  
                <conditions>  
                    <add input="{{REQUEST_FILENAME}}" matchType="IsFile" negate="True"/>  
                </conditions>  
                <action type="Rewrite" url="app.js"/>  
          </rule>
      </rules>
    </rewrite>
        <!-- 
        The key elements are:
          maxNamedPipeConnectionRetry="100" 
          namedPipeConnectionRetryDelay="250"  
        -->
    <iisnode
        maxNamedPipeConnectionRetry="100"
        namedPipeConnectionRetryDelay="250"
    />
  </system.webServer>
</configuration>
```
