### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by brideofscience** [electrode-io/electrode#753]
## Type of issue

Feature Request

Tried to use a .scss file with the latest ignite version (2.0.3) of Electrode without success. Can Sass support please be added to Electrode? I realize there are some are methods other users have found to adding to the webpack for Sass, but so far I have not found a solution that will support Sass for the server side render.

It would be great if .scss/.sass files could be supported, both client side and server side builds, and work with the postcss and css modules tasks already in place.

**Comment by devourment77** [comment]
Agreed, I am looking for this feature as well.

**Comment by dan3721** [comment]
Can someone from the Electrode community comment/acknowledge this issue?

**Comment by devourment77** [comment]
I found this: https://github.com/electrode-io/electrode/issues/333

It looks like a little custom configuration is all that is needed.  My issue specifically was node barfing on .scss imports server side.

**Comment by didi0613** [comment]
Hello,
Here is a small example for electrode component with sass: https://github.com/didi0613/oss-electrode-component-sass-example
The example is a client side render component, please check it out and let me know if you have any issues. Thanks!

**Comment by AdaByronLovelace** [comment]
Any plans to merge this into the component archetype?

**Comment by didi0613** [comment]
@AdaByronLovelace Yea i am currently working on it. Will PR soon.

**Comment by didi0613** [comment]
@AdaByronLovelace It should be released now. Please check it out and let me know any issues.
Thanks

**Comment by AdaByronLovelace** [comment]
Thanks @didi0613 It looks great.
