### ISSUE TITLE
Are there plans to update to hapi v17, React v16 and React Router v4?

### ISSUE THREAD

**Issue by SamuelEarl** [electrode-io/electrode#766]
I read this issue about [updating to hapi v17](https://github.com/electrode-io/electrode-server/issues/25) and was wondering if there is a status update or a possible timeline for when Electrode will be updated to hapi v17? Also, do you have plans for updating Electrode with React v16 and React Router v4? If so, do you have a timeline for when that might happen?

Thank you for such an awesome project! I am loving Electrode!

**Comment by jchip** [comment]
- we are still figuring out how to upgrade to hapi 17 since that's a leave everything behind kind of major upgrade.

- we've upgraded to react 16

- react router v4 - same thing like hapi 17

**Comment by karanmartian** [comment]
Hi @jchip anything on the react router v4 compatibility front? Is the issue about supporting <ConnectedRouter> and other new components. What exactly is the compatibility issue? Anything you could suggest so that electrode could be made to work with rr v4?

**Comment by jchip** [comment]
It's still in the consideration phase.  v4 is a dynamic router vs. static router.  For SSR, it has to be static.  Even v4 has a bunch of tools to make it useable as static router.  Electrode's tied to the router is really just in the redux router engine.  It's possible to use rr4 if that's not used.

**Comment by jchip** [comment]
react router 4 support released https://docs.electrode.io/advanced/stand-alone-modules/redux-router-engine
