### ISSUE TITLE
Babel transform-class-properties support for static class properties.

### ISSUE THREAD

**Issue by devourment77** [electrode-io/electrode#769]
## Feature Request
It doesn't look like babel transform-class-properties is enabled, which means that using static propTypes / defaultProps on class components gives an error.  Any reason why these are not enabled out of the box?

Example
```
class MyComponet extends Component {
  static propTypes = {
    coverImageUrl: PropTypes.string,
    coverCaption: PropTypes.string,
    imageUrl: PropTypes.string,
    imageAlt: PropTypes.string,
    as: PropTypes.node,
    children: PropTypes.node,
  };

  static defaultProps = {
    coverImageUrl: '',
    coverCaption: '',
    imageUrl: '',
    imageAlt: '',
    as: '',
    children: '',
  };
...
}
```

This results in the following webpack build error: `Module build failed: SyntaxError: Unexpected token`

**Comment by jchip** [comment]
we generally avoid TC39 proposals at stage 3 or earlier.  https://tc39.github.io/process-document/

**Comment by devourment77** [comment]
@jchip Thanks for the feedback.  Assume it is fine to append `/src/client/.babelrc` without side effects?

```
{
  "extends": "electrode-archetype-react-app-dev/config/babel/babelrc-client",
  "plugins": [
    ["transform-class-properties"]
  ]
}
```

**Comment by devourment77** [comment]
This can be closed out, the above works great!
