### ISSUE TITLE
Are where any plans to switch to Jest instead of Karma?

### ISSUE THREAD

**Issue by romanlv** [electrode-io/electrode#771]
## Type of issue
Feature request/Question

or what's the recommended approach if I want to use Jest in my project?

**Comment by devourment77** [comment]
It would be nice if this kind of thing was an option similar to express / hapi when starting an app.

**Comment by jchip** [comment]
yeah, we are planning to allow tests for karma and jest to co-exist and will detect and run them both.

**Comment by jchip** [comment]
jest is now auto detected and run
