### ISSUE TITLE
Service Workers - sw.js 404 error

### ISSUE THREAD

**Issue by denny64** [electrode-io/electrode#781]
## Type of issue
Bug

----

## My environment

* *OS version/details*: `mac 10.13.3`
* *Node version:* `8.8.1` (run `node --version` in your terminal)
* *npm version:* `5.4.2` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

No errors...

## Current behavior

I setup a completely fresh project via `ignite generate-app`

Did `clap build`, then ran `clap pwa`.

Getting error: 

```
sw.js:166 Uncaught (in promise) Error: Request for http://localhost:3000/dist/isomorphic-assets.json?_sw-precache=faeaed7e726412d70a82711d9a06892c returned a response with status 404
    at sw.js:166
(anonymous) @ sw.js:166
ed5067ae1d9a8c663c4e.sw-registration.js:1 Service worker has become redundant
```

Clicking on that 404 url above yields:
`{"status":404,"message":"redux-router-engine: Path /dist/isomorphic-assets.json not found"}`

However, I can see that that file does exist inside the dist folder.

`/dist/isomorphic-assets.json`

```
{
  "chunks": {
    "sw-registration": [
      "f3f0df993ba72ee921bd.sw-registration.js",
      "../map/f3f0df993ba72ee921bd.sw-registration.js.map"
    ],
    "main": [
      "main.bundle.f3f0df993ba72ee921bd.js",
      "main.style.f3f0df993ba72ee921bd.css",
      "../map/main.bundle.f3f0df993ba72ee921bd.js.map"
    ]
  },
  "marked": {
    "src/client/images/electrode.png": "2b7ac2d4ff91cca5b9c8e742eda58b24.png"
  }
}
```

## Steps to reproduce the behavior

See above.

## Command line output

No errors in command line

**Comment by devourment77** [comment]
Were you able to get this working?

**Comment by denny64** [comment]
I wasn't able to get it to work. Will give that a try, thanks!

**Comment by devourment77** [comment]
@denny64 I spent some time on this yesterday and was able to get it to work, but it may have side effects.  I made the following changes (see `staticFileGlobs` and `stripPrefix`)

sw-config.js
```
module.exports = {
  cache: {
    cacheId: "app-ui",
    runtimeCaching: [{
      handler: "fastest",
      urlPattern: "\/$"
    }],
    // staticFileGlobs: ['dist/**/*'], // original
    staticFileGlobs: ['dist/js/**/*'],
    stripPrefix: 'dist/', // added custom
  },
  manifest: {
    background: "#FFFFFF",
    title: "MyApp",
    logo: "./styles/icons/icon-green-192.png",
    short_name: "MyApp",
    theme_color: "#FFFFFF"
  }
};
```

After that, I no longer received 404s, but the sw also doesn't cache any of the following (and I am unsure of the side effects or if caching of the below files are actually needed):
- /dist/server/*
- /dist/map/*
- /dist/isomorphic-assets.json
- /dist/raw-messages.json

**Comment by adybfadel** [comment]
I'm having the same issue. Did you find any solution or workaround? Thanks!

**Comment by jchip** [comment]
- dist has to be built with `clap build` first
- there was a bug that dev deletes dist.  fixed now.
