### ISSUE TITLE
Windows 10 - Cannot run Gulp Check due to Sinon errors

### ISSUE THREAD

**Issue by alecwhittington** [electrode-io/electrode#80]
I've been trying to get our tests running from a Generated Component project, but have not been able to get any further than linting as Sinon is causing problems.

Here is what I am seeing from my console (truncated to show only the important pieces):

17 12 2016 12:32:23.618:INFO [karma]: Karma v0.13.22 server started at http://localhost:8080/
17 12 2016 12:32:23.634:INFO [launcher]: Starting browser PhantomJS
17 12 2016 12:32:24.044:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket akvOIblAU_ceFTgQAAAA with id 21202378
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  Error: Cannot find module './sinon/util/core'.
  at F:/@Salucro/salucro-reactor-common/node_modules/electrode-archetype-react-component/config/karma/entry.js:49021

PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.094 secs / 0 secs)

Unfortunately this is a blocking issue for us as it makes zero sense to continue writing components when we cannot test them through the component archetypes. 

I've spent more than an hour researching the issue, but cannot get past the error. I've verified that the node_modules/sinon/lib/sinon/util folder exists and there is a core module there. Seems like some sort of pathing issue based on the cannot find module error.

Also tried generating another component project and just running gulp check as soon as it is generated and NPM modules are installed. Same result

**Comment by alecwhittington** [comment]
More information:

Found the cause of the error. In the node_modules\electrode-archetype-react-component\config\webpack\webpack.config.test.js file, line 24. The pathing will not work for Windows.

Had to change from:
```javascript
/node_modules\/sinon\//
```
to
```javascript
/node_modules\\sinon\\/
```

for it to work on windows. This is a pretty big problem as we have developers that use Windows, Mac, and Linux.

**Comment by alecwhittington** [comment]
Fixed issue for Windows as well as Linux bases systems. Pull Request issued

**Comment by jchip** [comment]
thanks for the fix. published https://github.com/electrode-io/electrode/commit/1caca411b6de686b79ec747c3c89d4af0b41b4a3
