### ISSUE TITLE
ReactDOM.hydrate change in PR #787 causes server vs client mismatch 

### ISSUE THREAD

**Issue by CM-mlazzaro** [electrode-io/electrode#804]
When setting up a new electrode app using ignite or yeoman, the page throws an error `warning.js:33 Warning: Text content did not match. Server: "Hello from  " Client: "Hello from "`. Further updates to the jsx files don't seem to fix either. Seems like the server content is always 1 version behind what the client is displaying which throws the error.

----

* *OS version/details*: `MAC OS 10.12.5`
* *Node version:* `8.11.2`
* *npm version:* `5.6.0`
* *Version of yo :* `2.0.2`

**Comment by jchip** [comment]
this may be due to issue with PWA service worker.  reload a few times may make it go away.
