### ISSUE TITLE
Using renovate to update archetypes

### ISSUE THREAD

**Issue by mcrowder65** [electrode-io/electrode#806]
Joel, 

We should consider adding renovate - https://github.com/renovateapp/renovate to this repo to keep our archetypes up to date. 

I have been using it for my own OSS projects and have loved it. 

I think it would be especially helpful for WML developers who use electrode. Because then we don’t have to worry about worrying about updating. Just update the archetypes

**Comment by jchip** [comment]
Hi Matt, thanks for the idea.  We will add this to our timeline and look into it.

**Comment by mcrowder65** [comment]
@jchip idk how you handle your backlog. Feel free to close this

**Comment by jchip** [comment]
unfortunately I am afraid we cannot use Renovate because it's AGPL license.
