### ISSUE TITLE
Fail creating generating app with Ignite, Windows 10 64bit

### ISSUE THREAD

**Issue by gentijo** [electrode-io/electrode#812]
I am running Windows 10, 64 bit latest update.
Node is a fresh install of 10.4.1 in a directory with no spaces.
Ignite was the only package installed. 
Ignite check nodejs passes just fine.
When I go to generate an app, I get the error below.
The current directory is also a directory with no spaces.

I also tried this with Node 8.11.3, same failure.
-John

7] ☞ Exit
---------------------------------------------------------
Please select your option: 1
You chose 1
checking node and npm versions .. ◴
[00:05:31] You are using Node version 10.4.1. Electrode should work for you.
[00:05:31] You are using npm version 6.1.0. Electrode should work for you.
[00:05:31] Your Node binary path is: D:\Programs\nodejs\node.exe
Press enter to continue ...
---------------------------------------------------------
Electrode Ignite 2.0.7
---------------------------------------------------------
[1] ☑ Check your NodeJS and npm environment
[2] ♡ Generate an Electrode application
[3] ☆ Generate an Electrode component repo
[4] ✪ Add a React component to your electrode component repo
[5] ☺ Electrode Open Source official documenation
[6] ☃ Check for electrode-ignite update
[7] ☞ Exit
---------------------------------------------------------
Please select your option: 2
You chose 2
Generate an Electrode application (Y/N): y
[00:05:36] Loading generator electrode ...
[00:05:36] Running electrode generator failed: Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19).

D:\Projects\Sooth\Code\MobileApp>

**Comment by jchip** [comment]
What does the command `where ignite` show you?

**Comment by gentijo** [comment]
It seems that even though I installed Node in a directory with no spaces, NPM/Node is storing packages in my %APPDATA% directory which has a space in it.  Nothing in any of the log files seem to indicate that. I installed Cygwin tools, so I could do a "which ignite" and is showed that it was stored in my AppData directory.  

Foolishly I decided to try and "fix" my home directory to remove the space which totally thrashed my computer.  After hours of backups using xcopy and re-installing windows, I can say that the app generator is now working and the generated app is running fine.  

Thank you for the feedback.

-John

**Comment by jchip** [comment]
sorry about losing your home directory, but glad you got it sorted.

I thought windows 10 would've been better now and use a user id w/o spaces to create your home dir, but guess not.

Just a quick tip, if you ever need to fix something similar, then it's probably easier to just create a new user but make sure the user id has no space (obviously you can use full name with spaces, just not the user id).

We've done a lot of work to make things work on Windows, but obviously this is an issue we missed in our code or some module we use that's not taking into account of paths with spaces.  We all use *nix machines so spaces in identifiers, paths, and user_ids is something we are not accustomed to.
