### ISSUE TITLE
Implement client-side routing

### ISSUE THREAD

**Issue by pshivareddy** [electrode-io/electrode#828]
## Type of issue

----

## My environment

* *OS version/details*: mac
* *Node version:* `9.3.0` (run `node --version` in your terminal)
* *npm version:* `5.5.1` (run `npm --version` in your terminal)

## Client-side routing 

I am completely new to electrode. Here I am trying to implement client-side routing requires only to fetch data from db and rebuild redux store. Could you please help me on this and let me know if any info is required?

**Comment by jchip** [comment]
Hi, not sure how we can help you.  If you have any thing specific related to Electrode please post them.  Thanks.
