### ISSUE TITLE
Cannot wrap routes with a different react library

### ISSUE THREAD

**Issue by mgardner-at-ebsco** [electrode-io/electrode#843]
## Type of issue
bug
----

## My environment

* *OS version/details*: `MacOS 10.12.6 / Chrome Version 67.0.3396.87 (Official Build) (64-bit)`
* *Node version:* `v8.9.4`
* *npm version:* `5.7.1`

## Expected behavior

You should be able to wrap the react router with different libraries such as `React-Intl` so the web-app is wrapped at the app level and you don't have to wrap each component.

## Current behavior

If you wrap react-router with a different library other than Redux it will mess up the the initial state that was set in `electrode-redux-router-engine` and cause all values to be empty objects or null

## Steps to reproduce the behavior

1. Wrap the routes with another react library besides redux
```
window.webappStart = () => {
  const initialState = window.__PRELOADED_STATE__;
  const store = configureStore(initialState);

  render(
    <Provider store={store}>
      <IntlProvider
        locale={this.props.locale.mappedLocale}
        messages={this.props.locale.messages}>
        <Router history={browserHistory}>
          {routes}
        </Router>
      </IntlProvider>
    </Provider>,
    document.querySelector(".js-content")
  );
};
```

2. Create the Redux Router Engine
```
const createReduxStore = function(req) {

  const initialState = {
       person: {
            name: "test",
            height: "6'0"
            weight: "160 lbs"
       },
       test: "test"
  };
  const store = configureStore(initialState);

  return Promise.all(actions).then(() => store).catch(() => store);
};

module.exports = req => {
  if (!req.server.app.routesEngine) {
    req.server.app.routesEngine = new ReduxRouterEngine({ routes, createReduxStore });
  }

  return req.server.app.routesEngine.render(req);
};
```
3. Start the app and notice that the state of person and test are both empty objects.

**Comment by jchip** [comment]
We just release a new major v2 of electrode-redux-router-engine that uses react router 4.  Can you give that a try please?

**Comment by jchip** [comment]
We are moving to react router 4.
