### ISSUE TITLE
Docs: getting started links broken

### ISSUE THREAD

**Issue by benhalverson** [electrode-io/electrode#847]
## Type of issue

Bug 

----

## Expected behavior
A working link

## Current behavior

404 error

## Steps to reproduce the behavior
visit this link 
https://docs.electrode.io/quick-start/getting-started-with-electrode
click on any of the links 
```
​Start With Electrode Ignite​
​Create an Electrode App​
​Create an Electrode Component​
```
## Command line output

```
Github 404 error page
https://github.com/electrode/electrode/tree/f74782235ae19416900439e1a9590197277b78d2/chapter1/quick-start/start-with-ignite.md
```

**Comment by jchip** [comment]
thanks, we will get them updated.
