### ISSUE TITLE
WEBPACK_DEV_HOST vs WEBPACK_HOST and cors

### ISSUE THREAD

**Issue by devourment77** [electrode-io/electrode#848]
## Type of issue
Bug

----

## My environment

* *OS version/details*: `MacOS 10.13.5  / Chrome Version 67.0.3396.87 (Official Build) (64-bit)`
* *Node version:* `10.3.0` (run `node --version` in your terminal)
* *npm version:* `6.1.0` (run `npm --version` in your terminal)

## Expected behavior

`tiff` and `woff` font files to be served from `localhost` in development by default, or respect `process.env.WEBPACK_DEV_HOST` setting from xclap.js

## Current behavior

Default seems to be `127.0.0.1`, which gives cors errors when using localhost:3000 in the browser

## Steps to reproduce the behavior
- import a tiff / woff font file
- open localhost:3000 in browser
- get CORS error because webpack is using 127.0.0.1

Please note that in `xclap.js`, it looks like there is an option to set `process.env.WEBPACK_DEV_HOST = "localhost";`, but this did not do anything.  I had to set `process.env.WEBPACK_HOST = "localhost";` to get around the CORs issue.

See `electrode-react-webapp/lib/react-webapp.js`

```
devServer: {
      host: process.env.WEBPACK_HOST || "127.0.0.1",
      port: process.env.WEBPACK_DEV_PORT || "2992",
      https: Boolean(process.env.WEBPACK_DEV_HTTPS)
    },
```

Browser Error
```
Access to Font at 'http://127.0.0.1:3000/js/af95bc0abb1c03926838a9f84b5028b3.woff' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

**Comment by didi0613** [comment]
@devourment77  Thanks for reporting the issue. 
Please review: https://github.com/electrode-io/electrode/pull/868

**Comment by devourment77** [comment]
Cool!  Question as a framework users, what is the actual difference between the usage of rocess.env.WEBPACK_DEV_HOST and process.env.WEBPACK_HOST?  Does it matter which we use?  Any side effects if we pick one over the other?

**Comment by jchip** [comment]
`WEBPACK_DEV_HOST` is the correct one.

`WEBPACK_HOST` was a typo and it just got stuck.
