### ISSUE TITLE
Universal React App + React Router 4 + server side redirect stopped working.

### ISSUE THREAD

**Issue by kuldippujara** [electrode-io/electrode#862]
## Type of issue
Bug

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
NodeJS version v8.10.0 
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
5.6.0
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior
It should redirect sever side.

## Current behavior
Its Adding status 302 but not adding path to response so blank white screen displaying.

## Steps to reproduce the behavior
add new route 
{
        path: "/old-url",
        component: () => <Redirect from={"/old-url"} to={"/"} />
}

and also update /server/views/index-view.jsx
from 
app.routesEngine = new ReduxRouterEngine({ routes });
to
routesEngine = new ReduxRouterEngine({ routes, componentRedirect: true });
## Command line output

```
now try in your browser to open "/old-url" it should redirect to "/" but its just load page with 302 status and blank page.
```

found the issue in
https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/react/token-handlers.js#L839
Transform Function removing all other parameter if its not 200 (OK) but it should check if its Redirect Response then Path must be set as 
Hapi Plugin is expecting path when status is Redirect 
https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/hapi/index.js#L23

**Comment by devourment77** [comment]
Is this how we should do redirects in RRv4 (like the example above)?
```
{
path: "/old-url",
component: () => <Redirect from={"/old-url"} to={"/"} />
}
```
