### ISSUE TITLE
make node-sass an optional dependency

### ISSUE THREAD

**Issue by romanlv** [electrode-io/electrode#913]
Right now it installs `node-sass` even if it's not used (and as far as I know support is broken at the moment)
The actual install takes a lot of time and it's subject to issues in the build environment 

it is also the biggest package in the node_modules `255Mb`, which bloats our docker image

We are using `yarn` (if it makes a difference)

**Comment by romanlv** [comment]
thank for response, if there is a way to check if it's `node-sass` included in the main project (or require it dynamically) please do it.  

Yes, `yarn vs npm` is ongoing debate, but `yarn` it seems to be the fastest tool given current environment/implementation. 

Btw, i just checked the total size of our monorepo with node_modules, and `yarn` managed repo is smaller than `npm` managed one (`~10%` smaller)

**Comment by jchip** [comment]
http://npmjs.com/package/fyn is the fastest if you need speed on installing your packages.

**Comment by didi0613** [comment]
@romanlv Hi, I've created a PR: https://github.com/electrode-io/electrode/pull/920 to resolve this issue. Please let me know if there are any other questions.
