### ISSUE TITLE
React-resolver removed?

### ISSUE THREAD

**Issue by sbuys** [electrode-io/electrode#96]
Was this removed from the project? Listed in the docs (http://www.electrode.io/docs/whats_inside.html):

> If you have a universal application and server-side rendering, react-resolver handles bootstrapping server-rendered markup via Resolver.render instead of ReactDOM.render.

But I don't see it anywhere in a new project generated via _yo_

**Comment by jchip** [comment]
hi, thanks for reporting this.  The new generated app is using redux-router engine now instead.

**Comment by animesh10** [comment]
We will be updating our documentation to reflect this change.
