### ISSUE TITLE
Webpack config customization

### ISSUE THREAD

**Issue by sbuys** [electrode-io/electrode#97]
Are there any pathways to customizing the webpack config? e.g. adding loaders

**Comment by vimcat** [comment]
Now that #109 has been merged, how do we use it? Do we just have to add a webpack object into config/default.js?

**Comment by nevos** [comment]
Still trying to figure out how to customize my host. I've added 
    "publicPath": "http://MY_IP:2992/js/" 
to my entry.config.js
but my .isomorphic-loader-config.json is overriding that.

**Comment by ananavati** [comment]
@vimcat 

pr #109 has been merged, pending:
1. writing up `Usage` docs in README.
2. publishing a new version of the `electrode-archetype-react-app` with this change (currently targeted for 01/31).

tl;dr on how to extend/override webpack config:

Everything in [config/webpack](https://github.com/electrode-io/electrode/tree/master/packages/electrode-archetype-react-app/config/webpack) that starts with `webpack` is extendable by putting a file of the same name in your root. So `webpack.config.js, webpack.config.test.js`, etc..

for example: @jshado1 brought up a use-case here https://gitter.im/electrode-io/electrode

Use-case: `how to register with Electrode a postcss plugin, like postcss-strip-inline-comments`

Solve: 
define a file : `/<app>/webpack.config.js` with this as the code inside of it:
```
const baseConfig = require("electrode-archetype-react-app/config/webpack/webpack.config.js");

module.exports = {
    postcss: function() {
        const plugins = baseConfig.postcss();

        return [...plugins, 
            // new plugins go here
        ]
    }
};
```

**Comment by citelao** [comment]
@ananavati 's method is working; is this issue waiting on documentation?

**Comment by karlhorky** [comment]
> writing up Usage docs in README

Does this still need to be done?

cc @jmcriffey @ananavati @jchip

**Comment by karlhorky** [comment]
Actually, I've just opened #262 for this.

**Comment by karlhorky** [comment]
@ananavati you could link directly to the point in history in gitter about the original use case:

https://gitter.im/electrode-io/electrode?at=588156d56c1635643c5058bd
